#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contract-deployment-address.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet:
       writable */

const
  _libcrash =
  require(
    "crash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _printf */
const
_printf =
  _libcrash._printf;
/* global
     _process_exit */
const
_process_exit =
  _libcrash._process_exit;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evm-contract-deployments-versions.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       runtime_environment:
         writable */
  runtime_environment =
    "";
  /* global
       resolve_date:
         writable */
  resolve_date =
    "";
  /* global
       config_file:
         writable */
  config_file =
    "";
  /* global
       display_highest:
         writable */
  display_highest =
    "";
  /* global
       display_lowest:
         writable */
  display_lowest =
    "";
  quiet =
    "";
  /* global
       verbose:
         writable */
  verbose =
    "";
}

async function 
  _overrides_set(
    _help_display) {
  if ( resolve_date == "" ||
       typeof(
         resolve_date) == "undefined" ) {
    resolve_date =
      _get_date_human();
  }
  if ( display_highest == "" ) {
    display_highest =
      "n";
  }
  if ( display_lowest == "" ) {
    display_lowest =
      "n";
  }
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `             Resolve date:   ${resolve_date}`,
      `       Configuration file:   ${config_file}`,
      `          Display highest:   ${display_highest}`,
      `           Display lowest:   ${display_lowest}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "",
      "Returns available versions for contract deployments on a network",
      "",
      "Usage:",
      "",
      `  ${app_name}`,
      "    [options]",
      "    <config-file>",
      "",
      "  options:",
      "",
      "     -H --display-highest            Display highest versions available.",
      `                                     Default: '${display_highest}`,
      "",
      "     -L --display-lowest             Display lowest versions available.",
      `                                     Default: '${display_lowest}`,
      "",
      "     -h --help                       This message.",
      "     -v --verbose                    Enable verbose output.",
      ""
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _process_exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "H",
        "display-highest",
        "L",
        "display-lowest",
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  quiet = 
    "y";
  runtime_environment =
    "node";
  if ( _argv[
         "h"] ) {
    _help_display =
      true;
  }
  if ( _argv[
         "help"] ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    await _overrides_set(
      _help_display);
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Target application " +
      "argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  target_app =
    _argv[
      "_"][
        0];
  if ( "H" in _argv ) {
    display_highest =
      _argv[
        "H"];
  }
  if ( "display-highest" in _argv ) {
    display_highest =
      _argv[
        "display-highest"];
  }
  if ( "L" in _argv ) {
    display_lowest =
      _argv[
        "L"];
  }
  if ( "display-lowest" in _argv ) {
    display_lowest =
      _argv[
        "display-lowest"];
  }
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"] ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  let
    _method,
    _network;
  runtime_environment =
    "browser";
  config_file =
    _argv_url_get(
      "config_file")[
        0];
  display_highest =
    _argv_url_get(
      "display_highest")[
        0];
  display_lowest =
    _argv_url_get(
      "display_lowest")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

async function
  _evm_contract_deployment_versions_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      await _evm_contract_deployment_versions.apply(
        null,
        app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "object" ) {
    for ( _result of _results ) {
      console.log(
        _result);
    }
  }
  else if ( _results_type == "string" ) {
    _printf(
      _results);
  }
}

async function
  _main() {
  const
    _overrides_set_up =
      await _overrides_set();
  _config_show();
  const
    app_opts = [
      target_app,
      user_level
    ];
  const
    _versions =
      await _evm_contract_deployment_versions.apply(
        null,
        app_opts);
}

_global_variables();
if ( _cmdline_check(
       "evm-contract-deployments-versions.js") ||
     _cmdline_check(
       "evm-contract-deployments-versions") ) {
  _cmdline_parse();
}
else{
  _url_parse();
}
_main();
