#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contract-deployment-bytecode.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet:
       writable */

const
  _libcrash =
  await import(
    "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _libevm_contract_deployment_bytecode_module =
    await import(
      "./libevm-contract-deployment-bytecode");
/* global
     _evm_contract_deployment_bytecode */
const
  _evm_contract_deployment_bytecode =
    _libevm_contract_deployment_bytecode_module._evm_contract_deployment_bytecode;
/* global
     _contract_version_auto_detect */
const
  _contract_version_auto_detect =
    _libevm_contract_deployment_bytecode_module._contract_version_auto_detect;
/* global
     _deployments_dir_auto_detect */
const
  _deployments_dir_auto_detect =
    _libevm_contract_deployment_bytecode_module._deployments_dir_auto_detect;
/* global
     _networks_all_auto_detect */
const
  _networks_all_auto_detect =
    _libevm_contract_deployment_bytecode_module._networks_all_auto_detect;
/* global
     _target_app_auto_detect */
const
  _target_app_auto_detect =
    _libevm_contract_deployment_bytecode_module._target_app_auto_detect;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evm-contract-deployments-bytecode.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       runtime_environment:
         writable */
  runtime_environment =
    "";
  /* global
       resolve_date:
         writable */
  resolve_date =
    "";
  /* global
       target_networks:
         writable */
  target_networks =
    [];
  /* global
       network_ids:
         writable */
  network_ids =
    [];
  /* global
       networks_all:
         writable */
  networks_all =
    "";
  /* global
       target_app:
         writable */
  target_app =
    "";
  /* global
       target_contract:
         writable */
  target_contract =
    "";
  /* global
       contract_version:
         writable */
  contract_version =
    "";
  /* global
       user_defined:
         writable */
  user_defined =
    "";
  /* global
       configuration_format:
         writable */
  configuration_format =
    "";
  /* global
       deployments_dir:
         writable */
  deployments_dir =
    "";
  quiet =
    "";
  /* global
       verbose:
         writable */
  verbose =
    "";
}

async function 
  _overrides_set(
    _help_display) {
  _override_set(
    "resolve",
    "date",
    _get_date_human());
  _override_set(
    "configuration",
    "format",
    "bash");
  _networks_all_auto_detect();
  _override_set(
    "user",
    "defined",
    "n");
  await _target_app_auto_detect();
  await _deployments_dir_auto_detect();
  await _contract_version_auto_detect();
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `             Resolve date:   ${resolve_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `          Target networks:   ${target_networks}`,
      `    Network ID (chain ID):   ${network_ids}`,
      `             All networks:   ${networks_all}`,
      `       Target application:   ${target_app}`,
      `     User-defined address:   ${user_defined}`,
      `         Deployments path:   ${deployments_dir}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "",
      "Returns an EVM network's contract deployment address",
      "",
      "Usage:",
      "",
      `  ${app_name}`,
      "    [options]",
      "    <target-contract>",
      "",
      "  networks:",
      "    All those supported",
      "    by 'evm-chains-info'.",
      "",
      "  options:",
      "",
      "     -n, --network <network>              EVM network name.",
      "     -i, --chain-id <number>              EVM network id (chain ID).",
      "     -a, --target-app <app>               Application whose target",
      "                                          contract is part of.",
      `                                          Default: '${target_app}`,
      "     -A, --networks-all                   Returns address for all",
      "                                          available networks.",
      `                                          Default: '${networks_all}`,
      "     -V, --contract-version <version>     Contract version.",
      `                                          Default: '${contract_version}`,
      "     -u, --user-defined                   Returns contract address for",
      "                                          user-defined file system",
      "                                          deployment instead of the system",
      "                                          one.",
      `                                          Default: '${user_defined}`,
      "     -d, --deployments-dir <dir>          Specify contract deployments",
      "                                          directory path.",
      `                                          Default: '${deployments_dir}`,
      "     -f, --configuration-format <format>  Specify contract deployments",
      "                                          directory path.",
      `                                          Default: '${configuration_format}`,
      "",
      "     -h --help                            This message.",
      "     -v --verbose                         Enable verbose output.",
      ""
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "A",
        "networks-all",
        "u",
        "user-defined",
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _global =
      _global_get();
  const
    _options =
      _argv[
        "_"];
  _global[
    "quiet"] = 
    "y";
  _set(
    "runtime",
    "environment",
    "node");
  if ( _argv[
         "h"] ) {
    _help_display =
      true;
  }
  if ( _argv[
         "help"] ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    _global[
      "quiet"] =
      "n";
    await _overrides_set(
      _help_display);
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Target contract " +
      "argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  _set(
    "target",
    "contract",
    _argv[
      "_"][
        0]);
  const
    _target_networks =
      _get(
        "target",
        "networks");
  if ( "n" in _argv ) {
    _target_networks.push(
      _argv[
        "n"].toString());
  }
  if ( "network" in _argv ) {
    _target_networks.push(
      _argv[
        "network"].toString());
  }
  _set(
    "target",
    "networks",
    _target_networks);
  const
    _network_ids =
      _get(
        "network",
        "ids");
  if ( "i" in _argv ) {
    _network_ids.push(
      _argv[
        "i"].toString());
  }
  if ( "network-id" in _argv ) {
    _network_ids.push(
      _argv[
        "network-id"].toString());
  }
  _set(
    "networks",
    "ids",
    _network_ids);
  if ( "a" in _argv ) {
    _set(
      "target",
      "app",
      _argv[
        "a"]);
  }
  if ( "target-app" in _argv ) {
    _set(
      "target",
      "app",
      _argv[
        "target-app"]);
  }
  if ( _argv[
         "A"] ||
       _argv[
         "networks-all"] ) {
    _set(
      "networks",
      "all",
      "y");
  }
  if ( _argv[
         "u"] ||
       _argv[
         "user-defined"] ) {
    _set(
      "user",
      "defined",
      "y");
  }
  if ( "f" in _argv ) {
    _set(
      "configuration",
      "format",
      _argv[
        "f"]);
  }
  if ( "configuration-format" in _argv ) {
    _set(
      "configuration",
      "format",
      _argv[
        "configuration-format"]);
  }
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"] ) {
    _global[
      "quiet"] =
      "n";
  }
}

function
  _url_parse() {
  let
    _method,
    _network;
  _set(
    "runtime",
    "environment",
    "browser");
  _set(
    "target",
    "networks",
    _argv_url_get(
      "network"));
  _set(
    "network",
    "ids",
    _argv_url_get(
      "network_id"));
  _set(
    "networks",
    "all",
    _argv_url_get(
      "networks_all")[
        0]);
  _set(
    "target",
    "app",
    _argv_url_get(
      "target_app")[
        0]);
  _set(
    "target",
    "contract",
    _argv_url_get(
      "target_contract")[
        0]);
  _set(
    "contract",
    "version",
    _argv_url_get(
      "contract_version")[
        0]);
  _set(
    "user",
    "defined",
    _argv_url_get(
      "user_defined")[
        0]);
  _set(
    "configuration",
    "format",
    _argv_url_get(
      "configuration_format")[
        0]);
  _set(
    "deployments",
    "dir",
    _argv_url_get(
      "deployments_dir")[
        0]);
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    _global[
      "quiet"] =
      "n";
  }
}

async function
  _evm_contract_deployment_bytecode_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      await _evm_contract_deployment_bytecode.apply(
        null,
        _app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "object" ) {
    for ( _result of _results ) {
      _echo(
        _result);
    }
  }
  else if ( _results_type == "string" ) {
    _printf(
      _results);
  }
}

async function
  _main() {
  const
    _overrides_set_up =
      await _overrides_set();
  _config_show();
  const
    app_opts = [
      target_networks,
      network_ids,
      networks_all,
      target_app,
      target_contract,
      contract_version,
      user_defined,
      configuration_format,
      deployments_dir,
    ];
  const
    _bytecode =
      await _evm_contract_deployment_bytecode_cmdline(
        app_opts);
  return _bytecode;
}

_global_variables();
if ( await _cmdline_check(
       "evm-contract-deployment-bytecode.js") ||
     await _cmdline_check(
       "evm-contract-deployment-bytecode") ) {
  await _cmdline_parse();
}
else{
  _url_parse();
}
_main();
