#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------
 *     evm-contracts-tools
 *     ----------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it
 *     and/or modify it under the terms of the GNU General
 *     Public License as published by the Free Software
 *     Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will
 *     be useful, but WITHOUT ANY WARRANTY; without even the
 *     implied warranty of MERCHANTABILITY or FITNESS FOR A
 *     PARTICULAR PURPOSE.
 *     See the GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash_module =
    await import(
      "libcrash-js");
const
  _address_check_module =
    await import(
      "./lib/address-check");
/* global
     _address_check */
const
  _address_check =
    _address_check_module._address_check;
const
  _bytecode_creation_get_module =
    await import(
      "./lib/bytecode-creation-get");
/* global
     _bytecode_creation_get */
const
  _bytecode_creation_get =
    _bytecode_creation_get_module._bytecode_creation_get;
const
  _bytecode_runtime_get_module =
    await import(
      "./lib/bytecode-runtime-get");
/* global
     _bytecode_runtime_get */
const
  _bytecode_runtime_get =
    _bytecode_runtime_get_module._bytecode_runtime_get;

const
  _contract_get_module =
    await import(
      "./lib/contract-get");
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get;
const
  _deployer_get_module =
    await import(
      "./lib/deployer-get");
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;
const
  _deployer_verify_module =
    await import(
      "./lib/deployer-verify");
/* global
     _deployer_verify */
const
  _deployer_verify =
    _deployer_verify_module._deployer_verify;
const
  _evm_contract_call_dynamic_module =
    await import(
      "./lib/evm-contract-call-dynamic");
/* global
     _contract_call_dynamic */
const
  _contract_call_dynamic =
    _evm_contract_call_dynamic_module._contract_call_dynamic;
/* global
     _contract_run */
const
  _contract_run =
    _evm_contract_call_dynamic_module._contract_run;
const
  _evm_contract_call_static_module =
    await import(
      "./lib/evm-contract-call-static");
/* global
     _contract_call_static */
const
  _contract_call_static =
    _evm_contract_call_static_module._contract_call_static;

export {
  _app_check,
  _address_check,
  _bytecode_creation_get,
  _bytecode_runtime_get,
  _config_file_path_check,
  _configuration_format_auto_detect,
  _configuration_format_check,
  _configuration_format_get,
  _contract_abi_auto_detect,
  _contract_abi_check,
  _contract_address_auto_detect,
  _contract_address_check,
  _contract_bytecode_check,
  _contract_bytecode_auto_detect,
  _contract_call_dynamic,
  _contract_call_static,
  _contract_compiler_output_auto_detect,
  _contract_compiler_output_check,
  _contract_get,
  _contract_run,
  _contract_version_auto_detect,
  _contract_version_check,
  _default_artifact_path_get,
  _deployer_get,
  _deployer_verify,
  _deployments_dir_auto_detect,
  _deployments_dir_check,
  _network_check,
  _networks_all_auto_detect,
  _target_app_auto_detect,
  _target_app_check,
  _target_contract_auto_detect,
  _target_contract_check,
  _user_defined_check,
  _user_deployments_check,
  _user_level_check,
  _version_check
};

// module.exports = {

//   _address_check:
//     _address_check,
//   _app_check:
//     _app_check,
//   _bytecode_creation_get:
//     _bytecode_creation_get,
//   _bytecode_runtime_get:
//     _bytecode_runtime_get,
//   _config_file_path_check:
//     _config_file_path_check,
//   _configuration_format_auto_detect:
//     _configuration_format_auto_detect,
//   _configuration_format_check:
//     _configuration_format_check,
//   _configuration_format_get:
//     _configuration_format_get,
//   _contract_abi_auto_detect:
//     _contract_abi_auto_detect,
//   _contract_abi_check:
//     _contract_abi_check,
//   _contract_address_auto_detect:
//     _contract_address_auto_detect,
//   _contract_address_check:
//     _contract_address_check,
//   _contract_bytecode_auto_detect:
//     _contract_bytecode_auto_detect,
//   _contract_bytecode_check:
//     _contract_bytecode_check,
//   _contract_call_dynamic:
//     _contract_call_dynamic,
//   _contract_call_static:
//     _contract_call_static,
//   _contract_compiler_output_auto_detect:
//     _contract_compiler_output_auto_detect,
//   _contract_compiler_output_check:
//     _contract_compiler_output_check,
//   _contract_get:
//     _contract_get,
//   _contract_run:
//     _contract_run,
//   _contract_version_auto_detect:
//     _contract_version_auto_detect,
//   _contract_version_check:
//     _contract_version_check,
//   _default_artifact_path_get:
//     _default_artifact_path_get,
//   _deployer_get:
//     _deployer_get,
//   _deployer_verify:
//     _deployer_verify,
//   _deployments_dir_auto_detect:
//     _deployments_dir_auto_detect,
//   _deployments_dir_check:
//     _deployments_dir_check,
//   _network_check:
//     _network_check,
//   _networks_all_auto_detect:
//     _networks_all_auto_detect,
//   _target_app_auto_detect:
//     _target_app_auto_detect,
//   _target_app_check:
//     _target_app_check,
//   _target_contract_auto_detect:
//     _target_contract_auto_detect,
//   _target_contract_check:
//     _target_contract_check,
//   _user_defined_check:
//     _user_defined_check,
//   _user_deployments_check:
//     _user_deployments_check,
//   _user_level_check:
//     _user_level_check,
//   _version_check:
//     _version_check,
// };
