#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contract-deployment-dir.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet:
       writable */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _libevm_contract_deployments_dir_module =
    await import(
      "./libevm-contract-deployments-dir");
/* global
     _evm_contract_deployments_dir */
const
  _evm_contract_deployments_dir =
    _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "evm-contract-deployments-dir.js");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       runtime_environment:
         writable */
  _set(
    "runtime",
    "environment",
    "");
  /* global
       resolve_date:
         writable */
  _set(
    "resolve",
    "date",
    "");
  /* global
       target_app:
         writable */
  _set(
    "target",
    "app",
    "");
  /* global
       user_level:
         writable */
  _set(
    "user",
    "level",
    "");
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
  /* global
       verbose:
         writable */
  _global[
    "verbose"] =
    "";
}

async function 
  _overrides_set(
    _help_display) {
  _override_set(
    "resolve",
    "date",
    _get_date_human());
  _override_set(
    "user",
    "level",
    "n");
}

function
  _config_show() {
  let
    _line;
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _text = [
      `${_app_name} configuration:`,
      `             Resolve date:   ${resolve_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `       Target application:   ${target_app}`,
      `               User level:   ${user_level}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _text = [
      "",
      "Returns default deployments directory for an application",
      "",
      "Usage:",
      "",
      `  ${_app_name}`,
      "    [options]",
      "    <target-app>",
      "",
      "  options:",
      "",
      "     -u --user-level                 Returns user-level location",
      "                                     for an application deployments",
      `                                     Default: '${user_level}`,
      "",
      "     -h --help                       This message.",
      "     -v --verbose                    Enable verbose output.",
      ""
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "u",
        "user-level",
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  const
    _global =
      _global_get();
  _global[
    "quiet"] = 
    "y";
  _set(
    "runtime",
    "environment",
    "node");
  if ( _argv[
         "h"] ) {
    _help_display =
      true;
  }
  if ( _argv[
         "help"] ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    await _overrides_set(
      _help_display);
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Target application " +
      "argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  _set(
    "target",
    "app",
    _argv[
      "_"][
        0]);
  if ( "u" in _argv ) {
    _set(
      "user",
      "level",
      _argv[
        "u"]);
  }
  if ( "user_level" in _argv ) {
    _set(
      "user",
      "level",
      _argv[
        "user_level"]);
  }
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"] ) {
    _global[
      "quiet"] =
      "n";
  }
}

function
  _url_parse() {
  let
    _method,
    _network;
  _set(
    "runtime",
    "environment",
    "browser");
  _set(
    "user",
    "level",
    _argv_url_get(
      "user_level")[
        0]);
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    _global[
      "quiet"] =
      "n";
  }
}

async function
  _evm_contract_deployments_dir_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      await _evm_contract_deployments_dir.apply(
        null,
        app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "object" ) {
    for ( _result of _results ) {
      _echo(
        _result);
    }
  }
  else if ( _results_type == "string" ) {
    _printf(
      _results);
  }
}

async function
  _main() {
  const
    _overrides_set_up =
      await _overrides_set();
  _config_show();
  const
    app_opts = [
      target_app,
      user_level
    ];
  const
    _deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        app_opts);
}

_global_variables();
if ( await _cmdline_check(
       "evm-contract-deployments-dir.js") == true ||
     await _cmdline_check(
       "evm-contract-deployments-dir") == true ) {
  await _cmdline_parse();
}
else {
  _url_parse();
}
_main();
