#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contract-call.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet:
       writable */

/* LibEVM global variables */
/* global
     call_auth:
       writable */
/* global
     call_timeout:
       writable */
/* global
     msg_value:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */
/* global
     api_key:
       writable */
/* global
     wallet_path:
       writable */
/* global
     wallet_password:
       writable */
/* global
     wallet_seed:
       writable */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _libevm_module =
    await _require(
      "libevm");
/* global
     _libevm_cmdline_parse */
const
  _libevm_cmdline_parse =
    _libevm_module._libevm_cmdline_parse;
/* global
     _libevm_global_variables */
const
  _libevm_global_variables =
    _libevm_module._libevm_global_variables;
/* global
     _libevm_url_parse */
const
  _libevm_url_parse =
    _libevm_module._libevm_url_parse;
/* global
     _wallet_overrides_set */
const
  _wallet_overrides_set =
    _libevm_module._wallet_overrides_set;
const
  _libevm_contract_call_module =
    await import(
      "./libevm-contract-call");
/* global
     _artifact_local_auto_detect */
const
  _artifact_local_auto_detect =
    _libevm_contract_call_module._artifact_local_auto_detect;
/* global
     _address_check */
const
  _address_check =
    _libevm_contract_call_module._address_check;
/* global
     _default_artifact_path_get */
const
  _default_artifact_path_get =
    _libevm_contract_call_module._default_artifact_path_get;
/* global
     _contract_abi_auto_detect */
const
  _contract_abi_auto_detect =
    _libevm_contract_call_module._contract_abi_auto_detect;
/* global
     _evm_contract_call */
const
  _evm_contract_call =
    _libevm_contract_call_module._evm_contract_call;
/* global
     _call_auth_auto_detect */
const
  _call_auth_auto_detect =
    _libevm_contract_call_module._call_auth_auto_detect;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "evm-contract-call.js");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       runtime_environment:
         writable */
  _set(
    "runtime",
    "environment",
    "");
  /* global
       call_date:
         writable */
  _set(
    "call",
    "date",
    "");
  /* global
       cache_dir:
         writable */
  _set(
    "cache",
    "dir",
    "");
  /* global
       data_dir:
         writable */
  _set(
    "data",
    "dir",
    "");
  /* global
       wallet_name:
         writable */
  _set(
    "wallet",
    "name",
    "");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       rpc_selection:
         writable */
  _set(
    "rpc",
    "selection",
    "");
  /* global
       call_type:
         writable */
  _set(
    "call",
    "type",
    "");
  /* global
       index_retrieve:
         writable */
  _set(
    "index",
    "retrieve",
    "");
  /* global
       target_app:
         writable */
  _set(
    "target",
    "app",
    "");
  /* global
       target_contract:
         writable */
  _set(
    "target",
    "contract",
    "");
  /* global
       contract_address:
         writable */
  _set(
    "contract",
    "address",
    "");
  /* global
       contract_bytecode:
         writable */
  _set(
    "contract",
    "bytecode",
    "");
  /* global
       contract_compiler_output:
         writable */
  _set(
    "contract",
    "compiler_output",
    "");
  /* global
       contract_abi:
         writable */
  _set(
    "contract",
    "abi",
    "");
  /* global
       contract_method:
         writable */
  _set(
    "contract",
    "method",
    "");
  /* global
       method_args:
         writable */
  _set(
    "method",
    "args",
    []);
  /* global
       price_gas:
         writable */
  _set(
    "price",
    "gas",
    "");
  /* global
       measure_unit:
         writable */
  _set(
    "measure",
    "unit",
    "");
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
  /* global
       verbose:
         writable */
  _global[
    "verbose"] =
    "";
}

async function 
  _overrides_set(
    _help_display) {
  _target_app_auto_detect();
  if ( ! _help_display &&
       typeof(_help_display) != "undefined" &&
       _help_display != "" ) {
    const
      _address_valid =
        _address_check(
          contract_address);
    if ( ! _address_valid ) {
      const
        _msg =
          "Contract address " +
          `'${contract_address}' is ` +
          `invalid.`;
      _msg_error(
        _msg,
        1);
    }
  }
  _override_set(
    "call",
    "date",
    _get_date_human());
  _override_set(
    "wallet",
    "name",
    "default");
  _override_set(
    "index",
    "retrieve",
    "n");
  _override_set(
    "retries",
    "max",
    "300");
  _override_set(
    "rpc",
    "selection",
    "kirsh");
  _override_set(
    "call",
    "type",
    "static");
  _call_auth_auto_detect();
  _override_set(
    "call",
    "timeout",
    "300000");
  _override_set(
    "measure",
    "unit",
    "ether");
  _override_set(
    "msg",
    "value",
    "0");
  // _api_key_auto_detect();
  if ( contract_address != "" ) {
    if ( contract_abi == "" ) {
      contract_abi =
        _default_artifact_path_get(
          "abi");
      _artifact_local_auto_detect(
        "bytecode");
      _artifact_local_auto_detect(
        "compiler_output");
      if ( contract_abi == "" ||
           _default_artifact_path_get(
             "abi") == contract_abi ) {
        _contract_abi_auto_detect();
      }
    }
  }
  await _wallet_overrides_set(
    "evm-wallet",
    wallet_name,
    call_auth);
}

function
  _config_show() {
  let
    _line;
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _text = [
      `${_app_name} configuration:`,
      `                Call date:   ${call_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `                Call type:   ${call_type}`,
      `      Call authentication:   ${call_auth}`,
      `    Application options:`,
      `          Cache directory:   ${cache_dir}`,
      `           Data directory:   ${data_dir}`,
      `    Credentials options:`,
      `              Wallet name:   ${wallet_name}`,
      `           Wallet address:   ${api_key}`,
      `              Wallet path:   ${wallet_path}`,
      `          Wallet password:   ${wallet_password}`,
      `              Wallet seed:   ${wallet_seed}`,
      `        Network options:`,
      `           Target network:   ${target_network}`,
      `              Max retries:   ${retries_max}`,
      `             Call timeout:   ${call_timeout}`,
      `                  API key:   ${api_key}`,
      `     RPC selection method:   ${rpc_selection}`,
      `                Gas price:   ${price_gas}`,
      `       Contract options:`,
      `       Target application:   ${target_app}`,
      `          Target contract:   ${target_contract}`,
      `         Contract address:   ${contract_address}`,
      `             Contract ABI:   ${contract_abi}`,
      `        Contract bytecode:   ${contract_bytecode}`,
      `      Retrieve from Index:   ${index_retrieve}`,
      ` Contract compiler output:   ${contract_compiler_output}`,
      `           Call options:`,
      `            Message value:   ${msg_value}`,
      `             Measure unit:   ${measure_unit}`,
      `          Contract method:   ${contract_method}`,
      `         Method arguments:   ${method_args}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _text = [
      "",
      "Runs a smart contract function.",
      "",
      "Usage:",
      "",
      `  ${_app_name}`,
      "    [options]",
      "    <contract-address>",
      "    <contract-method>",
      "    ([method-args])",
      "",
      "  networks:",
      "    all those supported by",
      "    'evm-chains-info' as well",
      "    as directly RPC addresses",
      "",
      "  options:",
      "",
      "     -t --call-type                  It can be 'static' or 'dynamic'.",
      `       <call-type>                   Default: '${call_type}`,
      "",
      "  call options:",
      `     -V --msg-value                  How much '${measure_unit} to attach to the`,
      `       <msg-value>                   transaction.`,
      `                                     Default: '${msg_value}'`,
      "",
      "     -u --measure-unit               Measure unit for the transacion.",
      `       <measure-unit>                It can be 'ether' or 'wei'.`,
      `                                     Default: '${measure_unit}'`,
      "",
      "     -P --price-gas                  I dont remember. It can be 'idontknow'.",
      "       <price-gas>",
      `                                     Default: '${price_gas}'`,
      "",
      "     -r --retries-max                Maximum number of retries before",
      `       <retries-max>                 Declaring the call failed.`,
      `                                     Default: '${retries_max}'`,
      "",
      "     -T --call-timeout               Maximum number of milliseconds before",
      "       <call-timeout>                declaring the call failed.",
      `                                     Default: '${call_timeout}'`,
      "",
      "  contract options:",
      "",
      "     -A --abi                        Contract ABI path.",
      `       <contract-abi>                Default: '${contract_abi}'.`,
      "",
      "     -B --bytecode                   Contract bytecode path.",
      `       <contract-bytecode>           Default: '${contract_bytecode}'.`,
      "",
      "     -C --compiler-output            Contract compiler output path",
      `       <contract-bytecode>           (the hardhat artifact.`,
      `                                     Default: '${contract_compiler_output}'.`,
      "",
      "     -I --index-retrieve             Enables retrieving contract's artifacts",
      `                                     from the EVM Contracts Source Index.`,
      `                                     Default: '${index_retrieve}'.`,
      "",
      "  credentials options:",
      "",
      "     -N --wallet-name                EVM Wallet name.",
      `       <wallet-name>                 Default: '${wallet_name}'.`,
      "",
      "     -w --wallet-path                EVM Wallet path.",
      `       <wallet-path>                 Default: '${wallet_path}'.`,
      "",
      "     -p --wallet-password            EVM Wallet password file.",
      `       <wallet-password>             Default: '${wallet_password}'.`,
      "",
      "     -s --wallet-seed                EVM Wallet seed file.",
      `       <wallet-seed>                 Default: '${wallet_seed}'.`,
      "",
      "     -k --api-key                    Etherscan-like service key file.",
      `       <api-key>                     Default: '${api_key}'.`,
      "",
      "  libEVM options:",
      "",
      "     -K --app                        Target application.",
      `                                     Default: '${target_app}'`,
      "",
      "     -a --auth                       Call authentication.",
      `                                     Default: '${call_auth}'`,
      "",
      "     -n --network                    EVM network name. Accepted",
      "       <network>                     values are all those supported by",
      `                                     'evm-chains-info' and RPC addresses.`,
      `                                     Default: '${target_network}'.`,
      "",
      "     -S --rpc-selection              RPC selection method. It can be",
      "       <rpc-selection>               'kirsh', 'random' or 'all'.",
      `                                     Default: '${rpc_selection}'.`,
      "",
      "  Application options:",
      "",
      "     -W --cache-dir                  Cache directory.",
      `                                     Default: '${cache_dir}'`,
      "",
      "     -D --data-dir                   Data directory.",
      `                                     Default: '${data_dir}'`,
      "     -h --help                       This message.",
      "",
      "     -v --verbose                    Enable verbose output.",
      ""
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "a",
        "auth",
        "h",
        "help",
        "I",
        "index-retrieve",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  const
    _global =
      _global_get();
  _global[
    "quiet"] = 
    "y";
  _set(
    "runtime",
    "environment",
    "node");
  if ( _argv["h"] == true ) {
    _help_display =
      true;
  }
  if ( _argv["help"] == true ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    _global[
      "quiet"] = 
      "n";
    await _overrides_set(
      _help_display);
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Contract address argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  _set(
    "contract",
    "address",
    _argv[
      "_"][
        0]);
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 2 ) {
    _msg =
      "Contract method argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  _set(
    "contract",
    "method",
    _argv[
      "_"][
        0]);
  _set(
    "method",
    "args",
    _argv[
      "_"].slice(
      2,
      _argv[
        "_"].length - 2));
  if ( "t" in _argv ) {
    _set(
      "call",
      "type",
      _argv[
        "t"]);
  }
  if ( "call-type" in _argv ) {
    _set(
      "call",
      "type",
      _argv[
        "call-type"]);
  }
  if ( "T" in _argv ) {
    _set(
      "call",
      "timeout",
      _argv[
        "t"]);
  }
  if ( "call-timeout" in _argv ) {
    _set(
      "call",
      "timeout",
      _argv[
        "call-timeout"]);
  }
  if ( "I" in _argv ) {
    _set(
      "index",
      "retrieve",
      _argv[
        "I"]);
  }
  if ( "index_retrieve" in _argv ) {
    _set(
      "index",
      "retrieve",
      _argv[
        "index-retrieve"]);
  }
  if ( "app" in _argv ) {
    _set(
      "target",
      "app",
      _argv[
        "app"]);
  }
  if ( "K" in _argv ) {
    _set(
      "target",
      "app",
      _argv[
        "K"]);
  }
  if ( "cache-dir" in _argv ) {
    _set(
      "cache",
      "dir",
      _argv[
        "cache-dir"]);
  }
  if ( "W" in _argv ) {
    _set(
      "cache",
      "dir",
      _argv[
        "W"]);
  }
  if ( "data-dir" in _argv ) {
    _set(
      "data",
      "dir",
      _argv[
        "data-dir"]);
  }
  if ( "D" in _argv ) {
    _set(
      "data",
      "dir",
      _argv[
        "D"]);
  }
  if ( "P" in _argv ) {
    _set(
      "price",
      "gas",
      _argv[
        "P"]);
  }
  if ( "price-gas" in _argv ) {
    _set(
      "price",
      "gas",
      _argv[
        "price-gas"]);
  }
  if ( "u" in _argv ) {
    _set(
      "measure",
      "unit",
      _argv[
        "u"]);
  }
  if ( "measure-unit" in _argv ) {
    _set(
      "measure",
      "unit",
      _argv[
        "measure-unit"]);
  }
  if ( "V" in _argv ) {
    _set(
      "msg",
      "value",
      _argv[
        "V"]);
  }
  if ( "msg-value" in _argv ) {
    _set(
      "msg",
      "value",
      _argv[
        "msg-value"]);
  }
  if ( "r" in _argv ) {
    _set(
      "retries",
      "max",
      _argv[
        "r"]);
  }
  if ( "retries-max" in _argv ) {
    _set(
      "retries",
      "max",
      _argv[
        "retries-max"]);
  }
  if ( "S" in _argv ) {
    _set(
      "rpc",
      "selection",
      _argv[
        "S"]);
  }
  if ( "rpc-selection" in _argv ) {
    _set(
      "rpc",
      "selection",
      _argv[
        "rpc-selection"]);
  }
  if ( "A" in _argv ) {
    _set(
      "contract",
      "abi",
      _argv[
        "A"]);
  }
  if ( "abi" in _argv ) {
    _set(
      "contract",
      "abi",
      _argv[
        "abi"]);
  }
  if ( "B" in _argv ) {
    _set(
      "contract",
      "bytecode",
      _argv[
        "B"]);
  }
  if ( "bytecode" in _argv ) {
    _set(
      "contract",
      "bytecode",
      _argv[
        "bytecode"]);
  }
  if ( "C" in _argv ) {
    _set(
      "contract",
      "compiler_output",
      _argv[
        "C"]);
  }
  if ( "compiler-output" in _argv ) {
    _set(
      "contract",
      "compiler_output",
      _argv[
        "compiler-output"]);
  }
  if ( "a" in _argv ) {
    _set(
      "call",
      "auth",
      "y");
  }
  if ( "auth" in _argv ) {
    _set(
      "call",
      "auth",
      "y");
  }
  const
    _target_networks =
      _get(
        "target",
        "networks");
  if ( "n" in _argv ) {
    _target_networks.push(
      _argv[
        "n"]);
  }
  if ( "network" in _argv ) {
    _target_networks.push(
      _argv[
        "network"]);
  }
  _set(
    "target",
    "networks",
    _target_networks);
  _libevm_cmdline_parse(
    _argv);
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"] ) {
    _global[
      "quiet"] =
      "n";
  }
}

function
  _url_parse() {
  let
    _method,
    _network;
  _set(
    "runtime",
    "environment",
    "browser");
  _set(
    "call",
    "type",
    _argv_url_get(
      "call_type")[
        0]);
  _set(
    "call",
    "timeout",
    _argv_url_get(
      "call_timeout")[
        0]);
  _set(
    "index",
    "retrieve",
    _argv_url_get(
      "index_retrieve")[
        0]);
  _set(
    "data",
    "dir",
    _argv_url_get(
      "data_dir")[
        0]);
  _set(
    "cache",
    "dir",
    _argv_url_get(
      "cache_dir")[
        0]);
  _set(
    "price",
    "gas",
    _argv_url_get(
      "price_gas")[
        0]);
  _set(
    "measure",
    "unit",
    _argv_url_get(
      "measure_unit")[
        0]);
  _set(
    "msg",
    "value",
    _argv_url_get(
      "msg_value")[
        0]);
  _set(
    "retries",
    "max",
    _argv_url_get(
      "retries_max")[
        0]);
  _set(
    "rpc",
    "selection",
    _argv_url_get(
      "rpc_selection")[
        0]);
  _set(
    "contract",
    "abi",
    _argv_url_get(
      "abi")[
        0]);
  _set(
    "contract",
    "bytecode",
    _argv_url_get(
      "bytecode")[
        0]);
  _set(
    "contract",
    "compiler_output",
    _argv_url_get(
      "compiler_output")[
        0]);
  _set(
    "rpc",
    "selection",
    _argv_url_get(
      "rpc_selection")[
        0]);
  const
    _target_networks =
      _get(
        "target",
        "networks");
  for ( _network of _argv_url_get(
                     "network") ) {
    _target_networks.push(
      _network);
  }
  _set(
    "target",
    "networks",
    _target_networks);
  const
    _method_args =
     _get(
       "method",
       "args");
  for ( _method of _argv_url_get(
                     "method_args") ) {
    _method_args.push(
      _method);
  }
  _set(
    "method",
    "args",
    _method_args);
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    _argv_url_get(
      "quiet");
  if ( _global[
         "quiet"].length === 0 ) {
    _global[
      "quiet"] =
      "n";
  }
}

async function
  _evm_contract_call_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      await _evm_contract_call.apply(
        null,
        app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "object" ) {
    for ( _result of _results ) {
      _echo(
        _result);
    }
  }
  else if ( _results_type == "string" ) {
    _printf(
      _results);
  }
}

async function
  _main() {
  const
    _overrides_set_up =
      await _overrides_set();
  _config_show();
  app_opts = [
    call_type,
    call_timeout,
    wallet_name,
    wallet_path,
    wallet_password,
    wallet_seed,
    api_key,
    msg_value,
    price_gas,
    measure_unit,
    retries_max,
    target_network,
    rpc_selection,
    contract_address,
    contract_abi,
    contract_bytecode,
    contract_compiler_output,
    contract_method,
    method_args
  ];
  await _evm_contract_call_cmdline(
    app_opts);
}

_global_variables();
_libevm_global_variables();
if ( await _cmdline_check(
       "evm-contract-call.js") ||
     await _cmdline_check(
       "evm-contract-call") ||
     await _cmdline_check(
       "./evm-contract-call") ) {
  await _cmdline_parse();
}
else{
  _url_parse();
  _libevm_url_parse();
}
// _echo(
//   contract_address);
_main();

export {
  _evm_contract_call
};
