#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------
 *     evm-contracts-tools
 *     ----------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it
 *     and/or modify it under the terms of the GNU General
 *     Public License as published by the Free Software
 *     Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will
 *     be useful, but WITHOUT ANY WARRANTY; without even the
 *     implied warranty of MERCHANTABILITY or FITNESS FOR A
 *     PARTICULAR PURPOSE.
 *     See the GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash_module =
    await import(
      "libcrash-js");
const
  _address_check_module =
    await import(
      "./lib/address-check");
/* global
     _address_check */
const
  _address_check =
    _address_check_module._address_check;
const
  _bytecode_creation_get_module =
    await import(
      "./lib/bytecode-creation-get");
/* global
     _bytecode_creation_get */
const
  _bytecode_creation_get =
    _bytecode_creation_get_module._bytecode_creation_get;
const
  _bytecode_runtime_get_module =
    await import(
      "./lib/bytecode-runtime-get");
/* global
     _bytecode_runtime_get */
const
  _bytecode_runtime_get =
    _bytecode_runtime_get_module._bytecode_runtime_get;

const
  _contract_get_module =
    await import(
      "./lib/contract-get");
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get;
const
  _deployer_get_module =
    await import(
      "./lib/deployer-get");
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;
const
  _deployer_verify_module =
    await import(
      "./lib/deployer-verify");
/* global
     _deployer_verify */
const
  _deployer_verify =
    _deployer_verify_module._deployer_verify;
const
  _evm_contract_call_dynamic_module =
    await import(
      "./lib/evm-contract-call-dynamic");
/* global
     _contract_call_dynamic */
const
  _contract_call_dynamic =
    _evm_contract_call_dynamic_module._contract_call_dynamic;
/* global
     _contract_run */
const
  _contract_run =
    _evm_contract_call_dynamic_module._contract_run;
const
  _evm_contract_call_static_module =
    await import(
      "./lib/evm-contract-call-static");
/* global
     _contract_call_static */
const
  _contract_call_static =
    _evm_contract_call_static_module._contract_call_static;

const
  _libevm_contract_call_module =
    await import(
      "./lib/evm-contract-call");
/* global
     _app_lookup_contract */
const
  _app_lookup_contract =
    _libevm_contract_call_module._app_lookup_contract;
/* global
     _artifact_local_auto_detect */
const
  _artifact_local_auto_detect =
    _libevm_contract_call_module._artifact_local_auto_detect;
/* global
     _artifact_type_check */
const
  _artifact_type_check =
    _libevm_contract_call_module._artifact_type_check;
/* global
     _cache_dir_auto_detect */
const
  _cache_dir_auto_detect =
    _libevm_contract_call_module._cache_dir_auto_detect;
/* global
     _call_auth_auto_detect */
const
  _call_auth_auto_detect =
    _libevm_contract_call_module._call_auth_auto_detect;
/* global
     _call_auth_get */
const
  _call_auth_get =
    _libevm_contract_call_module._call_auth_get;
/* global
     _call_type_check */
const
  _call_type_check =
    _libevm_contract_call_module._call_type_check;
/* global
     _contract_artifacts_retrieve */
const
  _contract_artifacts_retrieve =
    _libevm_contract_call_module._contract_artifacts_retrieve;
/* global
     _contract_lookup_address */
const
  _contract_lookup_address =
    _libevm_contract_call_module._contract_lookup_address;
/* global
     _contracts_init */
const
  _contracts_init =
    _libevm_contract_call_module._contracts_init;
/* global
     _data_dir_auto_detect */
const
  _data_dir_auto_detect =
    _libevm_contract_call_module._data_dir_auto_detect;
/* global
     _evm_contract_call */
const
  _evm_contract_call =
    _libevm_contract_call_module._evm_contract_call;
/* global
     _help_display_check */
const
  _help_display_check =
    _libevm_contract_call_module._help_display_check;
/* global
     _libevm_contract_call_target_app_auto_detect */
const
  _libevm_contract_call_target_app_auto_detect =
    _libevm_contract_call_module._target_app_auto_detect;
/* global
     _libevm_contract_call_target_networks_auto_detect */
const
  _libevm_contract_call_target_networks_auto_detect =
    _libevm_contract_call_module._target_networks_auto_detect;
/* global
     _libevm_contract_call_target_networks_check */
const
  _libevm_contract_call_target_networks_check =
    _libevm_contract_call_module._target_networks_check;
/* global
     _methods_init */
const
  _methods_init =
    _libevm_contract_call_module._methods_init;
/* global
     _target_app_get */
const
  _target_app_get =
    _libevm_contract_call_module._target_app_get;
/* global
     _target_networks_get */
const
  _target_networks_get =
    _libevm_contract_call_module._target_networks_get;
const
  _libevm_contract_deployment_module =
    await import(
      "./lib/evm-contract-deployment");
/* global
     _app_check */
const
  _app_check =
    _libevm_contract_deployment_module._app_check;
/* global
     _config_file_path_check */
const
  _config_file_path_check =
    _libevm_contract_deployment_module._config_file_path_check;
/* global
     _configuration_format_auto_detect */
const
  _configuration_format_auto_detect =
    _libevm_contract_deployment_module._configuration_format_auto_detect;
/* global
     _configuration_format_check */
const
  _configuration_format_check =
    _libevm_contract_deployment_module._configuration_format_check;
/* global
     _configuration_format_get */
const
  _configuration_format_get =
    _libevm_contract_deployment_module._configuration_format_get;
/* global
     _contract_abi_auto_detect */
const
  _contract_abi_auto_detect =
    _libevm_contract_deployment_module._contract_abi_auto_detect;
/* global
     _contract_abi_check */
const
  _contract_abi_check =
    _libevm_contract_deployment_module._contract_abi_check;
/* global
     _contract_address_auto_detect */
const
  _contract_address_auto_detect =
    _libevm_contract_deployment_module._contract_address_auto_detect;
/* global
     _contract_address_check */
const
  _contract_address_check =
    _libevm_contract_deployment_module._contract_address_check;
/* global
     _contract_bytecode_auto_detect */
const
  _contract_bytecode_auto_detect =
    _libevm_contract_deployment_module._contract_bytecode_auto_detect;
/* global
     _contract_bytecode_check */
const
  _contract_bytecode_check =
    _libevm_contract_deployment_module._contract_bytecode_check;
/* global
     _contract_compiler_output_auto_detect */
const
  _contract_compiler_output_auto_detect =
    _libevm_contract_deployment_module._contract_compiler_output_auto_detect;
/* global
     _contract_compiler_output_check */
const
  _contract_compiler_output_check =
    _libevm_contract_deployment_module._contract_compiler_output_check;
/* global
     _contract_version_auto_detect */
const
  _contract_version_auto_detect =
    _libevm_contract_deployment_module._contract_version_auto_detect;
/* global
     _contract_version_check */
const
  _contract_version_check =
    _libevm_contract_deployment_module._contract_version_check;
/* global
     _default_artifact_path_get */
const
  _default_artifact_path_get =
    _libevm_contract_deployment_module._default_artifact_path_get;
/* global
     _deployments_dir_auto_detect */
const
  _deployments_dir_auto_detect =
    _libevm_contract_deployment_module._deployments_dir_auto_detect;
/* global
     _deployments_dir_check */
const
  _deployments_dir_check =
    _libevm_contract_deployment_module._deployments_dir_check;
/* global
     _network_check */
const
  _network_check =
    _libevm_contract_deployment_module._network_check;
/* global
     _networks_all_auto_detect */
const
  _networks_all_auto_detect =
    _libevm_contract_deployment_module._networks_all_auto_detect;
/* global
     _target_app_auto_detect */
const
  _target_app_auto_detect =
    _libevm_contract_deployment_module._target_app_auto_detect;
/* global
     _target_app_check */
const
  _target_app_check =
    _libevm_contract_deployment_module._target_app_check;
/* global
     _target_contract_auto_detect */
const
  _target_contract_auto_detect =
    _libevm_contract_deployment_module._target_contract_auto_detect;
/* global
     _target_contract_check */
const
  _target_contract_check =
    _libevm_contract_deployment_module._target_contract_check;
/* global
     _target_networks_auto_detect */
const
  _target_networks_auto_detect =
    _libevm_contract_deployment_module._target_networks_auto_detect;
/* global
     _target_networks_check */
const
  _target_networks_check =
    _libevm_contract_deployment_module._target_networks_check;
/* global
     _user_deployments_check */
const
  _user_deployments_check =
    _libevm_contract_deployment_module._user_deployments_check;
/* global
     _user_defined_check */
const
  _user_defined_check =
    _libevm_contract_deployment_module._user_defined_check;
/* global
     _user_level_check */
const
  _user_level_check =
    _libevm_contract_deployment_module._user_level_check;
/* global
     _version_check */
const
  _version_check =
    _libevm_contract_deployment_module._version_check;
const
  _libevm_contract_deployment_abi_module =
    await import(
      "./libevm-contract-deployment-abi");
/* global
     _contract_abi_get */
const
  _contract_abi_get =
    _libevm_contract_deployment_abi_module._contract_abi_get;
/* global
     _evm_contract_deployment_abi */
const
  _evm_contract_deployment_abi =
    _libevm_contract_deployment_abi_module._evm_contract_deployment_abi;
const
  _libevm_contract_deployment_address_module =
    await import(
      "./libevm-contract-deployment-address");
/* global
     _contract_address_get */
const
  _contract_address_get =
    _libevm_contract_deployment_address_module._contract_address_get;
/* global
     _evm_contract_deployment_address */
const
  _evm_contract_deployment_address =
    _libevm_contract_deployment_address_module._evm_contract_deployment_address;
const
  _libevm_contract_deployment_bytecode_module =
    await import(
      "./libevm-contract-deployment-bytecode");
/* global
     _contract_bytecode_get */
const
  _contract_bytecode_get =
    _libevm_contract_deployment_bytecode_module._contract_bytecode_get;
/* global
     _evm_contract_deployment_bytecode */
const
  _evm_contract_deployment_contract_bytecode =
    _libevm_contract_deployment_bytecode_module._evm_contract_deployment_bytecode;
const
  _libevm_contract_deployment_compiler_output_module =
    await import(
      "./libevm-contract-deployment-compiler-output");
/* global
     _contract_compiler_output_get */
const
  _contract_compiler_output_get =
    _libevm_contract_deployment_compiler_output_module._contract_compiler_output_get;
/* global
     _evm_contract_deployment_compiler_output */
const
  _evm_contract_deployment_contract_compiler_output =
    _libevm_contract_deployment_compiler_output_module._evm_contract_deployment_compiler_output;
const
  _libevm_contract_deployment_networks_module =
    await import(
      "./libevm-contract-deployment-networks");
/* global
     _evm_contract_deployment_networks */
const
  _evm_contract_deployment_networks =
    _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;
/* global _networks_find */
const
  _networks_find =
    _libevm_contract_deployment_networks_module._networks_find;
const
  _libevm_contract_deployment_versions_module =
    await import(
      "./libevm-contract-deployment-versions");
/* global
     _evm_contract_deployment_versions */
const
  _evm_contract_deployment_versions =
    _libevm_contract_deployment_versions_module._evm_contract_deployment_versions;
const
  _libevm_contract_deployments_dir_module =
    await import(
      "./libevm-contract-deployments-dir");
/* global
     _default_deployments_dir_get */
const
  _default_deployments_dir_get =
    _libevm_contract_deployments_dir_module._default_deployments_dir_get;
/* global
     _evm_contract_deployments_dir */
const
  _evm_contract_deployments_dir =
    _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;

export {
  _app_check,
  _app_lookup_contract,
  _artifact_local_auto_detect,
  _artifact_type_check,
  _address_check,
  _bytecode_creation_get,
  _bytecode_runtime_get,
  _cache_dir_auto_detect,
  _call_auth_auto_detect,
  _call_auth_get,
  _call_type_check,
  _config_file_path_check,
  _configuration_format_auto_detect,
  _configuration_format_check,
  _configuration_format_get,
  _contract_abi_auto_detect,
  _contract_abi_check,
  _contract_address_auto_detect,
  _contract_address_check,
  _contract_address_get,
  _contract_artifacts_retrieve,
  _contract_bytecode_check,
  _contract_bytecode_auto_detect,
  _contract_bytecode_get,
  _contract_call_dynamic,
  _contract_call_static,
  _contract_compiler_output_auto_detect,
  _contract_compiler_output_check,
  _contract_compiler_output_get,
  _contract_lookup_address,
  _contract_get,
  _contract_run,
  _contract_version_auto_detect,
  _contract_version_check,
  _contracts_init,
  _data_dir_auto_detect,
  _default_artifact_path_get,
  _default_deployments_dir_get,
  _deployer_get,
  _deployer_verify,
  _deployments_dir_auto_detect,
  _deployments_dir_check,
  _evm_contract_call,
  _evm_contract_deployment_abi,
  _evm_contract_deployment_address,
  _evm_contract_deployment_bytecode,
  _evm_contract_deployment_compiler_output,
  _evm_contract_deployment_networks,
  _evm_contract_deployments_dir,
  _help_display_check,
  _libevm_contract_call_target_app_auto_detect,
  _libevm_contract_call_target_networks_auto_detect,
  _libevm_contract_call_target_networks_check,
  _methods_init,
  _network_check,
  _networks_all_auto_detect,
  _networks_find,
  _target_app_auto_detect,
  _target_app_check,
  _target_app_get,
  _target_contract_auto_detect,
  _target_contract_check,
  _target_networks_auto_detect,
  _target_networks_check,
  _target_networks_get,
  _user_defined_check,
  _user_deployments_check,
  _user_level_check,
  _version_check
};

// module.exports = {
//   _address_check:
//     _address_check,
//   _app_check:
//     _app_check,
//   _app_lookup_contract:
//     _app_lookup_contract,
//   _artifact_local_auto_detect:
//     _artifact_local_auto_detect,
//   _artifact_local_auto_detect:
//     _artifact_local_auto_detect,
//   _artifact_type_check:
//     _artifact_type_check,
//   _bytecode_creation_get:
//     _bytecode_creation_get,
//   _bytecode_runtime_get:
//     _bytecode_runtime_get,
//   _cache_dir_auto_detect:
//     _cache_dir_auto_detect,
//   _call_auth_auto_detect:
//     _call_auth_auto_detect,
//   _call_auth_get:
//     _call_auth_get,
//   _call_type_check:
//     _call_type_check,
//   _config_file_path_check:
//     _config_file_path_check,
//   _configuration_format_auto_detect:
//     _configuration_format_auto_detect,
//   _configuration_format_check:
//     _configuration_format_check,
//   _configuration_format_get:
//     _configuration_format_get,
//   _contract_abi_auto_detect:
//     _contract_abi_auto_detect,
//   _contract_abi_check:
//     _contract_abi_check,
//   _contract_address_auto_detect:
//     _contract_address_auto_detect,
//   _contract_address_check:
//     _contract_address_check,
//   _contract_address_get:
//     _contract_address_get,
//   _contract_artifacts_retrieve:
//     _contract_artifacts_retrieve,
//   _contract_bytecode_auto_detect:
//     _contract_bytecode_auto_detect,
//   _contract_bytecode_check:
//     _contract_bytecode_check,
//   _contract_bytecode_get:
//     _contract_bytecode_get,
//   _contract_call_dynamic:
//     _contract_call_dynamic,
//   _contract_call_static:
//     _contract_call_static,
//   _contract_compiler_output_auto_detect:
//     _contract_compiler_output_auto_detect,
//   _contract_compiler_output_check:
//     _contract_compiler_output_check,
//   _contract_compiler_output_get:
//     _contract_compiler_output_get,
//   _contract_lookup_address:
//     _contract_lookup_address,
//   _contract_get:
//     _contract_get,
//   _contract_run:
//     _contract_run,
//   _contract_version_auto_detect:
//     _contract_version_auto_detect,
//   _contract_version_check:
//     _contract_version_check,
//   _contracts_init:
//     _contracts_init,
//   _data_dir_auto_detect:
//     _data_dir_auto_detect,
//   _default_artifact_path_get:
//     _default_artifact_path_get,
//   _deployer_get:
//     _deployer_get,
//   _deployer_verify:
//     _deployer_verify,
//   _deployments_dir_auto_detect:
//     _deployments_dir_auto_detect,
//   _deployments_dir_check:
//     _deployments_dir_check,
//   _evm_contract_call:
//     _evm_contract_call,
//   _evm_contract_deployment_abi:
//     _evm_contract_deployment_abi,
//   _evm_contract_deployment_address:
//     _evm_contract_deployment_address,
//   _evm_contract_deployment_bytecode:
//     _evm_contract_deployment_bytecode,
//   _evm_contract_deployment_compiler_output:
//     _evm_contract_deployment_compiler_output,
//   _evm_contract_deployment_networks:
//     _evm_contract_deployment_networks,
//   _help_display_check:
//     _help_display_check,
//   _libevm_contract_call_target_app_auto_detect:
//     _libevm_contract_call_target_app_auto_detect,
//   _libevm_contract_call_target_networks_auto_detect:
//     _libevm_contract_call_target_networks_auto_detect,
//   _libevm_contract_call_target_networks_check:
//     _libevm_contract_call_target_networks_check,
//   _method_init:
//     _method_init,
//   _network_check:
//     _network_check,
//   _networks_all_auto_detect:
//     _networks_all_auto_detect,
//   _networks_find:
//     _networks_find,
//   _target_app_auto_detect:
//     _target_app_auto_detect,
//   _target_app_check:
//     _target_app_check,
//   _target_app_get:
//     _target_app_get,
//   _target_contract_auto_detect:
//     _target_contract_auto_detect,
//   _target_contract_check:
//     _target_contract_check,
//   _target_networks_auto_detect:
//     _target_networks_auto_detect,
//   _target_networks_check:
//     _target_networks_check,
//   _user_defined_check:
//     _user_defined_check,
//   _user_deployments_check:
//     _user_deployments_check,
//   _user_level_check:
//     _user_level_check,
//   _version_check:
//     _version_check,
// };
