#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contract-deployment-address.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet:
       writable */

const
  _libcrash =
  require(
    "crash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _printf */
const
_printf =
  _libcrash._printf;
/* global
     _process_exit */
const
_process_exit =
  _libcrash._process_exit;
const
  _libevm_contract_deployment_address_module =
  require(
    "./libevm-contract-deployment-address");
/* global
     _evm_contract_deployment_address */
const
  _evm_contract_deployment_address =
    _libevm_contract_deployment_address_module._evm_contract_deployment_address;
/* global
     _contract_version_auto_detect */
const
  _contract_version_auto_detect =
    _libevm_contract_deployment_address_module._contract_version_auto_detect;
/* global
     _deployments_dir_auto_detect */
const
  _deployments_dir_auto_detect =
    _libevm_contract_deployment_address_module._deployments_dir_auto_detect;
/* global
     _networks_all_auto_detect */
const
  _networks_all_auto_detect =
    _libevm_contract_deployment_address_module._networks_all_auto_detect;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "evm-contract-deployments-address.js";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       runtime_environment:
         writable */
  runtime_environment =
    "";
  /* global
       resolve_date:
         writable */
  resolve_date =
    "";
  /* global
       target_networks:
         writable */
  target_networks =
    [];
  /* global
       network_ids:
         writable */
  network_ids =
    [];
  /* global
       networks_all:
         writable */
  networks_all =
    "";
  /* global
       target_app:
         writable */
  target_app =
    "";
  /* global
       target_contract:
         writable */
  target_contract =
    "";
  /* global
       contract_version:
         writable */
  contract_version =
    "";
  /* global
       user_defined:
         writable */
  user_defined =
    "";
  /* global
       configuration_format:
         writable */
  configuration_format =
    "";
  /* global
       deployments_dir:
         writable */
  deployments_dir =
    "";
  quiet =
    "";
  /* global
       verbose:
         writable */
  verbose =
    "";
}

async function 
  _overrides_set(
    _help_display) {
  if ( resolve_date == "" ||
       typeof(
         resolve_date) == "undefined" ) {
    resolve_date =
      _get_date_human();
  }
  if ( typeof(
         configuration_format) == "undefined" ||
       configuration_format == "" ) {
    configuration_format =
      "bash";
  }
  _networks_all_auto_detect();
  if ( typeof(
         user_defined) == "undefined" ||
       user_defined == "" ) {
    user_defined =
      "n";
  }
  await _deployments_dir_auto_detect();
  await _contract_version_auto_detect();
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `             Resolve date:   ${resolve_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `          Target networks:   ${target_networks}`,
      `    Network ID (chain ID):   ${network_ids}`,
      `             All networks:   ${networks_all}`,
      `       Target application:   ${target_app}`,
      `     User-defined address:   ${user_defined}`,
      `         Deployments path:   ${deployments_dir}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "",
      "Returns an EVM network's contract deployment address",
      "",
      "Usage:",
      "",
      `  ${app_name}`,
      "    [options]",
      "    <target-contract>",
      "",
      "  networks:",
      "    All those supported",
      "    by 'evm-chains-info'.",
      "",
      "  options:",
      "",
      "     -n, --network <network>              EVM network name.",
      "     -i, --chain-id <number>              EVM network id (chain ID).",
      "     -a, --target-app <app>               Application whose target",
      "                                          contract is part of.",
      `                                          Default: '${target_app}`,
      "     -A, --networks-all                   Returns address for all",
      "                                          available networks.",
      `                                          Default: '${networks_all}`,
      "     -V, --contract-version <version>     Contract version.",
      `                                          Default: '${contract_version}`,
      "     -u, --user-defined                   Returns contract address for",
      "                                          user-defined file system",
      "                                          deployment instead of the system",
      "                                          one.",
      `                                          Default: '${user_defined}`,
      "     -d, --deployments-dir <dir>          Specify contract deployments",
      "                                          directory path.",
      `                                          Default: '${deployments_dir}`,
      "     -f, --configuration-format <format>  Specify contract deployments",
      "                                          directory path.",
      `                                          Default: '${configuration_format}`,
      "",
      "     -h --help                            This message.",
      "     -v --verbose                         Enable verbose output.",
      ""
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _process_exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "u",
        "user-defined",
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  quiet = 
    "y";
  runtime_environment =
    "node";
  if ( _argv[
         "h"] ) {
    _help_display =
      true;
  }
  if ( _argv[
         "help"] ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    await _overrides_set(
      _help_display);
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "Target contract " +
      "argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  target_contract =
    _argv[
      "_"][
        0];
  if ( "n" in _argv ) {
    target_networks.push(
      _argv[
        "n"]);
  }
  if ( "network" in _argv ) {
    target_networks.push(
      _argv[
        "network"]);
  }
  if ( "a" in _argv ) {
    target_app =
      _argv[
        "a"];
  }
  if ( "target-app" in _argv ) {
    target_app =
      _argv[
        "target-app"];
  }
  if ( _argv[
         "u"] ) {
    user_defined =
      _argv[
        "u"];
  }
  if ( _argv[
         "user-defined"] ) {
    user_defined =
      _argv[
        "user-defined"];
  }
  if ( "f" in _argv ) {
    configuration_format =
      _argv[
        "f"];
  }
  if ( "configuration-format" in _argv ) {
    configuration_format =
      _argv[
        "configuration-format"];
  }
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"] ) {
    quiet =
      "n";
  }
}

function
  _url_parse() {
  let
    _method,
    _network;
  runtime_environment =
    "browser";
  target_networks =
    _argv_url_get(
      "network");
  target_ids =
    _argv_url_get(
      "chain_id");
  networks_all =
    _argv_url_get(
      "networks_all")[
        0];
  target_app =
    _argv_url_get(
      "target_app")[
        0];
  target_contract =
    _argv_url_get(
      "target_contract")[
        0];
  contract_version =
    _argv_url_get(
      "contract_version")[
        0];
  user_defined =
    _argv_url_get(
      "user_defined")[
        0];
  configuration_format =
    _argv_url_get(
      "configuration_format")[
        0];
  deployments_dir =
    _argv_url_get(
      "deployments_dir")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

async function
  _evm_contract_deployment_address_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      await _evm_contract_deployment_address.apply(
        null,
        _app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "object" ) {
    for ( _result of _results ) {
      console.log(
        _result);
    }
  }
  else if ( _results_type == "string" ) {
    _printf(
      _results);
  }
}

async function
  _main() {
  const
    _overrides_set_up =
      await _overrides_set();
  _config_show();
  const
    app_opts = [
      target_networks,
      network_ids,
      networks_all,
      target_app,
      target_contract,
      contract_version,
      user_defined,
      configuration_format,
      deployments_dir,
    ];
  const
    _address =
      await _evm_contract_deployment_address_cmdline(
        app_opts);
}

_global_variables();
if ( _cmdline_check(
       "evm-contract-deployment-address.js") ||
     _cmdline_check(
       "evm-contract-deployment-address") ) {
  _cmdline_parse();
}
else{
  _url_parse();
}
_main();
