#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contract-deployment-networks.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet:
       writable */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _stat */
const
  _stat =
    _libcrash._stat;
const
  _libevm_contract_deployment_networks_module =
    await import(
      "./libevm-contract-deployment-networks");
/* global
     _evm_contract_deployment_networks */
const
  _evm_contract_deployment_networks =
    _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "evm-contract-deployments-networks.js");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       runtime_environment:
         writable */
  _set(
    "runtime",
    "enviroment",
    "");
  /* global
       resolve_date:
         writable */
  _set(
    "resolve",
    "date",
    "");
  /* global
       deployments_dir:
         writable */
  _set(
    "deployments",
    "dir",
    "");
  /* global
       display_all:
         writable */
  _set(
    "display",
    "all",
    "");
  /* global
       display_safest:
         writable */
  _set(
    "display",
    "safest",
    "");
  /* global
       display_cheapest:
         writable */
  _set(
    "display",
    "cheapest",
    "");
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
  /* global
       verbose:
         writable */
  _global[
    "verbose"] =
    "";
}

async function 
  _overrides_set(
    _help_display) {
  if ( resolve_date == "" ||
       typeof(
         resolve_date) == "undefined" ) {
    resolve_date =
      _get_date_human();
  }
  if ( display_all == "" ) {
    display_all =
      "y";
  }
  if ( display_cheapest == "" ) {
    display_cheapest =
      "n";
  }
  if ( display_safest == "" ) {
    display_safest =
      "n";
  }
}

function
  _config_show() {
  let
    _line;
  const
    _app =
      _get(
        "app",
        "name");
  const
    _text = [
      `${_app_name} configuration:`,
      `             Resolve date:   ${resolve_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `              Display all:   ${display_all}`,
      `           Display safest:   ${display_safest}`,
      `         Display cheapest:   ${display_cheapest}`,
      `    Deployments directory:   ${deployments_dir}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _app =
      _get(
        "app",
        "name");
  const
    _text = [
      "",
      "Returns a contract's deployment available networks",
      "",
      "Usage:",
      "",
      `  ${_app_name}`,
      "    [options]",
      "    <deployment-dir>",
      "",
      "  options:",
      "",
      "     -A --display-all                Display all available networks",
      "                                     for the deployment.",
      `                                     Default: '${display_all}`,
      "",
      "     -S --display-safest             Display safest network",
      "                                     for the deployment.",
      `                                     Default: '${display_safest}`,
      "",
      "     -C --display-cheapest           Display cheapest network",
      "                                     for the deployment.",
      `                                     Default: '${display_cheapest}`,
      "",
      "     -h --help                       This message.",
      "     -v --verbose                    Enable verbose output.",
      ""
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "A",
        "display-all",
        "S",
        "display-safest",
        "C",
        "display-cheapest",
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  _global[
    "quiet"] = 
    "y";
  _set(
    "runtime",
    "environment",
    "node");
  if ( _argv[
         "h"] ) {
    _help_display =
      true;
  }
  if ( _argv[
         "help"] ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    quiet =
      "n";
    await _overrides_set(
      _help_display);
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 ) {
    _msg =
      "A deployment directory " +
      "must be specified.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  _set(
    "deployments",
    "dir",
    _argv[
      "_"][
        0]);
  if ( _argv[
         "A"] ) {
    _set(
      "display",
      "all",
      _argv[
        "A"]);
  }
  if ( _argv[
         "display-all"] ) {
    _set(
      "display",
      "all",
      _argv[
        "display-all"]);
  }
  if ( _argv[
         "S"] ) {
    _set(
      "display",
      "safest",
      _argv[
        "S"]);
  }
  if ( _argv[
         "display-safest"] ) {
    _set(
      "display",
      "safest",
      _argv[
        "display-safest"]);
  }
  if ( _argv[
         "C"] ) {
    _set(
      "display",
      "cheapest",
      _argv[
        "C"]);
  }
  if ( _argv[
         "display-cheapest"] ) {
    _set(
      "display",
      "cheapest",
      _argv[
        "display-cheapest"]);
  }
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"] ) {
    _global[
      "quiet"] =
      "n";
  }
}

function
  _url_parse() {
  let
    _method,
    _network;
  _set(
    "runtime",
    "environment",
    "browser");
  _set(
    "display",
    "all",
    _argv_url_get(
      "display_all")[
        0]);
  _set(
    "display",
    "safest",
    _argv_url_get(
      "display_safest")[
        0]);
  _set(
    "display",
    "cheapest",
    _argv_url_get(
      "display_cheapest")[
        0]);
  _set(
    "deployments",
    "dir",
    _argv_url_get(
      "deployments_dir")[
        0]);
  _global[
    'quiet'] =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    _global[
      "quiet"] =
      "n";
  }
}

async function
  _evm_contract_deployment_networks_cmdline(
    _app_opts) {
  let
    _result;
  const
    _results =
      await _evm_contract_deployment_networks.apply(
        null,
        app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "object" ) {
    for ( _result of _results ) {
      _echo(
        _result);
    }
  }
  else if ( _results_type == "string" ) {
    _printf(
      _results);
  }
}

async function
  _main() {
  const
    _overrides_set_up =
      await _overrides_set();
  _config_show();
  const
    app_opts = [
      deployments_dir,
      display_all,
      display_safest,
      display_cheapest
    ];
  const
    _networks =
      await _evm_contract_deployment_networks.apply(
        null,
        app_opts);
}

_global_variables();
if ( await _cmdline_check(
       "evm-contract-deployment-networks.js") == true ||
     await _cmdline_check(
       "evm-contract-deployment-networks") == true ) {
  await _cmdline_parse();
}
else{
  _url_parse();
}
_main();
