#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-contracts-tools
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash_module =
    await import(
      "libcrash-js");
const
  _address_check_module =
    await import(
      "./lib/address-check");
/* global
     _address_check */
const
  _address_check =
    _address_check_module._address_check;
const
  _bytecode_creation_get_module =
    await import(
      "./lib/bytecode-creation-get");
/* global
     _bytecode_creation_get */
const
  _bytecode_creation_get =
    _bytecode_creation_get_module._bytecode_creation_get;
const
  _bytecode_runtime_get_module =
    await import(
      "./lib/bytecode-runtime-get");
/* global
     _bytecode_runtime_get */
const
  _bytecode_runtime_get =
    _bytecode_runtime_get_module._bytecode_runtime_get;

const
  _contract_get_module =
    await import(
      "./lib/contract-get");
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get;
const
  _deployer_get_module =
    await import(
      "./lib/deployer-get");
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;
const
  _deployer_verify_module =
    await import(
      "./lib/deployer-verify");
/* global
     _deployer_verify */
const
  _deployer_verify =
    _deployer_verify_module._deployer_verify;
const
  _evm_contract_call_dynamic_module =
    await import(
      "./lib/evm-contract-call-dynamic");
/* global
     _contract_call_dynamic */
const
  _contract_call_dynamic =
    _evm_contract_call_dynamic_module._contract_call_dynamic;
/* global
     _contract_run */
const
  _contract_run =
    _evm_contract_call_dynamic_module._contract_run;
const
  _evm_contract_call_static_module =
    await import(
      "./lib/evm-contract-call-static");
/* global
     _contract_call_static */
const
  _contract_call_static =
    _evm_contract_call_static_module._contract_call_static;

export {
  _address_check,
  _bytecode_creation_get,
  _bytecode_runtime_get,
  _contract_call_dynamic,
  _contract_call_static,
  _contract_get,
  _contract_run,
  _deployer_get,
  _deployer_verify,
};

// module.exports = {
//   _address_check:
//     _address_check,
//   _bytecode_creation_get:
//     _bytecode_creation_get,
//   _bytecode_runtime_get:
//     _bytecode_runtime_get,
//   _contract_call_dynamic:
//     _contract_call_dynamic,
//   _contract_call_static:
//     _contract_call_static,
//   _contract_get:
//     _contract_get,
//   _contract_run:
//     _contract_run,
//   _deployer_get:
//     _deployer_get,
//   _deployer_verify:
//     _deployer_verify,
// };
