#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployment-address
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _file_exists */
/* eslint-disable-next-line
     no-global-assign */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _lib_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
const
  _path_join =
    _libcrash_module._path_join;
const
  _libevm_contract_deployments_dir_module =
    require(
      "./libevm-contract-deployments-dir");
/* global
     _evm_contract_deployments_dir */
const
  _evm_contract_deployments_dir =
    _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
const
  _libevm_contract_deployment_networks_module =
    require(
      "./libevm-contract-deployment-networks");
/* global
     _evm_contract_deployment_networks */
const
  _evm_contract_deployment_networks =
    _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;
const
  _evm_chains_info_module =
    require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;

function
  _contract_address_get(
    _deployments,
    _contract,
    _network,
    _network_id,
    _version,
    _configuration_format) {
  let
    _config_file_ext,
    _config_path,
    _address,
    _found,
    _msg,
    _net;
  if ( typeof(
         _configuration_format) === "undefined" ||
       _configuration_format == "" ) {
    _configuration_format =
      "bash";
  }
  if ( _configuration_format == "bash" ) {
    _config_file_ext =
      "sh";
  }
  if ( _configuration_format == "json" ) {
    _config_file_ext =
      "json"
  }
  else {
    _msg =
      "Unknown configuration format " +
      `${_configuration_format}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _networks = [
      _network,
      _network_id
    ];
  _found =
    false;
  for ( _net of _networks ) {
    _path_join_args =
    _config_path =
      _path_join( [
        _deployments,
        _contract,
        _net,
        `config.${_config_file_ext}` ]);
    if ( _file_exists(
           _config_path) ) {
      _found =
        true;
      break;
    }
  }
  if ( ! _found ) {
    _msg =
      `No network '${_network}' deployment ` +
      `configuration for contract '${_contract}' ` +
      `found at path '${_deployments}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _config =
      _json_read(
        _config);
  const
    _contract_address =
      _config[
        "contract-address"][
          _version];
  if ( _contract_address == "" ||
       _contract_address == null ) {
    _msg =
      `No '${_contract}' version '${_version}' ` +
      `contract deployment specified for network ` +
      `'${_network}' for directory at path `+
      `'${_deployments}'.`;
    _msg_error(
      _msg,
      1);
  }
  return _contract_address;
}

function
  _network_check(
    _deployments,
    _contract,
    _target_network,
    _target_network_id) {
  let
    _msg,
    _network_id,
    _networks;
  _networks = [
    // I need to write that first apparently
    _evm_contract_deployment_networks
  ];
  _app_check(
    _app);
  if ( typeof(
         _type) == "undefined" ||
       _type == "" ) {
    _type =
      "system";
  }
  let
    _conf_dir;
  if ( _type == "system" ) {
    _conf_dir =
      _lib_get();
  }
  else if ( _type == "user" ) {
    const
      _homedir =
        _homedir_get();
    _conf_dir =
      `${_homedir}/.config`;
  }
  return `${_conf_dir}/${_app}/deployments`;
}

function
  _evm_contract_deployment_address(
    _target_networks,
    _network_ids,
    _networks_all,
    _target_app,
    _contract_version,
    _user_defined,
    _deployments_dir) {
  let
    _args,
    _contract_address,
    _contract_address_get_args,
    _contracts_addresses,
    _network,
    _network_check_args,
    _target_network,
    _target_network_id,
    _user_deployments_dir,
    _system_deployments_dir,
    _msg;
  if ( _user_defined == "n" ) {
    if ( _target_app == "" ) {
      _msg =
        "A target application needs to " +
        "be specified with option '-a' " +
        "if not enabling user-defined " +
        "deployments with '-u' and " +
        "specifying a deployments directory " +
        "path with '-d'.";
      _msg_error(
        _msg,
        1)
    }
    _system_deployments_dir =
      _evm_contract_deployments_dir(
        target_app);
    if ( _deployments_dir != system_deployments_dir ) {
      _msg =
        "To set a custom deployments directory path " +
        "you need to enable the user-defined " +
        "deployments switch with '-u'." +
      _msg_error(
        _msg,
        1)
    }
  }
  else if ( _user_defined == "y" ) {
    if ( _target_app != "" ) {
      _user_deployments_dir =
        _evm_contract_deployments_dir(
	  _target_app,
          _user_defined);
    }
    if ( _deployments_dir != _user_deployments_dir ) {
      _msg =
        "Using custom deployments directory " +
        `path '${_deployments_dir}'.`;
      _msg_info(
        _msg);
    }
    else {
      _user_deployments_check();
    }
  }
  else {
    _msg =
      "The 'user-defined' switch argument must be " +
      "can be 'y' or 'n'."
    _msg_error(
      _msg,
      1);
  }
  if ( _networks_all == "y" ) {
    _target_networks =
      _evm_contract_deployment_networks(
        `${_deployments_dir}/${_target_contract}`,
        _networks_all);
  }
  for ( _network of _target_networks ) {
    _target_network_id =
      "";
    _network_check_args = [
      _deployments_dir,
      _target_contract,
      _network,
      _target_network_id
    ];
    _network_check.apply(
      null,
      _network_check_args);
    _contract_address_get_args.push( [
      _deployments_dir,
      _target_contract,
      _target_network,
      _target_network_id,
      _contract_version
    ] );
  }
  for ( _network of  _network_ids ) {
    _target_network =
      "";
    _network_check_args = [
      _deployments_dir,
      _target_contract,
      _target_network,
      _network
    ];
    _network_check.apply(
      null,
      _network_check_args);
    _contract_address_get_args.push( [
      _deployments_dir,
      _target_contract,
      _target_network,
      _target_network_id,
      _contract_version
    ] );
  }
  for ( _args of _contract_address_args ) {
    _contract_address =
      _contract_address_get.apply(
        null,
        _args);
    _contract_addresses.push(
      _contract_address);
  }
  return _contracts_addresses;
}

function
  _deployments_dir_auto_detect() {
  let
    _deployments;
  _deployments =
    "";
  const
    _app =
      target_app;
  const
    _app_type =
      typeof(
        _app);
  if ( _app_type != "undefined" ) {
    const
      _user_defined =
        user_defined;
    const
      _evm_contract_deployments_dir_args = [
        _app,
        _user_defined
      ];
    _deployments =
      _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  }
  const
    _deployments_dir_type =
      typeof(
        deployments_dir);
  if ( _deployments_dir_type === "undefined" ||
       deployments_dir == "" ) {
    deployments_dir =
      _deployments;
  }
}

function
  _contract_version_auto_detect() {
  let
    _config,
    _contract,
    _deployments,
    _found,
    _net,
    _network,
    _network_id,
    _networks,
    _version,
    _msg;
  const
    _contract =
      target_contract;
  _found =
    false;
  const
    _contract_type =
      typeof(
        _contract);
  if ( _contract != "" &&
       _contract_type != "undefined" ) {
    _deployments =
      deployments_dir;
    if ( 0 < target_networks.length ) {
      _network =
        _target_networks[
          0];
    }
    if ( 0 < network_ids.length ) {
      _network_id =
        _target_networks[
          0];
    }
  }
}

function
  _networks_all_auto_detect() {
  let
    _networks_all;
  _networks_all =
    "n";
  if ( target_networks.length < 1 &&
       network_ids.length < 1 ) {
    _networks_all =
      "y";
  }
  if ( typeof(
         networks_all) === "undefined" ||
       networks_all == "" ) {
    networks_all =
      _networks_all;
  }
}

module.exports = {
  _deployments_dir_auto_detect:
    _deployments_dir_auto_detect,
  _evm_contract_deployment_address:
    _evm_contract_deployment_address,
  _networks_all_auto_detect:
    _networks_all_auto_detect
};
