#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployment-address
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _chmod */
/* eslint-disable-next-line
     no-global-assign */
const
  _chmod =
    _libcrash_module._chmod;
/* global
     _cp */
/* eslint-disable-next-line
     no-global-assign */
const
  _cp =
    _libcrash_module._cp;
/* global
     _file_exists */
/* eslint-disable-next-line
     no-global-assign */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _lib_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _mkdir */
/* eslint-disable-next-line
     no-global-assign */
const
  _mkdir =
    _libcrash_module._mkdir;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
const
  _path_join =
    _libcrash_module._path_join;
const
  _evm_chains_info_module =
    require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;
const
  _libevm_contract_deployments_dir_module =
    require(
      "./libevm-contract-deployments-dir");
/* global
     _evm_contract_deployments_dir */
const
  _evm_contract_deployments_dir =
    _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
const
  _libevm_contract_deployment_networks_module =
    require(
      "./libevm-contract-deployment-networks");
/* global
     _evm_contract_deployment_networks */
const
  _evm_contract_deployment_networks =
    _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;
const
  _libevm_contract_deployment_versions_module =
    require(
      "./libevm-contract-deployment-versions");
/* global
     _evm_contract_deployment_versions */
const
  _evm_contract_deployment_versions =
    _libevm_contract_deployment_versions_module._evm_contract_deployment_versions;

function
  _contract_address_get(
    _deployments,
    _contract,
    _network,
    _network_id,
    _version,
    _configuration_format) {
  let
    _config_file_ext,
    _config_path,
    _address,
    _found,
    _msg,
    _net;
  if ( typeof(
         _configuration_format) === "undefined" ||
       _configuration_format == "" ) {
    _configuration_format =
      "bash";
  }
  if ( _configuration_format == "bash" ) {
    _config_file_ext =
      "sh";
  }
  else if ( _configuration_format == "json" ) {
    _config_file_ext =
      "json"
  }
  else {
    _msg =
      "Unknown configuration format " +
      `${_configuration_format}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _networks = [
      _network,
      _network_id
    ];
  _found =
    false;
  for ( _net of _networks ) {
    _path_join_args =
    _config_path =
      _path_join( [
        _deployments,
        _contract,
        _net,
        `config.${_config_file_ext}` ]);
    if ( _file_exists(
           _config_path) ) {
      _found =
        true;
      break;
    }
  }
  if ( ! _found ) {
    _msg =
      `No network '${_network}' deployment ` +
      `configuration for contract '${_contract}' ` +
      `found at path '${_deployments}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _config =
      _json_read(
        _config);
  const
    _contract_address =
      _config[
        "contract-address"][
          _version];
  if ( _contract_address == "" ||
       _contract_address == null ) {
    _msg =
      `No '${_contract}' version '${_version}' ` +
      `contract deployment specified for network ` +
      `'${_network}' for directory at path `+
      `'${_deployments}'.`;
    _msg_error(
      _msg,
      1);
  }
  return _contract_address;
}

async function
  _network_check(
    _deployments,
    _contract,
    _target_network,
    _target_network_id) {
  let
    _error_flag,
    _msg,
    _network_id;
  _error_flag =
    false;
  _deployments_path =
    _path_join( [
      _deployments,
      _contract ]);
  const
    _evm_contract_deployment_networks_args = [
      _deployments_path,
      "y",                  // Display all
      "n",                  // Display safest
      "n"                   // Display cheapest
    ];
  const
    _networks =
      await _evm_contract_deployment_networks.apply(
        null,
        _evm_contract_deployment_networks_args);
  if ( _target_network_id != "" ) {
    if ( ! _networks.includes(
             _target_network_id) ) {
      _msg =
        "The contract does not result deployed on " +
        `network with id '${_target_network_id}'.`;
      _error_flag =
        true;
    }
  }
  else if ( _target_network != "" ) {
    if ( ! _networks.includes(
             _target_network) ) {
      _msg =
        "The contract does not result deployed on " +
        `network '${_target_network}'.`;
      _error_flag =
        true;
    }
  }
  else {
    _msg =
      "Provide one between a target network name " +
      "or ID.";
    _error_flag =
      true;
  }
  if ( _error_flag ) {
    _msg_error(
      _msg,
      1);
  }
  if ( _target_network_id == "" ) {
    _evm_chains_info_args = [
      "get",             // target command
      "name",            // input type
      "id",              // output type
      "offline",
      [ "node",
        "system" ],      // db types
      "kirsh",           // selection method, first
      "n",               // api keys
      "n",               // query all networks
      _target_network,
      []                 // database paths
    ];
    _network_id =
      await _evm_chains_info.apply(
        null,
        _evm_chains_info_args);
    console.log(_network_id);
  }
  else if ( _target_network == "" ) {
    _evm_chains_info_args = [
      "get",             // target command
      "id"  ,            // input type
      "name",              // output type
      "offline",
      [ "node",
        "system" ],      // db types
      "kirsh",           // selection method, first
      "n",               // api keys
      "n",               // query all networks
      _target_network_id,
      []                 // database paths
    ];
    _target_network =
      await _evm_chains_info(
        _evm_chains_info_args);
  }
  if ( _target_network_id != "" ) {
    if ( _target_network_id != _network_id ) {
      _msg =
        "Requested target network ID " +
        `'${_target_network_id}' does ` +
        `not correspond to '${_target_network}' ` +
        `known ID '${_network_id}'.`;
      _msg_error(
        _msg,
        1);
    }
  }
}

async function
  _user_deployments_init(
    _app,
    _deployments_dir) {
  const
    _user_defined =
      "y";
  const
    _evm_contract_deployments_dir_args = [
      _app,
      _user_defined
    ];
  const
    _system_deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  _chmod(
    _deployments_dir,
    "0700");
  const
    _files =
      await _ls(
        _system_deployments);
  for ( _file of _files ) {
    _cp(
      _file,
      _deployments_dir);
  }
  return true;
}

async function
  _user_deployments_check(
    _app,
    _deployments_dir) {
  if ( ! _file_exists(
           _deployments_dir) ) {
    const
      _user_deployments_init_args = [
        _app,
        _deployments_dir
      ];
    const
      _initialized =
        await _user_deployments_init.apply(
          null,
          _user_deployments_init_args);
  }
}

async function
  _evm_contract_deployment_address(
    _target_networks,
    _network_ids,
    _networks_all,
    _target_app,
    _target_contract,
    _contract_version,
    _user_defined,
    _configuration_format,
    _deployments_dir) {
  let
    _args,
    _contract_address,
    _contracts_addresses,
    _network,
    _network_check_args,
    _target_network,
    _target_network_id,
    _user_deployments_dir,
    _system_deployments_dir,
    _msg;
  const
    _contract_address_get_args =
      [];
  if ( _user_defined == "n" ) {
    if ( _target_app == "" ) {
      _msg =
        "A target application needs to " +
        "be specified with option '-a' " +
        "if not enabling user-defined " +
        "deployments with '-u' and " +
        "specifying a deployments directory " +
        "path with '-d'.";
      _msg_error(
        _msg,
        1)
    }
    _system_deployments_dir =
      await _evm_contract_deployments_dir(
        _target_app,
        _user_defined);
    if ( _deployments_dir != _system_deployments_dir ) {
      _msg =
        "To set a custom deployments directory path " +
        "you need to enable the user-defined " +
        "deployments switch with '-u'." +
      _msg_error(
        _msg,
        1)
    }
  }
  else if ( _user_defined == "y" ) {
    if ( _target_app != "" ) {
      _user_deployments_dir =
        await _evm_contract_deployments_dir(
          _target_app,
          _user_defined);
    }
    if ( _deployments_dir != _user_deployments_dir ) {
      _msg =
        "Using custom deployments directory " +
        `path '${_deployments_dir}'.`;
      _msg_info(
        _msg);
    }
    else {
      _user_deployments_check(
        _target_app,
        _deployments_dir);
    }
  }
  else {
    _msg =
      "The 'user-defined' switch argument " +
      `can be 'y' or 'n', current value '${_user_defined}'.`;
    _msg_error(
      _msg,
      1);
  }
  if ( _networks_all == "y" ) {
    _target_networks =
      await _evm_contract_deployment_networks(
        `${_deployments_dir}/${_target_contract}`,
        _networks_all);
  }
  for ( _network of _target_networks ) {
    _target_network_id =
      "";
    _network_check_args = [
      _deployments_dir,
      _target_contract,
      _network,
      _target_network_id
    ];
    _network_check.apply(
      null,
      _network_check_args);
    _contract_address_get_args.push( [
      _deployments_dir,
      _target_contract,
      _target_network,
      _target_network_id,
      _contract_version
    ] );
  }
  for ( _network of  _network_ids ) {
    _target_network =
      "";
    _network_check_args = [
      _deployments_dir,
      _target_contract,
      _target_network,
      _network
    ];
    _network_check.apply(
      null,
      _network_check_args);
    _contract_address_get_args.push( [
      _deployments_dir,
      _target_contract,
      _target_network,
      _target_network_id,
      _contract_version
    ] );
  }
  for ( _args of _contract_address_get_args ) {
    console.log(
      _args);
    _contract_address =
      _contract_address_get.apply(
        null,
        _args);
    _contract_addresses.push(
      _contract_address);
  }
  return _contracts_addresses;
}

async function
  _deployments_dir_auto_detect() {
  let
    _deployments;
  _deployments =
    "";
  const
    _app =
      target_app;
  const
    _app_type =
      typeof(
        _app);
  if ( _app_type != "undefined" &&
       _app != "" ) {
    const
      _user_defined =
        user_defined;
    const
      _evm_contract_deployments_dir_args = [
        _app,
        _user_defined
      ];
    _deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  }
  const
    _deployments_dir_type =
      typeof(
        deployments_dir);
  if ( _deployments_dir_type === "undefined" ||
       deployments_dir == "" ) {
    deployments_dir =
      _deployments;
  }
}

async function
  _contract_version_auto_detect() {
  let
    _config,
    _config_ext,
    _deployments,
    _found,
    _net,
    _network,
    _network_id,
    _networks,
    _version,
    _msg;
  _networks =
    [];
  const
    _contract =
      target_contract;
  _found =
    false;
  if ( configuration_format == "bash" ) {
    _config_ext =
      "sh";
  }
  else if ( configuration_format == "bash" ) {
    _config_ext =
      "json";
  }
  const
    _contract_type =
      typeof(
        _contract);
  if ( _contract != "" &&
       _contract_type != "undefined" ) {
    const
      _deployments_dir_type =
        typeof(
          deployments_dir);
    if ( _deployments_dir_type != "undefined" &&
         deployments_dir != "" ) {
      _deployments =
        deployments_dir;
      if ( 0 < target_networks.length ) {
        _network =
          target_networks[
            0];
      }
      if ( 0 < network_ids.length ) {
        _network_id =
          _network_ids[
            0];
      }
      const
        _deployments_path =
          _path_join( [
            _deployments,
            _contract ] );
      if ( networks_all == "n" ) {
        _networks.push(
          _network,
          _network_id);
      }
      else if ( networks_all == "y" ) {
        const
          _evm_contract_deployment_networks_args = [
            _deployments_path,
            "y",                  // Display all
            "n",                  // Display safest
            "n"                   // Display cheapest
          ];
        _networks_new =
          await _evm_contract_deployment_networks.apply(
            null,
            _evm_contract_deployment_networks_args);
        _networks =
          _networks.concat(
            _networks_new);
      }
      for ( _net of _networks ) {
        _config =
          _path_join( [
            _deployments_path,
            _net,
            `config.${_config_ext}`
            ]);
        console.log(
          _config);
        if ( _file_exists(
               _config) ) {
          _found =
            true;
          _msg =
            `Found deployment configuration ` +
            `at location '${_config}'.`;
          _msg_info(
            _msg);
          break;
        }
      }
      if ( ! _found ) {
        _msg =
          "No deployment configuration " +
          "file found for network " +
          `'${_network}' with ID ` +
          `'${_network_id}'.`;
        _msg_error(
	  _msg,
          1);
      }
      const
        _evm_contract_deployment_versions_args = [
          _config,
          "y",                  // display highest
          "n",                  // display lowest
          configuration_format
	];
      _version =
        await _evm_contract_deployment_versions.apply(
          null,
          _evm_contract_deployment_versions_args);
      console.log(_version)
    }
    else if ( _deployments_dir_type == "undefined" ||
              deployments_dir == "" ) {
      const
        _msg =
          "If no target application is specified " +
          "then the user-defined deployments " +
          "switch must be enabled with '-u' and " +
          "a deployments directory must be specified " +
          "with '-d'.";
      _msg_error(
        _msg,
        1);
    }
  }
  const
    _contract_version_type =
      typeof(
        contract_version);
  if ( _contract_version_type == "undefined" ||
       contract_version == "" ) {
    contract_version =
      _version;
  }
  return true;
}

function
  _networks_all_auto_detect() {
  let
    _networks_all;
  _networks_all =
    "n";
  if ( target_networks.length < 1 &&
       network_ids.length < 1 ) {
    _networks_all =
      "y";
  }
  if ( typeof(
         networks_all) === "undefined" ||
       networks_all == "" ) {
    networks_all =
      _networks_all;
  }
}

module.exports = {
  _contract_version_auto_detect:
    _contract_version_auto_detect,
  _deployments_dir_auto_detect:
    _deployments_dir_auto_detect,
  _evm_contract_deployment_address:
    _evm_contract_deployment_address,
  _networks_all_auto_detect:
    _networks_all_auto_detect
};
