#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployments-networks
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _dirname */
/* eslint-disable-next-line
     no-global-assign */
const
  _dirname =
    _libcrash_module._dirname;
/* global
     _file_exists */
/* eslint-disable-next-line
     no-global-assign */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _lib_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _ls */
/* eslint-disable-next-line
     no-global-assign */
const
  _ls =
    _libcrash_module._ls;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
const
  _path_join =
    _libcrash_module._path_join;
/* global
     _range */
/* eslint-disable-next-line
     no-global-assign */
const
  _range =
    _libcrash_module._range;
/* global
     _stat */
/* eslint-disable-next-line
     no-global-assign */
const
  _stat =
    _libcrash_module._stat;
const
  _libevm_contract_deployments_dir_module =
    require(
      "./libevm-contract-deployments-dir");
/* global
     _evm_contract_deployments_dir */
const
  _evm_contract_deployments_dir =
    _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
const
  _evm_chains_info_module =
    require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;


function
  _contract_address_get(
    _deployments,
    _contract,
    _network,
    _network_id,
    _version) {
  let
    _config_path,
    _address,
    _found,
    _msg,
    _net;
  const
    _networks = [
      _network,
      _network_id
    ];
  _found =
    false;
  for ( _net of _networks ) {
    _config_path =
      `${_deployments}/${_contract}/${_net}/config.sh`;
    if ( _file_exists(
           _config_path) ) {
      _found =
        true;
      break;
    }
  }
  if ( ! _found ) {
    _msg =
      `No network '${_network}' deployment ` +
      `configuration for '${_contract}' ` +
      `found at path '${_deployments}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _config =
      _json_read(
        _config);
  const
    _contract_address =
      _config[
        "contract-address"][
          _version];
  if ( _contract_address == "" ||
       _contract_address == null ) {
    _msg =
      `No '${_contract}' version '${_version}' ` +
      `contract deployment specified for network ` +
      `'${_network}' for directory at path `+
      `'${_deployments}'.`;
    _msg_error(
      _msg,
      1);
  }
}

function
  _network_check(
    _deployments,
    _contract,
    _target_network,
    _target_network_id) {
  let
    _msg,
    _network_id,
    _networks;
  _networks = [
    // I need to write that first apparently
    _evm_contract_deployment_networks
  ];
  _app_check(
    _app);
  if ( typeof(
         _type) == "undefined" ||
       _type == "" ) {
    _type =
      "system";
  }
  let
    _conf_dir;
  if ( _type == "system" ) {
    _conf_dir =
      _lib_get();
  }
  else if ( _type == "user" ) {
    const
      _homedir =
        _homedir_get();
    _conf_dir =
      `${_homedir}/.config`;
  }
  return `${_conf_dir}/${_app}/deployments`;
}

function
  _networks_find(
    _deployment_dir) {
  let
    _file,
    _file_is_dir,
    _path;
  const
    _networks =
      [];
  const
    _files =
      _ls(
        _deployment_dir);
  for ( _file of _files ) {
    _path =
      `${_deployment_dir}/${_file}`;
    _file_is_dir =
      _is_dir(
        _path);
    if ( ! _file_is_dir ) {
      const
        _msg =
          `there shouldn't be a file into ` +
          `this directory.`;
      _msg_warning(
        _msg)
      _stat(
        _file_info);
    }
    else {
      _networks.push(
        _file);
    }
  }
  return _networks;
}

function
  _evm_contract_deployment_networks(
    _deployment_dir,
    _display_all,
    _display_safest,
    _display_cheapest) {
  let
    _networks;
  console.log(
    _deployment_dir);
  _networks =
    _networks_find(
      _deployment_dir);
  console.log(
    _networks);
  return _networks;
}

module.exports = {
  _evm_contract_deployment_networks:
    _evm_contract_deployment_networks
};
