#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployment-versions
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _file_read */
/* eslint-disable-next-line
     no-global-assign */
const
  _file_read =
    _libcrash_module._file_read;
/* global
     _from_bash_ass_array */
/* eslint-disable-next-line
     no-global-assign */
const
  _from_bash_ass_array =
    _libcrash_module._from_bash_ass_array;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
const
  _msg_error =
    _libcrash_module._msg_error;

function
  _configuration_format_auto_detect() {
  let
    _configuration_format;
  if ( typeof(
         configuration_format) === "undefined" ||
       configuration_format == "" ) {
    _configuration_format =
      "json";
    if ( config_file.endsWith(
           ".sh") ) {
      _configuration_format =
        "bash";
    }
    else if ( config_file.endsWith(
           ".json") ) {
      _configuration_format =
        "json";
    }
    else {
      const
        _msg =
          "Impossible determining " +
          "configuration format from file " +
          "extension, defaulting to 'json'.";
      _msg_info(
        _msg,
        1);
    }
    configuration_format =
      _configuration_format;
  }
}

function
  _evm_contract_deployment_versions(
    _config_file,
    _display_highest,
    _display_lowest,
    _configuration_format) {
  let
    _config,
    _key_name,
    _versions;
  if ( typeof(
         _configuration_format) == "undefined" ||
       _configuration_format == "" ) {
    _configuration_format =
      "json";
  }
  if ( _configuration_format == "json" ) {
    _config =
      _json_read(
        _config_file);
    _key_name =
      "contract-address";
  }
  else if ( _configuration_format == "bash" ) {
    _config =
      _from_bash_ass_array(
        _file_read(
          _config_file));
    _key_name =
      "contract_address";
  }
  else {
    _msg =
      "Unknown configuration format " +
      `'${_configuration_format}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _contract_addresses =
      _config[
        _key_name];
  _versions =
    Object.keys(
      _contract_addresses);
  if ( _display_highest == "y" ) {
    _versions =
      _versions.reverse()[
        0];
  }
  if ( _display_lowest == "y" ) {
    _versions =
      _versions.sort()[
        0];
  }
  return _versions;
}

module.exports = {
  _configuration_format_auto_detect:
    _configuration_format_auto_detect,
  _evm_contract_deployment_versions:
    _evm_contract_deployment_versions,
};
