#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployment-address
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _basename */
const
  _basename =
    _libcrash_module._basename;
/* global
     _chmod */
const
  _chmod =
    _libcrash_module._chmod;
/* global
     _cp */
const
  _cp =
    _libcrash_module._cp;
/* global
     _dir_exists */
const
  _dir_exists =
    _libcrash_module._dir_exists;
/* global
     _echo2 */
const
  _echo2 =
    _libcrash_module._echo2;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash_module._file_read;
/* global
     _from_bash_ass_array */
const
  _from_bash_ass_array =
    _libcrash_module._from_bash_ass_array;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _lib_get */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash_module._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash_module._path_join;
/* global
     _pwd */
const
  _pwd =
    _libcrash_module._pwd;
/* global
     _require */
const
  _require =
    _libcrash_module._require;
const
  _libevm_contract_deployment_module =
    await import(
      "./libevm-contract-deployment");
/* global
     _contract_version_auto_detect */
const
  _contract_version_auto_detect =
    _libevm_contract_deployment_module._contract_version_auto_detect;
/* global
     _deployments_dir_auto_detect */
const
  _deployments_dir_auto_detect =
    _libevm_contract_deployment_module._deployments_dir_auto_detect;
/* global
     _network_check */
const
  _network_check =
    _libevm_contract_deployment_module._network_check;
/* global
     _networks_all_auto_detect */
const
  _networks_all_auto_detect =
    _libevm_contract_deployment_module._networks_all_auto_detect;
/* global
     _target_app_auto_detect */
const
  _target_app_auto_detect =
    _libevm_contract_deployment_module._target_app_auto_detect;
/* global
     _user_deployments_check */
const
  _user_deployments_check =
    _libevm_contract_deployment_module._user_deployments_check;
const
  _libevm_contract_deployment_networks_module =
    await import(
      "./libevm-contract-deployment-networks");
/* global
     _evm_contract_deployment_networks */
const
  _evm_contract_deployment_networks =
    _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;

async function
  _contract_address_get(
    _deployments,
    _contract,
    _network,
    _network_id,
    _version,
    _configuration_format) {
  let
    _config,
    _config_file_ext,
    _config_path,
    _libevm_contract_deployment_versions_module,
    _found,
    _key_name,
    _msg,
    _net;
  _msg =
    "Reading address from " +
    "configuration file.";
  _msg_info(
    _msg);
  const
    _version_type =
      typeof(
        _version);
  const
    _configuration_format_type =
      typeof(
        _configuration_format);
  if ( _version_type === "undefined" ||
       _version == "" ) {
    _msg =
      "No version selected,"
      "retrieving.";
    _msg_info(
      _msg);
    try {
      _libevm_contract_deployment_versions_module =
        await import(
          "./libevm-contract-deployment-versions");
    }
    catch(
      _error) {
      _msg =
        "Error while importing " +
        "'lib-evm-contract-deployment-versions'.";
      _msg_error(
        _msg,
        0);
      throw _error;
    }
    const
      _evm_contract_deployment_versions =
        _libevm_contract_deployment_versions_module._evm_contract_deployment_versions;
    const
      _evm_contract_deployment_versions_args = [
      ];
    try {
    _version =
      await _evm_contract_deployment_versions.apply(
        null,
        _evm_contract_deployment_versions_args);
    }
    catch(
      _error) {
      _msg =
        "Error while running " +
        "'_evm_contract_deployment_versions' with arguments:";
      _msg_error(
        _msg,
        0);
      _echo2(
        _evm_contract_deployment_versions_args);
      throw _error;
    }
  }
  if ( _configuration_format_type === "undefined" ||
       _configuration_format == "" ) {
    _msg =
      "Configuration format not set, " +
      "setting default (bash).";
    _msg_info(
      _msg);
    _configuration_format =
      "bash";
  }
  if ( _configuration_format == "bash" ) {
    _config_file_ext =
      "sh";
  }
  else if ( _configuration_format == "json" ) {
    _config_file_ext =
      "json";
  }
  else {
    _msg =
      "Unknown configuration format " +
      `${_configuration_format}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  const
    _networks = [
      _network,
      _network_id
    ];
  _found =
    false;
  for ( _net of _networks ) {
    _config_path =
      _path_join( [
        _deployments,
        _contract,
        _net,
        `config.${_config_file_ext}` ]);
    if ( _file_exists(
           _config_path) ) {
      _found =
        true;
      break;
    }
  }
  if ( ! _found ) {
    _msg =
      `No network '${_network}' deployment ` +
      `configuration for contract '${_contract}' ` +
      `found at path '${_deployments}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _configuration_format == "json" ) {
    _config =
      _json_read(
        _config_path);
    _key_name =
      "contract-address";
  }
  else if ( _configuration_format == "bash" ) {
    _config =
      _from_bash_ass_array(
        _file_read(
          _config_path));
    _key_name =
      "contract_address";
  }
  else {
    _msg =
      "Unknown configuration format " +
      `'${_configuration_format}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  const
    _contract_address =
      _config[
        _key_name][
          _version];
  if ( _contract_address == "" ||
       _contract_address == null ) {
    _msg =
      `No '${_contract}' version '${_version}' ` +
      `contract deployment specified for network ` +
      `'${_network}' for directory at path `+
      `'${_deployments}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _contract_address;
}

async function
  _evm_contract_deployment_address(
    _target_networks,
    _network_ids,
    _networks_all,
    _target_app,
    _target_contract,
    _contract_version,
    _user_defined,
    _configuration_format,
    _deployments_dir) {
  let
    _args,
    _contract_address,
    _msg,
    _network,
    _network_check_args,
    _target_network,
    _target_network_id,
    _user_deployments_dir,
    _system_deployments_dir;
  const
    _libevm_contract_deployments_dir_module =
      await import(
        "./libevm-contract-deployments-dir");
  const
    _evm_contract_deployments_dir =
      _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
  const
    _contracts_addresses =
      [];
  const
    _contract_address_get_args =
      [];
  const
    _user_defined_type =
      typeof(
        _user_defined);
  const
    _deployments_dir_type =
      typeof(
        _deployments_dir);
  if ( _user_defined_type === "undefined" ||
       _user_defined === "" ) {
    _msg =
      "User defined not specified, setting " +
      "default (n).";
    _msg_info(
      _msg);
    _user_defined =
      "n";
  }
  if ( _deployments_dir_type === "undefined" ||
       _deployments_dir === "" ) {
    try {
      _deployments_dir =
        await _evm_contract_deployments_dir(
          _target_app,
          _user_defined);
    }
    catch(
      _error) {
      _msg =
        "Error while retrieving system deployments " +
        "directory location for auto-detection.";
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  if ( _user_defined == "n" ) {
    if ( _target_app === "" ) {
      _msg =
        "A target application needs to " +
        "be specified with option '-a' " +
        "if not enabling user-defined " +
        "deployments with '-u' and " +
        "specifying a deployments directory " +
        "path with '-d'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    try {
      _system_deployments_dir =
        await _evm_contract_deployments_dir(
          _target_app,
          _user_defined);
    }
    catch(
      _error) {
      _msg =
        "Error while retrieving system deployments " +
        "directory location.";
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
    if ( _deployments_dir != _system_deployments_dir ) {
      _msg =
        "To set a custom deployments directory path " +
        "you need to enable the user-defined " +
        "deployments switch with '-u'." +
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  else if ( _user_defined == "y" ) {
    if ( _target_app != "" ) {
      try {
        _user_deployments_dir =
          await _evm_contract_deployments_dir(
            _target_app,
            _user_defined);
      }
      catch(
        _error) {
        _msg =
          "Error while retrieving user deployments " +
          "directory location.";
        _msg_error(
          _msg,
          0);
        _msg_error(
          _error,
          0);
        throw _error;
      }
    }
    if ( _deployments_dir != _user_deployments_dir ) {
      _msg =
        "Using custom deployments directory " +
        `path '${_deployments_dir}'.`;
      _msg_info(
        _msg);
    }
    else {
      _user_deployments_check(
        _target_app,
        _deployments_dir);
    }
  }
  else {
    _msg =
      "The 'user-defined' switch argument " +
      `can be 'y' or 'n', current value '${_user_defined}'.`;
    _msg_error(
      _msg,
      0);
    const
      _exception = {
        "msg":
          _msg
      };
    throw _exception;
  }
  if ( _networks_all == "y" ) {
    _msg =
      "Selecting all networks.";
    _msg_info(
      _msg);
    try {
      _target_networks =
        await _evm_contract_deployment_networks(
          `${_deployments_dir}/${_target_contract}`,
          _networks_all);
    }
    catch(
      _error) {
      _msg =
        "Error while retrieving networks " +
        `for contract '${_target_contract}'.`;
      _msg_error(
        _msg,
        0);
      _echo2(
        _error);
      throw _error;
    }
  }
  _msg =
    `Getting '${_target_contract}' contract address for ` +
    `libEVM app '${_target_app}' ` +
    `for networks with RPCs '${_target_networks}' ` +
    `and chain ID '${_network_ids}', (user-defined contracts: ` +
    `'${_user_defined}'), by looking for configuration files ` +
    `of type '${_configuration_format}'.`;
  _msg_info(
    _msg);
  for ( _network of _target_networks ) {
    // _msg =
    //   "Info arguments for " +
    //   `network '${_network}'.`;
    // _msg_info(
    //   _msg);
    _target_network_id =
      "";
    _network_check_args = [
      _deployments_dir,
      _target_contract,
      _network,
      _target_network_id
    ];
    await _network_check.apply(
      null,
      _network_check_args);
    _contract_address_get_args.push( [
      _deployments_dir,
      _target_contract,
      _network,
      _target_network_id,
      _contract_version,
      _configuration_format
    ] );
  }
  for ( _network of  _network_ids ) {
    _target_network =
      "";
    _network_check_args = [
      _deployments_dir,
      _target_contract,
      _target_network,
      _network
    ];
    await _network_check.apply(
      null,
      _network_check_args);
    _contract_address_get_args.push( [
      _deployments_dir,
      _target_contract,
      _target_network,
      _network,
      _contract_version,
      _configuration_format
    ] );
  }
  for ( _args of _contract_address_get_args ) {
    try {
      _contract_address =
        await _contract_address_get.apply(
          null,
          _args);
    }
    catch(
      _error) {
      _msg =
        "Error while running " +
        "_contract_address_get " +
        `with parameters:`;
      _msg_error(
        _msg,
        0);
      _echo2(
        _args);
      _echo2(
        _error);
      throw _msg;
    }
    _contracts_addresses.push(
      _contract_address);
  }
  return _contracts_addresses;
}

export {
  _contract_version_auto_detect,
  _deployments_dir_auto_detect,
  _evm_contract_deployment_address,
  _networks_all_auto_detect,
  _target_app_auto_detect
};

// module.exports = {
//   _contract_version_auto_detect:
//     _contract_version_auto_detect,
//   _deployments_dir_auto_detect:
//     _deployments_dir_auto_detect,
//   _evm_contract_deployment_address:
//     _evm_contract_deployment_address,
//   _networks_all_auto_detect:
//     _networks_all_auto_detect,
//   _target_app_auto_detect:
//     _target_app_auto_detect
// };
