#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployment
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _basename */
const
  _basename =
    _libcrash_module._basename;
/* global
     _chmod */
const
  _chmod =
    _libcrash_module._chmod;
/* global
     _cp */
const
  _cp =
    _libcrash_module._cp;
/* global
     _dir_exists */
const
  _dir_exists =
    _libcrash_module._dir_exists;
/* global
     _echo */
const
  _echo =
    _libcrash_module._echo;
/* global
     _echo2 */
const
  _echo2 =
    _libcrash_module._echo2;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash_module._file_read;
/* global
     _from_bash_ass_array */
const
  _from_bash_ass_array =
    _libcrash_module._from_bash_ass_array;
/* global
     _get */
const
  _get =
    _libcrash_module._get;
/* global
     _global_get */
const
  _global_get =
    _libcrash_module._global_get;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash_module._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash_module._path_join;
/* global
     _pwd */
const
  _pwd =
    _libcrash_module._pwd;
/* global
     _require */
const
  _require =
    _libcrash_module._require;
const
  _evm_chains_info_module =
    await _require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;
/* global
     _evm_contract_deployments_dir */
/* global
     _evm_contract_deployment_networks */
/* global
     _evm_contract_deployment_versions */
const
  _evm_contracts_tools_module =
    await import(
      "./evm-contracts-tools");
/* global
     _address_check */
const
  _address_check =
    _evm_contracts_tools_module._address_check;

function
  _configuration_format_check(
    _configuration_format) {
  let
    _msg;
  const
    _configuration_format_type =
      typeof(
        _configuration_format);
  if ( _configuration_format_type === "undefined" ) {
    _msg =
      "Configuration format not set, " +
      "setting default (bash).";
    _msg_info(
      _msg);
    _configuration_format =
      "bash";
  }
  else if ( _configuration_format_type === "string" ) {
    if ( _configuration_format.length < 1 ) {
      _msg =
        "Configuration format not set, " +
        "setting default (bash).";
      _msg_info(
        _msg);
      _configuration_format =
        "bash";
    }
    else {
      _msg =
        "Setting configuration format " +
        `'${_configuration_format}'.`;
    }
  }
  else {
    _msg =
      "Type of variable " +
      "'configuration format' must be string.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _configuration_format !== "bash" &&
       _configuration_format !== "json" ) {
    _msg =
      "Unknown configuration format " +
      `'${_configuration_format}'.`
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _configuration_format;
}

async function
  _contract_abi_get(
    _network,
    _address,
    _api_key,
    _compiler_output,
    _abi,
    _app,
    _contract) {
  let
    _abi_target,
    _msg;
  const
    _abi_type =
      typeof(
        _abi);
  if ( _abi_type === "undefined" ) {
    _abi =
      _get(
        "contract",
        "abi");
    _msg =
      "Variable '_abi' not defined, " +
      "defaulting to global variable " +
      "'contract_abi', which has value " +
      `'${_abi}'.`;
    _msg_info(
      _msg);
  }
  const
    _network_type =
      typeof(
        _network);
  if ( _network_type === "undefined" ) {
    _network =
      _get(
        "target",
        "network");
    _msg =
      "Variable '_network' not defined, " +
      "defaulting to global variable " +
      "'target_network', which has value " +
      `'${_network}'.`;
    _msg_info(
      _msg);
  }
  const
    _api_key_type =
      typeof(
        _api_key);
  if ( _api_key_type == "undefined" ) {
    _api_key =
      _get(
        "api",
        "key");
    _msg =
      "Variable '_api_key' not defined, " +
      "defaulting to global variable " +
      "'api_key', which has value " +
      `'${_api_key}'.`;
    _msg_info(
      _msg);
  }
  const
    _compiler_output_type =
      typeof(
        _compiler_output);
  if ( _compiler_output_type == "undefined" ) {
    _compiler_output =
      _get(
        "contract",
        "compiler_output");
    _msg =
      "Variable '_compiler_output' not defined, " +
      "defaulting to global variable " +
      "'contract_compiler_output', which has value " +
      `'${_compiler_output}'.`;
    _msg_info(
      _msg);
  }
  _app =
    _app_check(
      _app);
  const
    _contract_type =
      typeof(
        _contract);
  if ( _contract_type == "undefined" ) {
    _contract =
      _get(
        "target",
        "contract");
    _msg =
      "Variable '_contract' not defined, " +
      "defaulting to global variable " +
      "'target_contract', which has value " +
      `'${_contract}'.`;
    _msg_info(
      _msg);
  }
  const
    _address_type =
      typeof(
        _address);
  if ( _address_type == "undefined" ) {
    _address =
      _get(
        "contract",
        "address");
    _msg =
      "Variable '_address' not defined, " +
      "defaulting to global variable " +
      "'contract_address', which has value " +
      `'${_address}'.`;
    _msg_info(
      _msg);
  }
  _abi_target =
    _abi;
  if ( typeof(
         _abi_target) === "undefined" ||
       _abi_target === "" ) {
    _abi_target =
      _default_artifact_path_get(
        "abi");
    if ( ! _file_exists(
             _abi_target) ) {
      if ( _app !== "" &&
           _contract !== "" ) {
        _msg =
          `Getting LibEVM app '${_app}' ` +
          `ABI for contract '${_contract}'.`;
        _msg_info(
          _msg);
        const
          _evm_contract_deployment_abi_args = [
            [ _network ] ,
            [ _network ],
            "n",
            _app,
            _contract,
            "",                     // version
            "n",                    // user level
            "json",                 // configuration format
            ""
          ];
        try {
          _abi =
            await _evm_contract_deployment_abi.apply(
              null,
              _evm_contract_deployment_abi_args);
        }
        catch(
          _error) {
          _msg =
            `Error retrieving LibEVM app '${_app}' ` +
            `ABI for contract '${_contract}'.`;
          _msg_error(
            _msg,
            0);
          throw _error;
        }
      }
    }
  }
  const
    _abi_dir =
      _dirname(
        _abi);
  if ( ! _file_exists(
           _abi) &&
       ! _file_exists(
           _compiler_output) ) {
    if ( _file_exists(
           _abi_target) ) {
      _abi =
        _abi_target;
    }
    else {
      _contract_artifacts_retrieve(
        _abi_dir);
    }
  }
  return _abi;
}

async function
  _network_check(
    _deployments_dir,
    _contract,
    _target_network,
    _target_network_id,
    _app,
    _user_defined) {
  let
    _contract_deployments_dir,
    _error_flag,
    _evm_contract_deployment_networks,
    _evm_chains_info_args,
    _msg,
    _network_id,
    _networks;
  _error_flag =
    false;
  _app =
    _app_check(
      _app,
      false);
  _user_defined =
    _user_defined_check(
      _user_defined);
  const
    _deployments_dir_check_args = [
      _deployments_dir,
      _app,
      _user_defined
    ];
  try {
    _deployments_dir =
      await _deployments_dir_check.apply(
        null,
        _deployments_dir_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error checking '_deployments_dir' " +
      "variable in '_network_check' function:";
    _msg_error(
      _msg,
      0);
    throw _error;
  }
  _msg =
    "Network check for deployments " +
    `'${_deployments_dir}', contract '${_contract}', ` +
    `network '${_target_network}' and network with ID ` +
    `'${_target_network_id}'.`;
  _msg_info(
    _msg);
  _evm_contract_deployment_networks =
    _get(
      "_evm_contract_deployment",
      "networks");
  try {
    _evm_contract_deployment_networks =
      await _evm_contract_deployment_networks_check(
        _evm_contract_deployment_networks);
  }
  catch(
    _error) {
    _msg =
      "Error importing '_evm_contract_deployment_networks'.";
    _msg_error(
      _msg,
      0);
    _echo2(
      _error);
    throw _error;
  }
  _contract_deployments_dir =
    _path_join( [
      _deployments_dir,
      _contract ]);
  const
    _evm_contract_deployment_networks_args = [
      _contract_deployments_dir,
      "y",                  // Display all
      "n",                  // Display safest
      "n"                   // Display cheapest
    ];
  try {
    _networks =
      await _evm_contract_deployment_networks.apply(
        null,
        _evm_contract_deployment_networks_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_evm_contract_deployment_networks' " +
      `with parameters:`;
    _msg_error(
      _msg,
      0);
    _echo2(
      _evm_contract_deployment_networks_args);
    _echo2(
      _error);
    throw _error;
  }
  if ( _target_network_id != "" ) {
    if ( ! _networks.includes(
             _target_network_id) ) {
      _msg =
        "The contract does not result deployed on " +
        `network with id '${_target_network_id}'.`;
      _error_flag =
        true;
    }
  }
  else if ( _target_network != "" ) {
    if ( ! _networks.includes(
             _target_network) ) {
      _msg =
        "The contract does not result deployed on " +
        `network '${_target_network}'.`;
      _error_flag =
        true;
    }
  }
  else {
    _msg =
      "Provide one between a target network name " +
      "or ID.";
    _error_flag =
      true;
  }
  if ( _error_flag ) {
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _target_network_id == "" ) {
    _evm_chains_info_args = [
      "get",             // target command
      "name",            // input type
      "id",              // output type
      "offline",
      [ "system",        // db types
        "node" ],
      "kirsh",           // selection method, first
      "n",               // api keys
      "n",               // query all networks
      _target_network,
      []                 // database paths
    ];
    try {
      _network_id =
        await _evm_chains_info.apply(
          null,
          _evm_chains_info_args);
    }
    catch(
      _error) {
      _msg = 
        "Error while running '_evm_chains_info' " +
        `with arguments '${_evm_chains_info_args}'.`;
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  else if ( _target_network == "" ) {
    _network_id =
      _target_network_id;
    _evm_chains_info_args = [
      "get",             // target command
      "id"  ,            // input type
      "name",            // output type
      "offline",
      [ "system",        // db types
        "node" ],
      "kirsh",           // selection method, first
      "n",               // api keys
      "n",               // query all networks
      _target_network_id,
      []                 // database paths
    ];
    try {
      _target_network =
        await _evm_chains_info.apply(
          null,
          _evm_chains_info_args);
    }
    catch(
      _error) {
      _msg = 
        "Error while running '_evm_chains_info' " +
        `with arguments '${_evm_chains_info_args}'.`;
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  if ( _target_network_id != "" ) {
    if ( _target_network_id != _network_id ) {
      _msg =
        "Requested target network ID " +
        `'${_target_network_id}' does ` +
        `not correspond to '${_target_network}' ` +
        `known ID '${_network_id}'.`;
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  _msg =
    "Network check for deployments " +
    `'${_deployments_dir}', contract '${_contract}', ` +
    `network '${_target_network}' and network with ID ` +
    `'${_target_network_id}' completed.`;
  _msg_info(
    _msg);
}

async function
  _user_deployments_init(
    _app,
    _deployments_dir) {
  let
    _evm_contract_deployments_dir;
  const
    _user_defined =
      "y";
  _evm_contract_deployments_dir =
    _get(
      "_evm_contract",
      "deployments_dir");
  try {
    _evm_contract_deployments_dir =
      await _evm_contract_deployments_dir_check(
        _evm_contract_deployments_dir);
  }
  catch(
    _error) {
    _msg =
      "Error getting '_evm_cotract_deployments_dir' " +
      "function.";
    _msg_error(
      _msg,
      0);
    _echo2(
      _error);
    throw _error;
  }
  const
    _evm_contract_deployments_dir_args = [
      _app,
      _user_defined
    ];
  const
    _system_deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  _chmod(
    _deployments_dir,
    "0700");
  const
    _files =
      await _ls(
        _system_deployments);
  for ( _file of _files ) {
    _cp(
      _file,
      _deployments_dir);
  }
  return true;
}

async function
  _user_deployments_check(
    _app,
    _deployments_dir) {
  if ( ! _file_exists(
           _deployments_dir) ) {
    const
      _user_deployments_init_args = [
        _app,
        _deployments_dir
      ];
    const
      _initialized =
        await _user_deployments_init.apply(
          null,
          _user_deployments_init_args);
  }
}

function
  _user_defined_check(
    _user_defined) {
  let
    _msg;
  const
    _user_defined_type =
      typeof(
        _user_defined);
  if ( _user_defined_type === "undefined" ) {
    _msg =
      "Variable '_user_defined' undefined, " +
      "setting default value 'n'.";
    _msg_info(
      _msg);
    _user_defined =
      "n";
  }
  else if ( _user_defined_type === "string" ) {
    if ( _user_defined.length < 1 ) {
      _msg =
        "Variable '_user_defined' not set, " +
        "setting default value 'n'.";
      _msg_info(
        _msg);
      _user_defined =
        "n";
    }
    else if ( _user_defined.length > 1 ||
              ( _user_defined !== "n" &&
                _user_defined !== "y" ) ) {
      _msg =
        "Variable '_user_defined' can have " +
        "value 'y' or 'n'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  else {
    _msg =
      "Variable '_user_defined' must be of type " +
      "string and have value 'y' or 'n'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _user_defined;
}

function
  _user_level_check(
    _user_level) {
  let
    _msg;
  const
    _user_level_type =
      typeof(
        _user_level);
  if ( _user_level_type === "undefined" ) {
    _msg =
      "Variable '_user_level' undefined, " +
      "setting default value 'n'.";
    _msg_info(
      _msg);
    _user_level =
      "n";
  }
  else if ( _user_level_type === "string" ) {
    if ( _user_level.length < 1 ) {
      _msg =
        "Variable '_user_level' not set, " +
        "setting default value 'n'.";
      _msg_info(
        _msg);
      _user_level =
        "n";
    }
    else if ( _user_level.length > 1 ||
              ( _user_level !== "n" &&
                _user_level !== "y" ) ) {
      _msg =
        "Variable '_user_level' can have " +
        "value 'y' or 'n' (current value " +
        `'${_user_level}'.`;
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  else {
    _msg =
      "Variable '_user_level' must be of type " +
      "string and have value 'y' or 'n'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _user_level;
}

async function
  _deployments_dir_check(
    _deployments,
    _app,
    _user_defined) {
  let
    _evm_contract_deployments_dir,
    _msg;
  _evm_contract_deployments_dir =
    _get(
      "_evm_contract",
      "deployments_dir");
  try {
    _evm_contract_deployments_dir =
      await _evm_contract_deployments_dir_check(
        _evm_contract_deployments_dir);
  }
  catch(
    _error) {
    _msg =
      "Error getting '_evm_contract_deployments_dir' " +
      "function.";
    _msg_error(
      _msg,
      0);
    _echo2(
      _error);
    throw _error;
  }
  _app =
    _app_check(
      _app);
  _user_defined =
    _user_defined_check(
      _user_defined);
  const
    _evm_contract_deployments_dir_args = [
      _app,
      _user_defined
    ];
  try {
    _deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_evm_contract_deployments_dir' " +
      "function with arguments:";
    _msg_error(
      _msg,
      0);
    _echo2(
      _evm_contract_deployments_dir_args);
    _echo2(
      _error);
    throw _error;
  }
  return _deployments;
}

async function
  _deployments_dir_auto_detect() {
  let
    _app,
    _deployments_dir,
    _evm_contract_deployments_dir,
    _msg,
    _user_defined;
  _deployments_dir =
    _get(
      "deployments",
      "dir");
  _app =
    _get(
      "target",
      "app");
  _app =
    _app_check(
      _app);
  if ( _app != "" ) {
    _user_defined =
      _get(
        "user",
        "defined");
    _user_defined =
      _user_defined_check(
        _user_defined);
    const
      _deployments_dir_check_args = [
        _deployments_dir,
        _app,
        _user_defined
      ];
    try {
      _deployments_dir =
        await _deployments_dir_check.apply(
          null,
          _deployments_dir_check_args);
    }
    catch(
      _error) {
      _msg =
        "Error checking '_deployments_dir' " +
        "variable."
      _msg_error(
        _msg,
        0);
      _echo2(
        _error);
      throw _error;
    }
  }
  _override_set(
    "deployments",
    "dir",
    _deployments_dir);
}

function
  _app_check(
    _app,
    _local) {
  let
    _undefined_flag,
    _msg;
  const
    _local_type =
      typeof(
        _local);
  if ( _local_type === "undefined" ) {
    _msg =
      "Local not specified, setting default " +
      "value 'false'.";
    _local =
      true;
  }
  else if ( _local_type !== "boolean" ) {
    _msg =
      "Variable '_local' must be a boolean.";
    _msg_error(
      _msg,
      0);
  }
  const
    _app_type =
      typeof(
        _app);
  if ( _app_type == "undefined" ) {
    _msg =
      "No application specified.";
    _undefined_flag =
      true;
  }
  else if ( _app_type == "string" ) {
    if ( _app.length < 1 ) {
      _msg =
        "No application specified.";
      _undefined_flag =
        true;
    }
  }
  else {
    _msg =
      "Application argument must be of " +
      `type string (current type: '${_app_type}').`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _undefined_flag ) {
    if ( _local ) {
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    else {
      _msg =
        "Local option disabled, " +
        "getting '_app' variable from " +
        "global variable 'target_app'.";
      _msg_info(
        _msg);
      const
        _global =
          _global_get();
      const
        _target_app =
          _get(
            "target",
            "app");
      const
        _target_app_type =
          typeof(
            _target_app);
      if ( _target_app_type === "string" ) {
        if ( 0 < _target_app.length ) {
          _msg =
            "Getting '_app' variable value from " +
            "global variable 'target_app'.";
          _msg_info(
            _msg);
          _app =
            _target_app;
        }
        else {
          _msg =
            "Error while auto-detecting '_app' variable " +
            "value, global variable 'target_app' " +
            "also not set.";
          _msg_error(
            _msg,
            0);
          throw _msg;
        }
      }
      else {
        _msg =
          "Global variable 'target_app' has " +
          "the wrong type for the local " +
          `variable '_app' ('${_target_app_variable}')`;
        _msg_error(
          _msg,
          0);
        throw _msg;
      }
    }
  }
  return _app;
}

async function
  _contract_version_auto_detect() {
  let
    _config,
    _config_ext,
    _contract,
    _deployments_dir,
    _evm_contracts_deployment_versions,
    _found,
    _net,
    _network,
    _network_id,
    _networks,
    _version,
    _msg;
  _networks =
    [];
  _contract =
    _get(
      "target",
      "contract");
  _deployments_dir =
    _get(
      "deployments",
      "dir");
  _found =
    false;
  if ( configuration_format == "bash" ) {
    _config_ext =
      "sh";
  }
  else if ( configuration_format == "bash" ) {
    _config_ext =
      "json";
  }
  const
    _contract_type =
      typeof(
        _contract);
  if ( _contract != "" &&
       _contract_type != "undefined" ) {
    const
      _deployments_dir_type =
        typeof(
          _deployments_dir);
    if ( _deployments_dir_type !== "undefined" &&
         deployments_dir !== "" ) {
      _deployments =
        deployments_dir;
      if ( 0 < target_networks.length ) {
        _network =
          target_networks[
            0];
      }
      if ( 0 < network_ids.length ) {
        _network_id =
          _network_ids[
            0];
      }
      const
        _deployments_path =
          _path_join( [
            _deployments,
            _contract ] );
      if ( networks_all == "n" ) {
        _networks.push(
          _network,
          _network_id);
      }
      else if ( networks_all == "y" ) {
        const
          _evm_contract_deployment_networks_args = [
            _deployments_path,
            "y",                  // Display all
            "n",                  // Display safest
            "n"                   // Display cheapest
          ];
        _networks_new =
          await _evm_contract_deployment_networks.apply(
            null,
            _evm_contract_deployment_networks_args);
        _networks =
          _networks.concat(
            _networks_new);
      }
      for ( _net of _networks ) {
        _config =
          _path_join( [
            _deployments_path,
            _net,
            `config.${_config_ext}`
            ]);
        if ( _file_exists(
               _config) ) {
          _found =
            true;
          _msg =
            `Found deployment configuration ` +
            `at location '${_config}'.`;
          _msg_info(
            _msg);
          break;
        }
      }
      if ( ! _found ) {
        _msg =
          "No deployment configuration " +
          "file found for network " +
          `'${_network}' with ID ` +
          `'${_network_id}'.`;
        _msg_error(
          _msg,
          1);
      }
      _evm_contract_deployment_versions =
        _get(
          "_evm_contract_deployment",
          "versions");
      try {
        _evm_contract_deployment_versions =
          await _evm_contract_deployment_versions_check(
            _evm_contract_deployment_versions);
      }
      catch(
        _error) {
        _msg =
          "Error checking '_evm_contract_deployment_versions'.";
        _msg_error(
          _msg,
          0);
        throw _msg;
      }
      const
        _evm_contract_deployment_versions_args = [
          _config,
          "y",                  // display highest
          "n",                  // display lowest
          configuration_format
        ];
      _version =
        await _evm_contract_deployment_versions.apply(
          null,
          _evm_contract_deployment_versions_args);
    }
    else if ( _deployments_dir_type == "undefined" ||
              deployments_dir == "" ) {
      const
        _msg =
          "If no target application is specified " +
          "then the user-defined deployments " +
          "switch must be enabled with '-u' and " +
          "a deployments directory must be specified " +
          "with '-d'.";
      _msg_error(
        _msg,
        1);
    }
  }
  _override_set(
    "contract",
    "version",
    _version);
  return true;
}

function
  _networks_all_auto_detect() {
  let
    _networks_all;
  _networks_all =
    "n";
  if ( target_networks.length < 1 &&
       network_ids.length < 1 ) {
    _networks_all =
      "y";
  }
  _override_set(
    "networks",
    "all",
    _networks_all);
}

async function
  _evm_contract_deployments_dir_check(
    _evm_contract_deployments_dir) {
  let
    _import,
    _msg;
  _import =
    false;
  const
    _evm_contract_deployments_dir_type =
      typeof(
        _evm_contract_deployments_dir);
  if ( _evm_contract_deployments_dir_type === "undefined" ) {
    _msg =
      "Function '_evm_contract_deployments_dir' " +
      "undefined, importing.";
    _import =
      true;
  }
  else if ( _evm_contract_deployments_dir_type === "string" ) {
    if ( _evm_contract_deployments_dir.length < 1 ) {
      _msg =
        "Function '_evm_contract_deployments_dir' " +
        "undefined, importing.";
      _import =
        true;
    }
    else {
      _msg =
        "Function '_evm_contract_deployments_dir' " +
        "is a string.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  if ( _import ) {
    try {
      const
        _libevm_contract_deployments_dir_module =
          await import(
            "./libevm-contract-deployments-dir");
        _evm_contract_deployments_dir =
          _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
    }
    catch(
      _error) {
      _msg =
        "Error importing './libevm-contract-deployments-dir'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  return _evm_contract_deployments_dir;
}

async function
  _evm_contract_deployment_versions_check(
    _evm_contract_deployment_versions) {
  let
    _import,
    _msg;
  _import =
    false;
  const
    _evm_contract_deployment_versions_type =
      typeof(
        _evm_contract_deployment_versions);
  if ( _evm_contract_deployment_versions_type === "undefined" ) {
    _msg =
      "Function '_evm_contract_deployment_versions' " +
      "undefined, importing.";
    _import =
      true;
  }
  else if ( _evm_contract_deployment_versions_type === "string" ) {
    if ( _evm_contract_deployment_versions.length < 1 ) {
      _msg =
        "Function '_evm_contract_deployment_versions' " +
        "undefined, importing.";
      _import =
        true;
    }
    else {
      _msg =
        "Function '_evm_contract_deployment_versions' " +
        "is a string.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  if ( _import ) {
    try {
      const
        _libevm_contract_deployment_versions_module =
          await import(
            "./libevm-contract-deployment-versions");
        _evm_contract_deployment_versions =
          _libevm_contract_deployment_versions_module._evm_contract_deployment_versions;
    }
    catch(
      _error) {
      _msg =
        "Error importing './libevm-contract-deployment-versions'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  return _evm_contract_deployment_versions;
}

async function
  _evm_contract_deployment_networks_check(
    _evm_contract_deployment_networks) {
  let
    _import,
    _msg;
  _import =
    false;
  const
    _evm_contract_deployment_networks_type =
      typeof(
        _evm_contract_deployment_networks);
  if ( _evm_contract_deployment_networks_type === "undefined" ) {
    _msg =
      "Function '_evm_contract_deployment_networks' " +
      "undefined, importing.";
    _import =
      true;
  }
  else if ( _evm_contract_deployment_networks_type === "string" ) {
    if ( _evm_contract_deployment_networks.length < 1 ) {
      _msg =
        "Function '_evm_contract_deployment_networks' " +
        "undefined, importing.";
      _import =
        true;
    }
    else {
      _msg =
        "Function '_evm_contract_deployment_networks' " +
        "is a string.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  if ( _import ) {
    try {
      const
        _libevm_contract_deployment_networks_module =
          await import(
            "./libevm-contract-deployment-networks");
        _evm_contract_deployment_networks =
          _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;
    }
    catch(
      _error) {
      _msg =
        "Error importing './libevm-contract-deployment-networks'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  return _evm_contract_deployment_networks;
}

async function
  _target_app_auto_detect() {
  let
    _app,
    _evm_contract_deployments_dir;
  _app =
    "";
  const
    _dir_current_name =
      _basename(
        _pwd());
  const
    _user_defined =
      _get(
        "user",
        "defined");
  _evm_contract_deployments_dir =
    _get(
      "_evm_contract",
      "deployments_dir");
  _user_defined =
    _user_defined_check(
      _user_defined);
  try {
    _evm_contract_deployments_dir =
      await _evm_contract_deployments_dir_check(
        _evm_contract_deployments_dir);
  }
  catch(
    _error) {
    _msg =
      "Error getting '_evm_cotract_deployments_dir' " +
      "function.";
    _msg_error(
      _msg,
      0);
    _echo2(
      _error);
    throw _error;
  }
  const
    _evm_contract_deployments_dir_args = [
      _dir_current_name,
      _user_defined
    ];
  try {
    const
      _target_dir =
        await _evm_contract_deployments_dir.apply(
          null,
          _evm_contract_deployments_dir_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_evm_contract_deployments_dir' " +
      "with arguments:";
    _echo2(
      _evm_contract_deployments_dir_args);
    _echo2(
      _error);
    throw _error;
  }
  if ( _dir_exists(
         _target_dir) ) {
    _msg =
      "Found existing directory " +
      `'${_target_dir}', setting ` +
      `'${_dir_current_name}' as application name.`;
    _msg_info(
      _msg);
    _app =
      _dir_current_name;
  }
  else {
    _msg =
      `Directory '${_target_dir}' ` +
      "not found, impossible auto-detecting " +
      "application name for given contract.";
    _msg_info(
      _msg);
  }
  _override_set(
    "target",
    "app",
    _app);
}

async function
  _config_file_path_check(
    _config_file_path,
    _app,
    _deployments_dir,
    _contract,
    _network,
    _network_id,
    _configuration_format,
    _user_defined) {
  let
    _config_file_ext,
    _config_file_path_get,
    _msg,
    _net;
  const
    _config_file_path_type =
      typeof(
        _config_file_path);
  _config_file_path_get =
    false;
  if ( _config_file_path_type == "undefined" ) {
    _msg =
      "Configuration file path undefined, " +
      "auto-detecting.";
    _msg_info(
      _msg);
    _config_file_get =
      true;
  }
  else if ( _config_file_path_type == "string" ) {
    if ( _config_file_path.length < 1 ) {
    _msg =
      "Configuration file path not set, " +
      "auto-detecting.";
    _msg_info(
      _msg);
    _config_file_get =
      true;
    }
    else {
      if ( ! _file_exists(
             _config_file_path) ) {
        _msg =
          `File at location '${_config_file_path}' ` +
          `does not exist.`;
        _msg_error(
          _msg,
          0);
        throw _msg;
      }
    }
  }
  else {
    _msg =
      `Unknown type '${_config_file_path_type}' ` +
      `for '_config_file_path' variable (correct ` +
      `type: string).`;
    _msg_error(
      _msg,
      0);
  }
  const
    _global =
      _global_get();
  const
    _quiet =
      _global[
        "quiet"];
  if ( _config_file_get ) {
    const
      _contract_type =
        typeof(
          _contract);
    if ( _contract_type === "undefined" ) {
      _msg =
        "A contract name must be specified a contract name."
    }
    _user_defined =
      await _user_defined_check(
        _user_defined);
    _configuration_format =
      _configuration_format_check(
        _configuration_format);
    if ( _configuration_format == "bash" ) {
      _config_file_ext =
        "sh";
    }
    else if ( _configuration_format == "json" ) {
      _config_file_ext =
        "json";
    }
    else {
      _msg =
        "Unknown configuration format " +
        `${_configuration_format}'.`;
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    const
      _deployments_dir_check_args = [
        _deployments_dir,
        _app,
        _user_defined
      ];
    try {
      _deployments_dir =
        await _deployments_dir_check.apply(
          null,
          _deployments_dir_check_args);
    }
    catch(
      _error) {
      _msg =
        "Error checking '_deployments_dir' " +
        "variable."
      _msg_error(
        _msg,
        0);
      _echo2(
        _error);
      throw _error;
    }
    const
      _networks = [
        _network,
        _network_id
      ];
    _found =
      false;
    for ( _net of _networks ) {
      _config_file_path =
        _path_join( [
          _deployments_dir,
          _contract,
          _net,
          `config.${_config_file_ext}` ]);
      if ( _file_exists(
             _config_file_path) ) {
        _found =
          true;
        break;
      }
    }
  }
  return _config_file_path;
}

function
  _configuration_format_get(
    _config_file) {
  let
    _configuration_format,
    _msg;
  _msg =
    "Getting configuration format " +
    `for configuration file '${_config_file}'.`;
  _msg_info(
    _msg);
  if ( _config_file.endsWith(
         ".sh") ) {
    _configuration_format =
      "bash";
  }
  else if ( _config_file.endsWith(
         ".json") ) {
    _configuration_format =
      "json";
  }
  else {
    _msg =
      "Impossible determining " +
      "configuration format from file " +
      "extension, defaulting to 'json'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _configuration_format;
}

async function
  _configuration_format_auto_detect() {
  let
    _config_file_path,
    _configuration_format,
    _msg;
  _configuration_format =
    _get(
      "configuration",
      "format");
  _config_file_path =
    _get(
      "config",
      "file");
  const
    _app =
      _get(
        "target",
        "app");
  const
    _deployments_dir =
      _get(
        "deployments",
        "dir");
  const
    _target_contract =
      _get(
        "target",
        "contract");
  const
    _target_network =
      _get(
        "target",
        "network");
  const
    _user_defined =
      _get(
        "user",
        "defined");
  const
    _config_file_path_check_args = [
      _config_file_path,
      _app,
      _deployments_dir,
      _contract,
      _target_network,
      _target_network,
      _configuration_format,
      _user_defined
    ];
  try {
    _config_file_path =
      await _config_file_path_check.apply(
        null,
        _config_file_path_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error checking 'config_file' variable.";
    _msg_error(
      _msg,
      0);
    echo2(
      _error);
    throw _error;
  }
  _configuration_format =
    _configuration_format_get(
      _config_file);
  _override_set(
    "configuration",
    "format",
    _configuration_format);
}

async function
  _version_check(
    _version,
    _configuration_format) {
  let
    _msg,
    _version_get;
  _configuration_format = 
    _configuration_format_check(
      _configuration_format);
  const
    _version_type =
      typeof(
        _version);
  _version_get =
    false;
  if ( _version_type === "undefined" ) {
    _msg =
      "Variable 'version' undefined, " +
      "auto-detecting.";
    _version_get =
      true;
  }
  if ( _version_type === "string" ) {
    if ( _version.length < 1 ) {
      _msg =
        "Variable 'version' not specified, " +
        "auto-detecting.";
    _version_get =
      true;
    }
  }
  if ( _version_get ) {
    _evm_contract_deployment_versions =
      _get(
        "_evm_contract_deployment",
        "versions");
    try {
      _evm_contract_deployment_versions =
        await _evm_contract_deployment_versions_check(
          _evm_contract_deployment_versions);
    }
    catch(
      _error) {
      _msg =
        "Error importing '_evm-contract-deployment-versions'.";
      _msg_error(
        _msg,
        0);
      throw _error;
    }
    const
      _evm_contract_deployment_versions_args = [
        _config_file,
        _display_highest,
        _display_lowest,
        _configuration_format
      ];
    try {
      _version =
        await _evm_contract_deployment_versions.apply(
          null,
          _evm_contract_deployment_versions_args);
    }
    catch(
      _error) {
      _msg =
        "Error auto-retrieving version.";
      _msg_error(
        _msg,
        0);
      throw _error;
    }
  }
  return _version;
}

async function
  _contract_address_check(
    _contract_address,
    _deployments_dir,
    _app) {
  let
    _contract,
    _contract_address_get;
  _contract_address_get =
    false;
  const
    _contract_address_type =
      typeof(
        _contract_address);
  if ( _contract_address_type === "undefined" ) {
    _msg =
      "Contract address not set, " +
      "auto-detecting given input data.";
    _msg_info(
      _msg);
    _contract_address_get =
      true;
  }
  else if ( _contract_address_type === "string" ) {
    if ( _contract_address.length < 1 ) {
      _msg =
        "Contract address not set, " +
        "auto-detecting given input data.";
      _msg_info(
        _msg);
      _contract_address_get =
        true;
    }
    else {
      try {
        const
          _address_valid =
            await _address_check(
              _contract_address);
      }
      catch(
        _error) {
        _msg =
          "Error verifying validity of " +
          `address '${_contract_address}'.`;
        _msg_error(
          _msg,
          0);
        throw _msg;
      }
      if ( ! _address_valid ) {
        _msg =
          "Address not valid, getting " +
          "contract address.";
        _contract_address_get =
          true;
        _contract =
          _get(
            "target",
            "contract");
        try {
          _target_contract =
            await _target_contract_check(
              _contract_address);
	}
        catch(
          _error) {
          _msg =
            "Error running '_target_contract_check' " +
            `with parameters:`;
          _msg_error(
            _msg,
            0);
          _echo2(
            _contract_address);
          _echo2(
            _error);
          throw _error;
	}
      }
    }
  }
  else {
    _msg =
      "Invalid type for variable " +
      `'_contract_address' (${_contract_address_type}):`;
    _msg_error(
      _msg,
      0);
    _echo2(
      _contract_address);
    throw _msg;
  }
  if ( _contract_address_get ) {
    _app =
      _app_check(
        _app,
        false);
    const
      _deployments_dir_check_args = [
        _deployments_dir,
        _app,
        _user_defined
      ];
    try {
      _deployments_dir =
        await _deployments_dir_check.apply(
          null,
          _deployments_dir_check_args);
      _msg_info(
        `Got '${_deployments_dir}'`);
    }
    catch(
      _error) {
      _msg =
        "Error checking variable " +
        "'_deployments_dir'.";
      _msg_error(
        _msg,
        0);
      throw _error;
    }
    _msg =
      "Looking for address " +
      "corresponding to contract " +
      `'${_target_contract}' for the ` +
      `'${_app}' ` +
      "libEVM application on network " +
      `'${_target_networks}' at deployments ` +
      `directory '${_deployments_dir}'.`;
    _msg_info(
      _msg);
    _evm_contract_deployment_address_args = [
      _target_networks_set,      // target networks
      _target_networks_set,      // target chain ids
      "n",                       // all networks
      _app,
      _target_contract,
      "",                        // contract version
      "n",                       // user-level
      "",                        // configuration format
      _deployments_dir
    ];
    try {
      _contract_addresses =
        await _evm_contract_deployment_address.apply(
          null,
          _evm_contract_deployment_address_args);
      _contract_address =
        _contract_addresses[
          0];
    }
    catch(
      _error) {
      _msg =
        "Error while looking for contract " +
        "address from local libEVM applications " +
        "deployments directories.";
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  return _contract_address;
}

async function
  _target_contract_check(
    _target_contract,
    _contract_address,
    _target_app,
    _deployments_dir) {
  let
    _msg,
    _target_contract_get;
  const
    _target_contract_type =
      typeof(
        _target_contract); 
  if ( _target_contract_type === "undefined" ) {
    _msg =
      "Target contract undefined, auto-detecting.";
    _msg_info(
      _msg);
    _target_contract_get =
      true;
  }
  else if ( _target_contract_type === "string" ) {
    if ( _target_contract.length < 1 ) {
      _msg =
        "Target contract not set, auto-detecting.";
      _msg_info(
        _msg);
      _target_contract_get =
        true;
    }
  }
  else {
    _msg =
      "Target contract must have type 'string'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _target_contract_get ) {
    try {
      const
        _deployments_dir_check_args = [
          _deployments_dir,
          _target_app,
          _user_defined
        ];
      _deployments_dir =
        await _deployments_dir_check(
         _contract_address,
         _deployments_dir,
	 _target_app);
    }
    catch(
      _error) {
      _msg =
        "Error auto-detecting target contract name.";
    }
    try {
      _contract_address =
        await _contract_address_check(
         _contract_address,
         _deployments_dir,
	 _target_app);
    }
    catch(
      _error) {
      _msg =
        "Error auto-detecting target contract name.";
    }
    const
      _address_valid =
        await _address_check(
          _contract_address);
    if ( ! _address_valid ) {
      _target_contract =
        _contract_address;
    }
  }
  return _target_contract;
}

async function
  _target_contract_auto_detect() {
  let
    _target_contract;
  _target_contract =
    _get(
      "target",
      "contract");
  const
    _target_app =
      _get(
        "target",
        "app");
  const
    _deployments_dir =
      _get(
        "deployments",
        "dir");
  const
    _contract_address =
      _get(
        "contract",
        "address");
  const
    _contract_address_check_args = [
      _contract_address,
      _deployments_dir,
      _target_app
    ];
  try {
    _contract_address =
      await _contract_address_check.apply(
        null,
        _contract_address_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_contract_address_check' " +
      "with arguments:";
    _msg_error(
      _msg,
      0);
    _echo2(
      _contract_address_check_args);
    _echo2(
      _error);
    throw _error;
  }
  const
    _target_contract_check_args = [
      _target_contract,
      _contract_address,
      _target_app,
      _deployments_dir
    ];
  try {
    _target_contract =
      await _target_contract_check.apply(
        null,
        _target_contract_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_target_contract_check' " +
      "with arguments:";
    _msg_error(
      _msg,
      0);
    _echo2(
      _target_contract_check_args);
    _echo2(
      _error);
    throw _error;
  }
  _override_set(
    "target",
    "contract",
    _target_contract);
}

async function
  _contract_abi_auto_detect(
    _app,
    _contract,
    _networks,
    _address,
    _deployments_dir,
    _user_defined) {
  let
    _abi,
    _abi_retrieve,
    _msg;
  const
    _global =
      _global_get();
  const
    _quiet =
      _global[
        "quiet"];
  _app =
    _app_check(
      _app,
      false);
  _user_defined =
    _user_defined_check(
      _user_defined);
  const
    _deployments_dir_check_args = [
      _deployments_dir,
      _app,
      _user_defined
    ];
  try {
    _deployments_dir =
      await _deployments_dir_check.apply(
        null,
        _deployments_dir_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_deployments_dir_check'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  const
    _target_contract_check_args = [
      _contract,
      _address,
      _app,
      _deployments_dir
    ];
  try {
    _contract =
      await _target_contract_check(
        _target_contract_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_target_contract_check' " +
      "with parameters:";
    _echo2(
      _target_contract_check_args);
    _echo2(
      _error);
    throw _error;
  }
  const
    _networks =
      _get(
        "target",
        "networks");
  const
    _contract_address_check_args = [
      _address,
      _deployments_dir,
      _app
    ];
  try {
    _address =
      await _contract_address_check.apply(
        null,
        _contract_address_check_args);
  }
  catch(
    _error) {
    _msg =
      "Error running '_contract_address_check' " +
      "with parameters:";
    _echo2(
      _contract_address_check_args);
    _echo2(
      _error);
    throw _error;
  }
  const
    _api_key =
      _get(
        "api",
        "key");
  const
    _compiler_output =
      _get(
        "contract",
        "compiler_output");
  _abi =
    _get(
      "contract",
      "abi");
  const
    _abi_type =
      typeof(
        _abi);
  _abi_retrieve =
    false;
  if ( _abi_type === "undefined" ) {
    _abi_retrieve =
      true;
  }
  else if ( _abi_type === "string" ) {
    if ( _abi.length < 1 ) {
      _abi_retrieve =
        true;
    }
  }
  if ( _abi_retrieve ) {
    if ( 1 < _networks.length ) {
      _msg =
        "You can't currently retrieve " +
        "ABI for more than a contract.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    else if ( 1 == _networks.length ) {
      const
        _network =
          _networks[
            0];
      const
        _contract_abi_get_args = [
          _network,
          _address,
          _api_key,
          _compiler_output,
          _abi,
          _app,
          _contract
        ];
      _msg =
        "Running '_contract_abi_get' with " +
        "parameters:";
      _msg_info(
        _msg);
      if ( _quiet == "n" ) {
        _echo(
          _contract_abi_get_args);
      }
      try {
        _abi =
          await _contract_abi_get.apply(
            null,
            _contract_abi_get_args);
      }
      catch(
        _error) {
        _msg =
          "Error running '_contract_abi_get'.";
        _msg_error(
          _msg,
          0);
        _echo2(
          _error);
        throw _error;
      }
    }
    else {
      _msg =
        "You must currently select a network " +
        "to auto-detect the abi for " +
        "a libevm application contract.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  _override_set(
    "contract",
    "abi",
    _abi);
}



export {
  _app_check,
  _config_file_path_check,
  _configuration_format_auto_detect,
  _configuration_format_check,
  _configuration_format_get,
  _contract_address_check,
  _contract_version_auto_detect,
  _deployments_dir_auto_detect,
  _deployments_dir_check,
  _network_check,
  _networks_all_auto_detect,
  _target_app_auto_detect,
  _target_contract_auto_detect,
  _target_contract_check,
  _user_deployments_check,
  _user_defined_check,
  _user_level_check,
  _version_check
};

// module.exports = {
//   _app_check:
//     _app_check,
//   _config_file_path_check:
//     _config_file_path_check,
//   _configuration_format_auto_detect:
//     _configuration_format_auto_detect,
//   _configuration_format_check:
//     _configuration_format_check,
//   _configuration_format_get:
//     _configuration_format_get,
//   _contract_abi_get:
//     _contract_abi_get,
//   _contract_abi_auto_detect:
//     _contract_abi_auto_detect,
//   _contract_version_auto_detect:
//     _contract_version_auto_detect,
//   _deployments_dir_check:
//     _deployments_dir_check,
//   _deployments_dir_auto_detect:
//     _deployments_dir_auto_detect,
//   _network_check:
//     _network_check,
//   _networks_all_auto_detect:
//     _networks_all_auto_detect,
//   _target_app_auto_detect:
//     _target_app_auto_detect,
//   _target_contract_auto_detect:
//     _target_contract_auto_detect,
//   _target_contract_check:
//     _target_contract_check,
//   _contract_address_check:
//     _contract_address_check,
//   _user_deployments_check:
//     _user_deployments_check,
//   _user_defined_check:
//     _user_defined_check,
//   _user_level_check:
//     _user_level_check,
//   _version_check:
//     _version_check,
// };
