#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-chains-info
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _dirname */
/* eslint-disable-next-line
     no-global-assign */
_dirname =
  _libcrash_module._dirname;
/* global
     _file_exists */
/* eslint-disable-next-line
     no-global-assign */
_file_exists =
  _libcrash_module._file_exists;
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
_homedir_get =
  _libcrash_module._homedir_get;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
_json_read =
  _libcrash_module._json_read;
/* global
     _lib_get */
/* eslint-disable-next-line
     no-global-assign */
_lib_get =
  _libcrash_module._lib_get;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
_msg_info =
  _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
_msg_error =
  _libcrash_module._msg_error;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
_path_join =
  _libcrash_module._path_join;
/* global
     _range */
/* eslint-disable-next-line
     no-global-assign */
_range =
  _libcrash_module._range;
_evm_contracts_tools_module =
  require("./evm-contracts-tools");
/* global
     _address_check */
_address_check =
  _evm_contracts_tools_module._address_check;

const
  _ethereum_data_module =
    require(
      "ethereum-data");
/* global
     _data_get */
const
  _data_get =
    _ethereum_data_module._data_get;

function
  _target_networks_auto_detect() {
  // TODO:
  //   _evm_wallet_module.balance-discovery
  if ( target_networks == "" ||
       target_networks == [] ) {
    // to be auto-detected
    target_networks = [
      "1"
    ];
  }
  if ( target_network == "" ) {
    // to be auto-detected
    target_network =
      "1";
  }
}

function
  _default_artifact_path_get(
    _type) {
  let
    _file_name;
  const
    _home =
      _homedir_get();
  const
    _data_dir =
      _path_join( [
        _home,
        ".local",
        "share",
        "evm-contract-call" ]);
  if ( _type == "abi" ) {
    _file_name =
      `${contract_address}.abi.json`;
  }
  else if ( _type == "bytecode" ) {
    _file_name =
      `${contract_address}.bin`;
  }
  else if ( _type == "compiler_output" ) {
    _file_name =
      `${contract_address}.json`;
  }
  else {
    const
      _msg =
        `Unknown artifact type '${_type}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _artifact =
      _path_join( [
        _data_dir,
        target_network,
        _file_name ]);
  return _artifact;
}

function
  _contract_artifacts_retrieve() {
  true;
}

function
  _contract_abi_auto_detect() {
  let
    _abi,
    _abi_target;
  const
    _network =
      target_network;
  const
    _address =
      contract_address;
  const
    _key =
      api_key;
  const
    _compiler_output =
      contract_compiler_output;
  _abi =
    contract_abi;
    _abi_target =
      _abi;
  if ( typeof(
         _abi_target) == "undefined" ||
       _abi_target == "" ) {
    _abi_target =
      _default_artifact_path_get(
        "abi");
  }
  const
    _abi_dir =
      _dirname(
        _abi);
  if ( ! _file_exists(
           _abi) &&
       ! _file_exists(
           _compiler_output) ) {
    if ( _file_exists(
           _abi_target) ) {
      _abi =
        _abi_target;
    }
    else {
      _contract_artifacts_retrieve(
        _abi_dir);
    }
  }
}

function
  _call_auth_auto_detect() {
  if ( call_type == "static" ) {
    call_auth =
      "n";
  }
  else if ( call_type == "dynamic" ) {
    call_auth =
      "y";
  }
  else {
    const
      _msg =
        `Unknown call type '${call_type}'.`;
    _msg_error(
      _msg,
      1);
  }
}

function
  _evm_contract_call(
    _call_type,
    _call_timeout,
    _wallet_name,
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _api_key,
    _msg_value,
    _price_gas,
    _measure_unit,
    _retries_max,
    _target_networks,
    _rpc_selection,
    _contract_address,
    _contract_abi,
    _contract_bytecode,
    _contract_compiler_output,
    _contract_method,
    _method_args) {
  let
    _explorer,
    _out,
    _result,
    _rpc;
  if ( _call_type == "static" ) {
    const
      _infos =
        [];
    _out =
      "";

  }
  else if ( _call_type == "dynamic" ) {
    _out =
      "";
  }
  else {
    const
      _msg =
        `Unknown call type ` +
        `'${_call_type}'.`;
    _msg_error(
      _msg,
      1);
  }
  return _out;
}

function
  _artifact_local_auto_detect(
    _type) {
  const
    _artifact =
      _default_artifact_path_get(
        _type);
  if ( _type == "abi" ) {
    contract_abi =
      _artifact;
  }
  else if ( _type == "bytecode" ) {
    contract_bytecode =
      _artifact;
  }
  else if ( _type == "compiler_output" ) {
    contract_compiler_output =
      _artifact;
  }
}

module.exports = {
  _artifact_local_auto_detect:
    _artifact_local_auto_detect,
  _call_auth_auto_detect:
    _call_auth_auto_detect,
  _contract_abi_auto_detect:
    _contract_abi_auto_detect,
  _default_artifact_path_get:
    _default_artifact_path_get,
  _evm_contract_call:
    _evm_contract_call,
  _target_networks_auto_detect:
    _target_networks_auto_detect
};
