#!/usr/bin/env node


// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contracts-tools
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash_module =
    require(
      "crash-js");
const
  _bytecode_creation_get_module =
    require(
      "./lib/bytecode-creation-get");
/* global
     _bytecode_creation_get */
const
  _bytecode_creation_get =
    _bytecode_creation_get_module._bytecode_creation_get;
const
  _bytecode_runtime_get_module =
    require(
      "./lib/bytecode-runtime-get");
/* global
     _bytecode_runtime_get */
const
  _bytecode_runtime_get =
    _bytecode_runtime_get_module._bytecode_runtime_get;

const
  _contract_get_module =
    require(
      "./lib/contract-get");
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get;
const
  _deployer_get_module =
    require(
      "./lib/deployer-get");
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;
const
  _deployer_verify_module =
    require(
      "./lib/deployer-verify");
/* global
     _deployer_verify */
const
  _deployer_verify =
    _deployer_verify_module._deployer_verify;
const
  _evm_contract_call_dynamic_module =
    require(
      "./lib/evm-contract-call-dynamic");
/* global
     _evm_contract_call_dynamic */
const
  _evm_contract_call_dynamic =
    _evm_contract_call_dynamic_module._evm_contract_call_dynamic;
const
  _evm_contract_call_static_module =
    require(
      "./lib/evm-contract-call-static");
/* global
     _evm_contract_call_static */
const
  _evm_contract_call_static =
    _evm_contract_call_static_module._evm_contract_call_static;

module.exports = {
  _bytecode_creation_get:
    _bytecode_creation_get,
  _bytecode_runtime_get:
    _bytecode_runtime_get,
  _contract_get:
    _contract_get,
  _deployer_get:
    _deployer_get,
  _deployer_verify:
    _deployer_verify,
  _evm_contract_call_dynamic:
    _evm_contract_call_dynamic,
  _evm_contract_call_static:
    _evm_contract_call_static,
};
