#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployments-dir
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _lib_get */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;

function
  _app_check(
    _app,
    _local) {
  let
    _undefined_flag,
    _msg;
  const
    _local_type =
      typeof(
        _local);
  if ( _local_type === "undefined" ) {
    _msg =
      "Local not specified, setting default " +
      "value 'false'.";
    _local =
      true;
  }
  else if ( _local_type !== "boolean" ) {
    _msg =
      "Variable '_local' must be a boolean.";
    _msg_error(
      _msg,
      0);
  }
  const
    _app_type =
      typeof(
        _app);
  if ( _app_type == "undefined" ) {
    _msg =
      "No application specified.";
    _undefined_flag =
      true;
  }
  if ( _app_type == "string" ) {
    if ( _app.length < 1 ) {
      _msg =
        "No application specified.";
      _undefined_flag =
        true;
    }
  }
  else {
    _msg =
      "Application argument must be of " +
      "type string.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _undefined_flag ) {
    if ( _local ) {
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    else {
      _msg =
        "Local option disabled, " +
        "getting '_app' variable from " +
        "global variable 'target_app'.";
      _msg_info(
        _msg);
      const
        _global =
          _global_get();
      const
        _target_app =
          _get(
            "target",
            "app");
      const
        _target_app_type =
          typeof(
            _target_app);
      if ( _target_app_type === "string" ) {
        if ( 0 < _target_app.length ) {
          _msg =
            "Getting '_app' variable value from " +
            "global variable 'target_app'.";
          _msg_info(
            _msg);
          _app =
            _target_app;
        }
        else {
          _msg =
            "Error while auto-detecting '_app' variable " +
            "value, global variable 'target_app' " +
            "also not set.";
          _msg_error(
            _msg,
            0);
          throw _msg;
        }
      }
      else {
        _msg =
          "Global variable 'target_app' has " +
          "the wrong type for the local " +
          `variable '_app' ('${_target_app_variable}')`;
        _msg_error(
          _msg,
          0);
        throw _msg;
      }
    }
  }
  return _app;
}

async function
  _default_deployments_dir_get(
    _app,
    _type) {
  _app =
    _app_check(
      _app);
  if ( typeof(
         _type) == "undefined" ||
       _type == "" ) {
    _type =
      "system";
  }
  let
    _conf_dir;
  if ( _type == "system" ) {
    _conf_dir =
      await _lib_get();
  }
  else if ( _type == "user" ) {
    const
      _homedir =
        _homedir_get();
    _conf_dir =
      `${_homedir}/.config`;
  }
  return `${_conf_dir}/${_app}/deployments`;
}

async function
  _evm_contract_deployments_dir(
    _app,
    _user_level) {
  let
    _deployment_type;
  _app =
    _app_check(
      _app);
  if ( _user_level == "n" ) {
    _deployment_type =
      "system";
  }
  else if ( _user_level == "y" ) {
    _deployment_type =
      "user";
  }
  else {
    const
      _msg =
        "User level argument must be " +
        "can be 'y' or 'n'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  const
    _deployments =
      await _default_deployments_dir_get(
        _app,
        _deployment_type);
  return _deployments;
}

export {
  _default_deployments_dir_get,
  _evm_contract_deployments_dir,
};

// module.exports = {
//   _default_deployments_dir_get:
//     _default_deployments_dir_get,
//   _evm_contract_deployments_dir:
//     _evm_contract_deployments_dir,
// };
