#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployment
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _basename */
const
  _basename =
    _libcrash_module._basename;
/* global
     _chmod */
const
  _chmod =
    _libcrash_module._chmod;
/* global
     _cp */
const
  _cp =
    _libcrash_module._cp;
/* global
     _dir_exists */
const
  _dir_exists =
    _libcrash_module._dir_exists;
/* global
     _echo */
const
  _echo =
    _libcrash_module._echo;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash_module._file_read;
/* global
     _from_bash_ass_array */
const
  _from_bash_ass_array =
    _libcrash_module._from_bash_ass_array;
/* global
     _get */
const
  _get =
    _libcrash_module._get;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash_module._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash_module._path_join;
/* global
     _pwd */
const
  _pwd =
    _libcrash_module._pwd;
/* global
     _require */
const
  _require =
    _libcrash_module._require;
const
  _evm_chains_info_module =
    await _require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;
  /* global
       _evm_contract_deployments_dir */
/* global
     _evm_contract_deployment_networks */
/* global
     _evm_contract_deployment_versions */

function
  _configuration_format_check(
    _configuration_format) {
  let
    _msg;
  const
    _configuration_format_type =
      typeof(
        _configuration_format);
  if ( _configuration_format_type === "undefined" ) {
    _msg =
      "Configuration format not set, " +
      "setting default (bash).";
    _msg_info(
      _msg);
    _configuration_format =
      "bash";
  }
  else if ( _configuration_format_type === "string" ) {
    if ( _configuration_format.length < 1 ) {
      _msg =
        "Configuration format not set, " +
        "setting default (bash).";
      _msg_info(
        _msg);
      _configuration_format =
        "bash";
    }
    else {
      _msg =
        "Setting configuration format " +
        `'${_configuration_format}'.`;
    }
  }
  else {
    _msg =
      "Type of variable " +
      "'configuration format' must be string.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _configuration_format !== "bash" &&
       _configuration_format !== "json" ) {
    _msg =
      "Unknown configuration format " +
      `'${_configuration_format}'.`
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _configuration_format;
}

async function
  _network_check(
    _deployments,
    _contract,
    _target_network,
    _target_network_id) {
  let
    _contract_deployments_path,
    _error_flag,
    _evm_contract_deployment_networks,
    _evm_chains_info_args,
    _msg,
    _network_id;
  _msg =
    "Network check for deployments " +
    `'${_deployments}', contract '${_contract}', ` +
    `network '${_target_network}' and network with ID ` +
    `'${_target_network_id}'.`;
  _msg_info(
    _msg);
  _evm_contract_deployment_networks =
    _get(
      "_evm_contract",
      "deployment_networks");
  const
    _evm_contract_deployment_networks_type =
      typeof(
        _evm_contract_deployment_networks_dir);
  if ( _evm_contract_deployment_networks_type == "undefined" ||
       _evm_contract_deployment_networks == "" ) {
    const
      _libevm_contract_deployment_networks_module =
        await import(
          "./libevm-contract-deployment-networks");
      _evm_contract_deployment_networks =
        _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;
  }
  _error_flag =
    false;
  _contract_deployments_path =
    _path_join( [
      _deployments,
      _contract ]);
  const
    _evm_contract_deployment_networks_args = [
      _contract_deployments_path,
      "y",                  // Display all
      "n",                  // Display safest
      "n"                   // Display cheapest
    ];
  const
    _networks =
      await _evm_contract_deployment_networks.apply(
        null,
        _evm_contract_deployment_networks_args);
  if ( _target_network_id != "" ) {
    if ( ! _networks.includes(
             _target_network_id) ) {
      _msg =
        "The contract does not result deployed on " +
        `network with id '${_target_network_id}'.`;
      _error_flag =
        true;
    }
  }
  else if ( _target_network != "" ) {
    if ( ! _networks.includes(
             _target_network) ) {
      _msg =
        "The contract does not result deployed on " +
        `network '${_target_network}'.`;
      _error_flag =
        true;
    }
  }
  else {
    _msg =
      "Provide one between a target network name " +
      "or ID.";
    _error_flag =
      true;
  }
  if ( _error_flag ) {
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _target_network_id == "" ) {
    _evm_chains_info_args = [
      "get",             // target command
      "name",            // input type
      "id",              // output type
      "offline",
      [ "system",        // db types
        "node" ],
      "kirsh",           // selection method, first
      "n",               // api keys
      "n",               // query all networks
      _target_network,
      []                 // database paths
    ];
    try {
      _network_id =
        await _evm_chains_info.apply(
          null,
          _evm_chains_info_args);
    }
    catch(
      _error) {
      _msg = 
        "Error while running '_evm_chains_info' " +
        `with arguments '${_evm_chains_info_args}'.`;
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  else if ( _target_network == "" ) {
    _network_id =
      _target_network_id;
    _evm_chains_info_args = [
      "get",             // target command
      "id"  ,            // input type
      "name",            // output type
      "offline",
      [ "system",        // db types
        "node" ],
      "kirsh",           // selection method, first
      "n",               // api keys
      "n",               // query all networks
      _target_network_id,
      []                 // database paths
    ];
    try {
      _target_network =
        await _evm_chains_info.apply(
          null,
          _evm_chains_info_args);
    }
    catch(
      _error) {
      _msg = 
        "Error while running '_evm_chains_info' " +
        `with arguments '${_evm_chains_info_args}'.`;
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  if ( _target_network_id != "" ) {
    if ( _target_network_id != _network_id ) {
      _msg =
        "Requested target network ID " +
        `'${_target_network_id}' does ` +
        `not correspond to '${_target_network}' ` +
        `known ID '${_network_id}'.`;
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  _msg =
    "Network check for deployments " +
    `'${_deployments}', contract '${_contract}', ` +
    `network '${_target_network}' and network with ID ` +
    `'${_target_network_id}' completed.`;
  _msg_info(
    _msg);
}

async function
  _user_deployments_init(
    _app,
    _deployments_dir) {
  let
    _evm_contract_deployments_dir;
  const
    _user_defined =
      "y";
  _evm_contract_deployments_dir =
    _get(
      "_evm_contract",
      "deployments_dir");
  const
    _evm_contract_deployments_dir_type =
      typeof(
        _evm_contract_deployments_dir);
  if ( _evm_contract_deployments_dir_type == "undefined" ||
       _evm_contract_deployments_dir == "" ) {
    const
      _libevm_contract_deployments_dir_module =
        await import(
          "./libevm-contract-deployments-dir");
      _evm_contract_deployments_dir =
        _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
  }
  const
    _evm_contract_deployments_dir_args = [
      _app,
      _user_defined
    ];
  const
    _system_deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  _chmod(
    _deployments_dir,
    "0700");
  const
    _files =
      await _ls(
        _system_deployments);
  for ( _file of _files ) {
    _cp(
      _file,
      _deployments_dir);
  }
  return true;
}

async function
  _user_deployments_check(
    _app,
    _deployments_dir) {
  if ( ! _file_exists(
           _deployments_dir) ) {
    const
      _user_deployments_init_args = [
        _app,
        _deployments_dir
      ];
    const
      _initialized =
        await _user_deployments_init.apply(
          null,
          _user_deployments_init_args);
  }
}

function
  _user_defined_check(
    _user_defined) {
  let
    _msg;
  const
    _user_defined_type =
      const
        typeof(
          _user_defined);
  if ( _user_defined_type === "undefined" ) {
    _msg =
      "Variable '_user_defined' undefined, " +
      "setting default value 'n'.";
    _msg_info(
      _msg);
    _user_defined =
      "n";
  }
  else if ( _user_defined_type === "string" ) {
    if ( _user_defined.length < 1 ) {
      _msg =
        "Variable '_user_defined' not set, " +
        "setting default value 'n'.";
      _msg_info(
        _msg);
      _user_defined =
        "n";
    }
    else {
      _msg =
        "Variable '_user_defined' can have " +
        "value 'y' or 'n'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  else {
    _msg =
      "Variable '_user_defined' must be of type " +
      "string and have value 'y' or 'n'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _user_defined;
}

function
  _user_level_check(
    _user_level) {
  let
    _msg;
  const
    _user_level_type =
      const
        typeof(
          _user_level);
  if ( _user_level_type === "undefined" ) {
    _msg =
      "Variable '_user_level' undefined, " +
      "setting default value 'n'.";
    _msg_info(
      _msg);
    _user_level =
      "n";
  }
  else if ( _user_level_type === "string" ) {
    if ( _user_level.length < 1 ) {
      _msg =
        "Variable '_user_level' not set, " +
        "setting default value 'n'.";
      _msg_info(
        _msg);
      _user_level =
        "n";
    }
    else {
      _msg =
        "Variable '_user_level' can have " +
        "value 'y' or 'n'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  else {
    _msg =
      "Variable '_user_level' must be of type " +
      "string and have value 'y' or 'n'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _user_level;
}

async function
  _deployments_dir_check(
    _deployments_dir,
    _app,
    _user_defined) {
  try {
    _user_defined =
      _user_defined_check(
        _user_defined);
  }
  catch(
    _error) {
    _msg =
      "Error checking '_user_defined' " +
      "variable:";
    _msg_error(
      _msg,
      0);
    _echo2(
      _user_defined);
    _echo2(
      _error);
    throw _error;
  }
}

async function
  _deployments_dir_auto_detect() {
  let
    _deployments,
    _evm_contract_deployments_dir;
  _deployments =
    "";
  const
    _app =
      target_app;
  const
    _app_type =
      typeof(
        _app);
  if ( _app_type != "undefined" &&
       _app != "" ) {
    const
      _user_defined =
        user_defined;
    _evm_contract_deployments_dir =
      _get(
        "_evm_contract",
        "deployments_dir");
    const
      _evm_contract_deployments_dir_type =
        typeof(
          _evm_contract_deployments_dir);
    if ( _evm_contract_deployments_dir_type == "undefined" ||
         _evm_contract_deployments_dir == "" ) {
      const
        _libevm_contract_deployments_dir_module =
          await import(
            "./libevm-contract-deployments-dir");
        _evm_contract_deployments_dir =
          _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
    }
    const
      _evm_contract_deployments_dir_args = [
        _app,
        _user_defined
      ];
    _deployments =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  }
  _override_set(
    "deployments",
    "dir",
    _deployments);
}

function
  _app_check(
    _app,
    _local) {
  let
    _undefined_flag,
    _msg;
  const
    _local_type =
      typeof(
        _local);
  if ( _local_type === "undefined" ) {
    _msg =
      "Local not specified, setting default " +
      "value 'false'.";
    _local =
      true;
  }
  else if ( _local_type !== "boolean" ) {
    _msg =
      "Variable '_local' must be a boolean.";
    _msg_error(
      _msg,
      0);
  }
  const
    _app_type =
      typeof(
        _app);
  if ( _app_type == "undefined" ) {
    _msg =
      "No application specified.";
    _undefined_flag =
      true;
  }
  if ( _app_type == "string" ) {
    if ( _app.length < 1 ) {
      _msg =
        "No application specified.";
      _undefined_flag =
        true;
    }
  }
  else {
    _msg =
      "Application argument must be of " +
      "type string.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _undefined_flag ) {
    if ( _local ) {
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    else {
      _msg =
        "Local option disabled, " +
        "getting '_app' variable from " +
        "global variable 'target_app'.";
      _msg_info(
        _msg);
      const
        _global =
          _global_get();
      const
        _target_app =
          _get(
            "target",
            "app");
      const
        _target_app_type =
          typeof(
            _target_app);
      if ( _target_app_type === "string" ) {
        if ( 0 < _target_app.length ) {
          _msg =
            "Getting '_app' variable value from " +
            "global variable 'target_app'.";
          _msg_info(
            _msg);
          _app =
            _target_app;
        }
        else {
          _msg =
            "Error while auto-detecting '_app' variable " +
            "value, global variable 'target_app' " +
            "also not set.";
          _msg_error(
            _msg,
            0);
          throw _msg;
        }
      }
      else {
        _msg =
          "Global variable 'target_app' has " +
          "the wrong type for the local " +
          `variable '_app' ('${_target_app_variable}')`;
        _msg_error(
          _msg,
          0);
        throw _msg;
      }
    }
  }
  return _app;
}

async function
  _contract_version_auto_detect() {
  let
    _config,
    _config_ext,
    _deployments,
    _evm_contracts_deployment_versions,
    _found,
    _net,
    _network,
    _network_id,
    _networks,
    _version,
    _msg;
  _networks =
    [];
  const
    _contract =
      target_contract;
  _found =
    false;
  if ( configuration_format == "bash" ) {
    _config_ext =
      "sh";
  }
  else if ( configuration_format == "bash" ) {
    _config_ext =
      "json";
  }
  const
    _contract_type =
      typeof(
        _contract);
  if ( _contract != "" &&
       _contract_type != "undefined" ) {
    const
      _deployments_dir_type =
        typeof(
          deployments_dir);
    if ( _deployments_dir_type != "undefined" &&
         deployments_dir != "" ) {
      _deployments =
        deployments_dir;
      if ( 0 < target_networks.length ) {
        _network =
          target_networks[
            0];
      }
      if ( 0 < network_ids.length ) {
        _network_id =
          _network_ids[
            0];
      }
      const
        _deployments_path =
          _path_join( [
            _deployments,
            _contract ] );
      if ( networks_all == "n" ) {
        _networks.push(
          _network,
          _network_id);
      }
      else if ( networks_all == "y" ) {
        const
          _evm_contract_deployment_networks_args = [
            _deployments_path,
            "y",                  // Display all
            "n",                  // Display safest
            "n"                   // Display cheapest
          ];
        _networks_new =
          await _evm_contract_deployment_networks.apply(
            null,
            _evm_contract_deployment_networks_args);
        _networks =
          _networks.concat(
            _networks_new);
      }
      for ( _net of _networks ) {
        _config =
          _path_join( [
            _deployments_path,
            _net,
            `config.${_config_ext}`
            ]);
        if ( _file_exists(
               _config) ) {
          _found =
            true;
          _msg =
            `Found deployment configuration ` +
            `at location '${_config}'.`;
          _msg_info(
            _msg);
          break;
        }
      }
      if ( ! _found ) {
        _msg =
          "No deployment configuration " +
          "file found for network " +
          `'${_network}' with ID ` +
          `'${_network_id}'.`;
        _msg_error(
          _msg,
          1);
      }
      const
        _libevm_contract_deployment_versions_module =
          await import(
            "./libevm-contract-deployment-versions");
      _evm_contract_deployment_versions =
        _get(
          "_evm_contract",
          "deployment_versions");
      const
        _evm_contract_deployment_versions_type =
          typeof(
            _evm_contract_deployment_versions_dir);
      if ( _evm_contract_deployment_versions_type == "undefined" ||
           _evm_contract_deployment_versions == "" ) {
        const
          _libevm_contract_deployment_versions_module =
            await import(
              "./libevm-contract-deployment-versions");
          _evm_contract_deployment_versions =
            _libevm_contract_deployment_versions_module._evm_contract_deployment_versions;
      }
      const
        _evm_contract_deployment_versions_args = [
          _config,
          "y",                  // display highest
          "n",                  // display lowest
          configuration_format
        ];
      _version =
        await _evm_contract_deployment_versions.apply(
          null,
          _evm_contract_deployment_versions_args);
    }
    else if ( _deployments_dir_type == "undefined" ||
              deployments_dir == "" ) {
      const
        _msg =
          "If no target application is specified " +
          "then the user-defined deployments " +
          "switch must be enabled with '-u' and " +
          "a deployments directory must be specified " +
          "with '-d'.";
      _msg_error(
        _msg,
        1);
    }
  }
  _override_set(
    "contract",
    "version",
    _version);
  return true;
}

function
  _networks_all_auto_detect() {
  let
    _networks_all;
  _networks_all =
    "n";
  if ( target_networks.length < 1 &&
       network_ids.length < 1 ) {
    _networks_all =
      "y";
  }
  _override_set(
    "networks",
    "all",
    _networks_all);
}

async function
  _target_app_auto_detect() {
  let
    _app;
  _app =
    "";
  const
    _dir_current_name =
      _basename(
        _pwd());
  const
    _user_defined =
      user_defined;

  const
    _evm_contract_deployments_dir_args = [
      _dir_current_name,
      _user_defined
    ];
  const
    _target_dir =
      await _evm_contract_deployments_dir.apply(
        null,
        _evm_contract_deployments_dir_args);
  if ( _dir_exists(
         _target_dir) ) {
    _app =
      _dir_current_name;
  }
  else {
    _msg =
      `Directory '${_target_dir}' ` +
      "not found.";
    _msg_info(
      _msg);
  }
  _override_set(
    "target",
    "app",
    _app);
}

function
  _configuration_format_get(
    _config_file) {
  let
    _configuration_format;
  if ( _config_file.endsWith(
         ".sh") ) {
    _configuration_format =
      "bash";
  }
  else if ( _config_file.endsWith(
         ".json") ) {
    _configuration_format =
      "json";
  }
  else {
    const
      _msg =
        "Impossible determining " +
        "configuration format from file " +
        "extension, defaulting to 'json'.";
    _msg_info(
      _msg,
      0);
    throw _msg;
  }
  return _configuration_format;
}

function
  _configuration_format_auto_detect() {
  const
    _configuration_format =
      _configuration_format_get(
        config_file);
  _override_set(
    "configuration",
    "format",
    _configuration_format);
}

export {
  _app_check,
  _configuration_format_auto_detect,
  _configuration_format_get,
  _contract_version_auto_detect,
  _deployments_dir_auto_detect,
  _network_check,
  _networks_all_auto_detect,
  _target_app_auto_detect,
  _user_deployments_check,
  _user_defined_check,
  _user_level_check,
};

// module.exports = {
//   _app_check:
//     _app_check,
//   _configuration_format_auto_detect:
//     _configuration_format_auto_detect,
//   _configuration_format_get:
//     _configuration_format_get,
//   _contract_version_auto_detect:
//     _contract_version_auto_detect,
//   _deployments_dir_auto_detect:
//     _deployments_dir_auto_detect,
//   _network_check:
//     _network_check,
//   _networks_all_auto_detect:
//     _networks_all_auto_detect,
//   _target_app_auto_detect:
//     _target_app_auto_detect,
//   _user_deployments_check:
//     _user_deployments_check,
//   _user_defined_check:
//     _user_defined_check,
//   _user_level_check:
//     _user_level_check,
// };
