#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-call
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */
/* eslint-disable
     no-useless-assignment */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _dirname */
const
  _dirname =
    _libcrash_module._dirname;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _get */
const
  _get =
    _libcrash_module._get;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _lib_get */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash_module._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash_module._path_join;
/* global
     _range */
const
  _range =
    _libcrash_module._range;
/* global
     _require */
const
  _require =
    _libcrash_module._require;
/* global
     _set */
const
  _set =
    _libcrash_module._set;
const
  _evm_contracts_tools_module =
    await import(
      "./evm-contracts-tools");
/* global
     _address_check */
const
  _address_check =
    _evm_contracts_tools_module._address_check;
const
  _evm_contract_deployment_address_module =
    await import(
      "./libevm-contracts-deployment-address");
/* global
     _evm_contract_deployment_address */
const
  _evm_contract_deployment_address =
    _evm_contract_deployment_address_module._evm_contract_deployment_address;
const
  _ethereum_data_module =
    await _require(
      "ethereum-data");
/* global
     _data_get */
const
  _data_get =
    _ethereum_data_module._data_get;

function
  _target_networks_get(
    _target_networks) {
  // TODO:
  //   _evm_wallet_module._balance_discovery
  const
    _target_networks_type =
      typeof(
        _target_networks);
  if ( _target_networks_type == "undefined" ) {
    _target_networks =
      _get(
        "target",
        "networks");
  }
  if ( _target_networks == "" ||
       _target_networks == [] ) {
    // to be auto-detected
    _target_networks = [
        "1"
      ];
  }
  const
    _target_network =   
      _target_network[0];
  return [ _target_networks,
           _target_network ];
}

function
  _target_networks_auto_detect() {
  // TODO:
  //   _evm_wallet_module._balance_discovery
  let
    _target_network,
    _target_networks;
  _target_networks =
    _get(
      "target",
      "networks");
  [ _target_networks,
    /* eslint-disable-next-line
         prefer-const */  
    _target_network ] =
    _target_networks_auto_detect(
      _target_networks);
  _set(
    "target",
    "networks",
    _target_networks);
  _override_set(
    "target",
    "network",
    _target_network);
}

function
  _default_artifact_path_get(
    _type) {
  let
    _file_name;
  const
    _home =
      _homedir_get();
  const
    _data_dir =
      _path_join( [
        _home,
        ".local",
        "share",
        "evm-contract-call" ]);
  if ( _type == "abi" ) {
    _file_name =
      `${contract_address}.abi.json`;
  }
  else if ( _type == "bytecode" ) {
    _file_name =
      `${contract_address}.bin`;
  }
  else if ( _type == "compiler_output" ) {
    _file_name =
      `${contract_address}.json`;
  }
  else {
    const
      _msg =
        `Unknown artifact type '${_type}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _artifact =
      _path_join( [
        _data_dir,
        target_network,
        _file_name ]);
  return _artifact;
}

function
  _contract_artifacts_retrieve() {
  true;
}

function
  _contract_abi_get(
    _network,
    _address,
    _api_key,
    _compiler_output,
    _abi) {
  let
    _abi_target;
  const
    _abi_type =
      typeof(
        _abi);
  if ( _abi_type == "undefined" ) {
    _abi =
      _get(
        "contract",
        "abi");
  }
  const
    _network_type =
      typeof(
        _network);
  if ( _network_type == "undefined" ) {
    _network =
      _get(
        "target",
        "network");
  }
  const
    _address_type =
      typeof(
        _address);
  if ( _address_type == "undefined" ) {
    _address =
      _get(
        "contract",
        "address");
  }
  const
    _api_key_type =
      typeof(
        _api_key);
  if ( _api_key_type == "undefined" ) {
    _api_key =
      _get(
        "api",
        "key");
  }
  const
    _compiler_output_type =
      typeof(
        _compiler_output);
  if ( _compiler_output_type == "undefined" ) {
    _compiler_output =
      _get(
        "contract",
        "compiler_output");
  }
  _abi_target =
    _abi;
  if ( typeof(
         _abi_target) == "undefined" ||
       _abi_target == "" ) {
    _abi_target =
      _default_artifact_path_get(
        "abi");
  }
  const
    _abi_dir =
      _dirname(
        _abi);
  if ( ! _file_exists(
           _abi) &&
       ! _file_exists(
           _compiler_output) ) {
    if ( _file_exists(
           _abi_target) ) {
      _abi =
        _abi_target;
    }
    else {
      _contract_artifacts_retrieve(
        _abi_dir);
    }
  }
  return _abi;
}

function
  _contract_abi_auto_detect() {
  let
    _abi;
  const
    _network =
      _get(
        "target",
        "network");
  const
    _address =
      _get(
        "contract",
        "address");
  const
    _api_key =
      _get(
        "api",
        "key");
  const
    _compiler_output =
      _get(
        "contract",
        "compiler_output");
  _abi =
    _get(
      "contract",
      "abi");
  _abi =
    _contract_abi_get(
      _network,
      _address,
      _api_key,
      _compiler_output,
      _abi);
  _override_set(
    "contract",
    "abi",
    _abi);
}

function
  _call_auth_get(
    _call_type) {
  let
    _call_auth;
  const
    _call_type_type =
      typeof(
        _call_type);
  if ( _call_type_type == "undefined" ) {
    _call_type =
      _get(
        "call",
        "type");
  }
  if ( _call_type == "static" ) {
    _call_auth =
      "n";
  }
  else if ( call_type == "dynamic" ) {
    _call_auth =
      "y";
  }
  else {
    const
      _msg =
        `Unknown call type '${call_type}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _call_auth;
}

function
  _call_auth_auto_detect() {
  const
    _call_type =
      _get(
        "call",
        "type");
  const
    _call_auth =
      _call_auth_get(
        _call_type);
  _override_set(
    "call",
    "type",
    _call_type);
}

async function
  _evm_contract_call(
    _call_type,
    _call_timeout,
    _wallet_name,
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _api_key,
    _msg_value,
    _price_gas,
    _measure_unit,
    _retries_max,
    _target_networks,
    _rpc_selection,
    _contract_address,
    _contract_abi,
    _contract_bytecode,
    _contract_compiler_output,
    _contract_method,
    _method_args) {
  let
    _explorer,
    _out,
    _result,
    _rpc;
  if ( _call_type == "static" ) {
    const
      _infos =
        [];
    _out =
      "";
  }
  else if ( _call_type == "dynamic" ) {
    _out =
      "";
  }
  else {
    const
      _msg =
        `Unknown call type ` +
        `'${_call_type}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  return _out;
}

function
  _artifact_local_auto_detect(
    _artifact_type) {
  const
    _artifact =
      _default_artifact_path_get(
        _artifact_type);
  if ( _artifact_type == "abi" ) {
    _override_set(
      "contract",
      "abi",
      _artifact);
  }
  else if ( _artifact_type == "bytecode" ) {
    _override_set(
      "contract",
      "bytecode",
      _artifact);
  }
  else if ( _artifact_type == "compiler_output" ) {
    _override_set(
      "contract",
      "compiler_output",
      _artifact);
  }
}

async function
  _target_app_get(
    _contract_address) {
  let
    _target_app;
  _target_app =
    ""
  const
    _contract_address_type =
      typeof(
        _contract_address);
  if ( _contract_address_type != "undefined" &&
       _contract_address != "" ) {
    const
      _address_valid =
        _address_check(
          _contract_address);
    if ( ! _address_valid ) {
      _target_app =
        await _app_lookup_contract(
          _contract_address);
    }
  }
  return _target_app;
}

async function
  _contract_lookup_address(
    _target_app,
    _address,
    _target_network) {
  let
    _contract,
    _contract_address,
    _contract_networks,
    _evm_contract_deployment_address_args,
    _exception,
    _msg,
    _network;
  const
    _target_contracts =
      {};
  const
    _lib =
      await _lib_get();
  const
    _deployments_dir =
      _path_join([
        _lib,
        _target_app,
        "deployments"
      ]);
  const
    _contracts =
      await _ls(
        _deployments_dir);
  for ( _contract of _contracts ) {
    _contract_networks =
      await ls(
        _path_join([
          _deployments_dir,
          _contract
        ]);
    for ( _network in _contract_networks ) {
      _evm_contract_deployment_address_args = [
        [ _target_network ],       // target networks
        [ _target_network ],       // target chain ids
        "n",                       // all networks
        _target_app,
        _contract,
        "",                        // contract version
        "n",                       // user-level
        "",                        // configuration format
        _deployments_dir
      ];
      _contract_address =
        await _evm_contract_deployment_address.apply(
          null,
          _evm_contract_deployment_address_args);
      if ( _address == _contract_address ) {
        if ( _target_network == "" ) {
          _target_contracts[
            _contract] =
            1;
        }
        else {
          if ( _network == _target_network ) {
            _target_contracts[
              _contract] =
              1;
          }
	}
      }
    }
  }
  const
    _target_contracts_set =
      Object.keys(
        _target_contracts);
  const
    _target_contracts_amount =
      _target_contracts_set.length; 
  if ( _target_contracts_amount < 1 ) {
    _msg =
      "No contract found for " +
      `address '${_address}' ` +
      `on network '${_network}' in '${_lib}'.`;
    _msg_error(
      _msg,
      0);
    _exception = {
      "msg":
        _msg
    };
    throw _exception;
  }
  if ( 1 < _target_contracts_amount ) {
    _msg =
      "Found more than one contract for " +
      `contract '${_contract_name}' ` +
      `in '${_lib}':\n`;
    for ( _contract of _target_contracts_set ) {
      _msg =
        _msg + `${_contract}\n`;
    }
    _msg_error(
      _msg,
      0);
    _exception = {
      "msg":
        _msg
    };
    throw _exception;
  }
  else {
    return _target_contracts_set;
  }
}

async function
  _app_lookup_contract(
    _contract_name) {
  let
    _app,
    _contract_dir,
    _msg;
  const
    _lib =
      await _lib_get();
  const
    _target_apps =
      {};
  const
    _apps =
      await _ls(
      _lib);
  for ( _app of _apps ) {
    _contract_dir =
      _path_join([
        _lib,
        _app,
        "deployments",
        _contract_name
      ]);
    if ( _dir_exists(
           _contract_dir) ) {
      _target_apps[
        _app] =
        1;
    }
  }
  const
    _target_apps_set =
      Object.keys(
        _target_apps);
  const
    _target_apps_amount =
      _target_apps_set.length;
  if ( _target_apps_amount < 1 ) {
    _msg =
      "No apps found for " +
      `contract '${_contract_name}' ` +
      `in '${_lib}'.`;
    _msg_error(
      _msg,
      0);
    const
      _exception = {
        "msg":
          _msg
      };
    throw _exception;
  }
  else if ( 1 < _target_apps_amount ) {
    _msg =
      "Found more than one app for " +
      `contract '${_contract_name}' ` +
      `in '${_lib}': '${_target_apps_set}'.`;
    _msg_error(
      _msg,
      0);
    const
      _exception = {
        "msg":
          _msg
      };
    throw _exception;
  }
  return _target_apps_set[
    0];
}

function
  _target_app_auto_detect() {
  let
    _target_app;
  _target_app =
    "";
  const
    _contract_address =
      _get(
        "contract",
        "address");
  const
    _contract_address_type =
      typeof(
        _contract_address);
  if ( _contract_address_type != "undefined" &&
       _contract_address != "" ) {
    _target_app =
      _target_app_get(
        _contract_address);
  }
  _override_set(
    "target",
    "app",
    _target_app);
}

async function
  _contract_address_get(
    _target_app,
    _target_contract,
    _target_network) {
  await 
}

async function
  _contract_address_auto_detect() {
  const
    _contract_address =
      _get(
        "contract",
        "address");
  const
    _target_app =
      _get(
        "target",
        "app");
  const
    _target_network =
      _get(
        "target",
        "network");
  const
    _target_contract =
      _get(
        "target",
        "contract");
  if ( _contract_address != "" ) {
    const
      _address_valid =
        await _address_check(
          _contract_address);
    if ( ! _address_valid ) {
      if ( _target_app != "" &&
           _target_network != "" &&
           _target_contract != "" ) {
        _msg =
          "Looking for address " +
          "corresponding to contract " +
          `'${_target_contract}' for the ` +
          `'${_target_app}' ` +
          "libEVM application on network " +
          `'${_target_network}'.`;
        _msg_info(
          _msg);
        _evm_contract_deployment_address_args = [
          [ _target_network ],       // target networks
          [ _target_network ],       // target chain ids
          "n",                       // all networks
          _target_app,
          _contract,
          "",                        // contract version
          "n",                       // user-level
          "",                        // configuration format
          _deployments_dir
        ];
        _contract_address =
          await _evm_contract_deployment_address.apply(
            null,
            _evm_contract_deployment_address_args);
      }
      else {
        _msg =
          "One between the " +
          `application '${_target_app}', ` +
          `the network '${_target_network}' ` +
          `or the contract '${_target_contract}' ` +
          `has not been specified.`;
        _msg_info(
          _msg);
      }
    }
  }
  _set(
    "contract",
    "address",
    _contract_address);
}

function
  _data_dir_auto_detect() {
  const
    _homedir =
      _homedir_get();
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _data_dir =
      _path_join([
        _homedir,
        ".local",
        "share",
        _app_name
      ]);
  _override_set(
    "data",
    "dir",
    _data_dir);
}

function
  _cache_dir_auto_detect() {
  const
    _homedir =
      _homedir_get();
  const
    _app_name =
      _get(
        "app",
        "name");
  const
    _cache_dir =
      _path_join([
        _homedir,
        ".cache",
        _app_name
      ]);
  _override_set(
    "cache",
    "dir",
    _cache_dir);
}

// ES6 module exports

export {
  _address_check,
  _app_lookup_contract,
  _artifact_local_auto_detect,
  _cache_dir_auto_detect,
  _call_auth_auto_detect,
  _call_auth_get,
  _contract_abi_auto_detect,
  _contract_abi_get,
  _contract_address_auto_detect,
  _data_dir_auto_detect,
  _default_artifact_path_get,
  _evm_contract_call,
  _target_app_auto_detect,
  _target_contract_auto_detect,
  _target_networks_auto_detect,
  _target_networks_get
};

// Common Javascript exports

// module.exports = {
//   _address_check:
//     _address_check,
//   _app_lookup_contract:
//     _app_lookup_contract,
//   _artifact_local_auto_detect:
//     _artifact_local_auto_detect,
//   _cache_dir_auto_detect:
//     _cache_dir_auto_detect,
//   _call_auth_auto_detect:
//     _call_auth_auto_detect,
//   _call_auth_get:
//     _call_auth_get,
//   _contract_abi_auto_detect:
//     _contract_abi_auto_detect,
//   _contract_abi_get:
//     _contract_abi_get,
//   _data_dir_auto_detect:
//     _data_dir_auto_detect,
//   _default_artifact_path_get:
//     _default_artifact_path_get,
//   _evm_contract_call:
//     _evm_contract_call,
//   _target_app_auto_detect:
//     _target_app_auto_detect,
//   _target_networks_auto_detect:
//     _target_networks_auto_detect,
//   _target_networks_get:
//     _target_networks_get
// };
