#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------
 *     libevm-contract-deployment-abi
 *     ----------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it
 *     and/or modify it under the terms of the GNU General
 *     Public License as published by the Free Software
 *     Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will
 *     be useful, but WITHOUT ANY WARRANTY; without even the
 *     implied warranty of MERCHANTABILITY or FITNESS FOR A
 *     PARTICULAR PURPOSE.
 *     See the GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* EVM Contracts tools global variables */
/* global
     call_type */
/* global
     call_auth:
       writable */

/* libEVM global variables */
/* global 
     api_key */
/* global
     contract_abi:
       writable */
/* global
     contract_address */
/* global
     contract_bytecode:
       writable */
/* global
     contract_compiler_output:
       writable */
/* global
     target_network:
       writable */
/* global
     target_networks:
       writable */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _basename */
const
  _basename =
    _libcrash_module._basename;
/* global
     _chmod */
const
  _chmod =
    _libcrash_module._chmod;
/* global
     _cp */
const
  _cp =
    _libcrash_module._cp;
/* global
     _dir_exists */
const
  _dir_exists =
    _libcrash_module._dir_exists;
/* global
     _echo2 */
const
  _echo2 =
    _libcrash_module._echo2;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash_module._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash_module._file_read;
/* global
     _from_bash_ass_array */
const
  _from_bash_ass_array =
    _libcrash_module._from_bash_ass_array;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _json_read */
const
  _json_read =
    _libcrash_module._json_read;
/* global
     _lib_get */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _mkdir */
const
  _mkdir =
    _libcrash_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash_module._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash_module._path_join;
/* global
     _pwd */
const
  _pwd =
    _libcrash_module._pwd;
/* global
     _require */
const
  _require =
    _libcrash_module._require;
const
  _evm_chains_info_module =
    await _require(
      "evm-chains-info");
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _evm_chains_info_module._evm_chains_info;
const
  _libevm_contract_deployment_module =
    await import(
      "./libevm-contract-deployment");
/* global
     _contract_version_auto_detect */
const
  _contract_version_auto_detect =
    _libevm_contract_deployment_module._contract_version_auto_detect;
/* global
     _deployments_dir_auto_detect */
const
  _deployments_dir_auto_detect =
    _libevm_contract_deployment_module._deployments_dir_auto_detect;
/* global
     _network_check */
const
  _network_check =
    _libevm_contract_deployment_module._network_check;
/* global
     _networks_all_auto_detect */
const
  _networks_all_auto_detect =
    _libevm_contract_deployment_module._networks_all_auto_detect;
/* global
     _target_app_auto_detect */
const
  _target_app_auto_detect =
    _libevm_contract_deployment_module._target_app_auto_detect;
/* global
     _user_deployments_check */
const
  _user_deployments_check =
    _libevm_contract_deployment_module._user_deployments_check;
/* global
     _user_defined_check */
const
  _user_defined_check =
    _libevm_contract_deployment_module._user_defined_check;
/* global
     _version_check */
const
  _version_check =
    _libevm_contract_deployment_module._version_check;
const
  _libevm_contract_deployments_dir_module =
    await import(
      "./libevm-contract-deployments-dir");
/* global
     _evm_contract_deployments_dir */
const
  _evm_contract_deployments_dir =
    _libevm_contract_deployments_dir_module._evm_contract_deployments_dir;
const
  _libevm_contract_deployment_networks_module =
    await import(
      "./libevm-contract-deployment-networks");
/* global
     _evm_contract_deployment_networks */
const
  _evm_contract_deployment_networks =
    _libevm_contract_deployment_networks_module._evm_contract_deployment_networks;

async function
  _contract_bytecode_get(
    _deployments,
    _app,
    _contract,
    _network,
    _network_id,
    _version,
    _configuration_format,
    _user_defined) {
  let
    _bytecode_path,
    _bytecode_retrieve,
    _bytecode,
    _break,
    _found,
    _key_name,
    _msg,
    _net,
    _non_empty_networks;
  const
    _networks = [
      _network,
      _network_id
    ];
  _non_empty_networks =
    false;
  _found =
    false;
  for ( _net of _networks ) {
    _bytecode_retrieve =
      false;
    _break =
      false;
    if ( _net.length < 1 ) {
      _msg =
        `Empty value network '${_net}', ` +
        "skipping.";
      _msg_info(
        _msg);
    }
    else {
      _bytecode_retrieve =
      true;
    }
    if ( _bytecode_retrieve ) {
      _non_empty_networks =
        true;
      _msg =
        "Getting bytecode for network " +
        `'${_net}'.`;
      _msg_info(
        _msg);
      const
        _version_check_args = [
          _version,
          _app,            // app
          _contract,
          "",            // address
          _net,
          _user_defined,
          _deployments,
          "",            // config file
          _configuration_format
        ];
      try {
        _version =
          await _version_check.apply(
            null,
            _version_check_args);
      }
      catch(
        _error) {
        _msg =
          "Error running '_version_check' " +
          "with arguments:";
        _msg_error(
          _msg,
          0);
        _echo2(
          _version_check_args);
        _echo2(
          _error);
        throw _error;
      }
      _msg =
        `Checked version '${_version}'.`;
      _msg_info(
        _msg);
      _bytecode_path =
        _path_join([
          _deployments,
          _contract,
          _net,
          _version,
          `${_contract}.bin`
        ]);
      _msg =
        `Checking file '${_abi_path}'.`;
      _msg_info(
        _msg);
      if ( _file_exists(
             _bytecode_path) ) {
        _found =
          true;
        _break =
          true;
      }
      else {
        _msg =
          `Bytecode at path '${_bytecode_path}' ` +
          `not found.`;
        _msg_info(
          _msg);
      }
    }
    if ( _break ) {
      _msg =
        "File found, breaking loop.";
      _msg_info(
        _msg);
      break;
    }
  }
  if ( ! _found &&
       _non_empty_networks ) {
    _msg =
      `No bytecode for network '${_network}' deployment ` +
      `of contract '${_contract}' ` +
      `found at path '${_deployments}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  const
    _contract_bytecode =
      _bytecode_path;
  const
    _contract_bytecode_type =
      typeof(
        _contract_bytecode);
  if ( _contract_bytecode == "" ||
       _contract_bytecode_type === "undefined" ||
       _contract_bytecode == null ) {
    _msg =
      `No '${_contract}' version '${_version}' ` +
      `contract deployment specified for network ` +
      `'${_network}' for directory at path `+
      `'${_deployments}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  _msg =
    `Got bytecode: '${_contract_bytecode}'.`;
  _msg_info(
    _msg);
  return _contract_bytecode;
}

async function
  _evm_contract_deployment_bytecode(
    _target_networks,
    _network_ids,
    _networks_all,
    _target_app,
    _target_contract,
    _contract_version,
    _user_defined,
    _configuration_format,
    _deployments_dir) {
  let
    _args,
    _contract_bytecode,
    _deployments_dir_get,
    _network,
    _network_check_args,
    _target_network,
    _target_network_id,
    _user_deployments_dir,
    _system_deployments_dir,
    _msg;
  const
    _contracts_bytecodes =
      [];
  const
    _contract_bytecode_get_args =
      [];
  _user_defined =
    _user_defined_check(
      _user_defined);
  const
    _deployments_dir_type =
      typeof(
        _deployments_dir);
  _deployments_dir_get =
    false;
  if ( _deployments_dir_type === "undefined" ) {
    _msg =
      "Deployments directory undefined, getting.";
    _msg_info(
      _msg);
    _deployments_dir_get =
      true;
  }
  else if ( _deployments_dir_type === "string" ) {
    if ( _deployments_dir.length < 1 ) {
      _msg =
        "Deployments directory not set, getting.";
      _msg_info(
        _msg);
      _deployments_dir_get =
        true;
    }
  }
  if ( _deployments_dir_get ) {
    const
      _evm_contract_deployments_dir_args = [
        _target_app,
        _user_defined
      ];
    try {
      _deployments_dir =
        await _evm_contract_deployments_dir.apply(
          null,
          _evm_contract_deployments_dir_args);
    }
    catch(
      _error) {
      _msg =
        "Error while retrieving system deployments " +
        "directory location for auto-detection.";
      _msg_error(
        _msg,
        0);
      _msg_error(
        _error,
        0);
      throw _error;
    }
  }
  if ( _user_defined == "n" ) {
    if ( _target_app == "" ) {
      _msg =
        "A target application needs to " +
        "be specified with option '-a' " +
        "if not enabling user-defined " +
        "deployments with '-u' and " +
        "specifying a deployments directory " +
        "path with '-d'.";
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
    _system_deployments_dir =
      await _evm_contract_deployments_dir(
        _target_app,
        _user_defined);
    if ( _deployments_dir != _system_deployments_dir ) {
      _msg =
        "To set a custom deployments directory path " +
        "you need to enable the user-defined " +
        "deployments switch with '-u'." +
      _msg_error(
        _msg,
        0);
      throw _msg;
    }
  }
  else if ( _user_defined == "y" ) {
    if ( _target_app != "" ) {
      _user_deployments_dir =
        await _evm_contract_deployments_dir(
          _target_app,
          _user_defined);
    }
    if ( _deployments_dir != _user_deployments_dir ) {
      _msg =
        "Using custom deployments directory " +
        `path '${_deployments_dir}'.`;
      _msg_info(
        _msg);
    }
    else {
      _user_deployments_check(
        _target_app,
        _deployments_dir);
    }
  }
  else {
    _msg =
      "The 'user-defined' switch argument " +
      `can be 'y' or 'n', current value '${_user_defined}'.`;
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  if ( _networks_all == "y" ) {
    _msg =
      "Selecting all networks.";
    _msg_info(
      _msg);
    _target_networks =
      await _evm_contract_deployment_networks(
        `${_deployments_dir}/${_target_contract}`,
        _networks_all);
  }
  for ( _network of _target_networks ) {
    // _msg =
    //   "Info arguments for " +
    //   `network '${_network}'.`;
    // _msg_info(
    //   _msg);
    if ( _network.length < 1 ) {
      _msg =
        "Empty network, skipping.";
      _msg_info(
        _msg);
    }
    else {
      _target_network_id =
        "";
      _network_check_args = [
        _deployments_dir,
        _target_contract,
        _network,
        _target_network_id
      ];
      await _network_check.apply(
        null,
        _network_check_args);
      _contract_bytecode_get_args.push( [
        _deployments_dir,
        _target_app,
        _target_contract,
        _network,
        _target_network_id,
        _contract_version,
        _configuration_format,
        _user_defined
      ] );
    }
  }
  for ( _network of _network_ids ) {
    if ( _network.length < 1 ) {
      _msg =
        "Empty network, skipping.";
      _msg_info(
        _msg);
    }
    else {
      _target_network =
        "";
      _network_check_args = [
        _deployments_dir,
        _target_contract,
        _target_network,
        _network
      ];
      await _network_check.apply(
        null,
        _network_check_args);
      _contract_bytecode_get_args.push( [
        _deployments_dir,
        _target_app,
        _target_contract,
        _target_network,
        _network,
        _contract_version,
        _configuration_format,
        _user_defined
      ] );
    }
  }
  for ( _args of _contract_bytecode_get_args ) {
    try {
      _contract_bytecode =
        await _contract_bytecode_get.apply(
          null,
          _args);
    }
    catch(
      _error) {
      _msg =
        "Error running '_contract_bytecode_get' " +
        "with parameters:";
      _msg_error(
        _msg,
        0);
      _echo2(
        _args);
      _echo2(
        _error);
      throw _error;
    }
    _contracts_bytecodes.push(
      _contract_bytecode);
  }
  return _contracts_bytecodes;
}

export {
  _contract_version_auto_detect,
  _deployments_dir_auto_detect,
  _evm_contract_deployment_bytecode,
  _networks_all_auto_detect,
  _target_app_auto_detect
};

// module.exports = {
//   _contract_version_auto_detect:
//     _contract_version_auto_detect,
//   _deployments_dir_auto_detect:
//     _deployments_dir_auto_detect,
//   _evm_contract_deployment_bytecode:
//     _evm_contract_deployment_bytecode,
//   _networks_all_auto_detect:
//     _networks_all_auto_detect,
//   _target_app_auto_detect:
//     _target_app_auto_detect
// };
