#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-contract-deployments-dir
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash_module =
    await import(
      "libcrash-js");
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash_module._homedir_get;
/* global
     _lib_get */
const
  _lib_get =
    _libcrash_module._lib_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash_module._msg_error;
const
  _libevm_contract_deployment_module =
    await import(
      "./libevm-contract-deployment");
/* global
     _app_check */
const
  _app_check =
    _libevm_contract_deployment_module._app_check;
/* global
     _user_level_check */
const
  _user_level_check =
    _libevm_contract_deployment_module._user_level_check;

async function
  _default_deployments_dir_get(
    _app,
    _type) {
  _app =
    _app_check(
      _app);
  if ( typeof(
         _type) == "undefined" ||
       _type == "" ) {
    _type =
      "system";
  }
  let
    _conf_dir;
  if ( _type == "system" ) {
    _conf_dir =
      await _lib_get();
  }
  else if ( _type == "user" ) {
    const
      _homedir =
        _homedir_get();
    _conf_dir =
      `${_homedir}/.config`;
  }
  return `${_conf_dir}/${_app}/deployments`;
}

async function
  _evm_contract_deployments_dir(
    _app,
    _user_level) {
  let
    _deployment_type,
    _deployments;
  _app =
    _app_check(
      _app);
  _user_level =
    _user_level_check(
      _user_level);
  if ( _user_level == "n" ) {
    _deployment_type =
      "system";
  }
  else if ( _user_level == "y" ) {
    _deployment_type =
      "user";
  }
  else {
    const
      _msg =
        "User level argument must be " +
        "can be 'y' or 'n'.";
    _msg_error(
      _msg,
      0);
    throw _msg;
  }
  try {
    _deployments =
      await _default_deployments_dir_get(
        _app,
        _deployment_type);
  }
  catch(
    _error) {
    _msg =
      "Error running '_default_deployments_dir_get' " +
      "with arguments:";
    _msg_error(
      _msg,
      0);
    throw _error;
  }
  return _deployments;
}

export {
  _default_deployments_dir_get,
  _evm_contract_deployments_dir,
};

// module.exports = {
//   _default_deployments_dir_get:
//     _default_deployments_dir_get,
//   _evm_contract_deployments_dir:
//     _evm_contract_deployments_dir,
// };
