#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     address-check
 *     ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _process_exit */
const
  _process_exit =
    _libcrash._process_exit;
const
  { ethers } =
    require(
      "ethers");
const
  _ethers =
    ethers;
/* global
     _address_check */
const
  _address_check =
    _ethers.isAddress;

function
  _global_variables() {
  app_name =
    "address-check";
  /* global
       target_address:
         writable */
  target_address =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function
  _config_show() {
  let
    _line;
  const
    _argv =
      _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      `${_program} configuration:`,
      `         Target address: ${target_address}`,
      ];
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit) {
  let
    _display_fun,
    _line;
  const
    _argv =
      _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      "Checks whether an address is valid.",
      "",
      "usage:",
      `  ${_program}`,
      "    <target-address>",
      "    [options]",
      "",
      "args:",
      "  <target-address>                 Address to check.",
      "",
      "  options:",
      "    -v --verbose                   Extended output.",
      "    -h --help                      This help."
    ];
  for (_line of _text) {
    _msg_info(
      _line);
  }
  _process_exit(
    _exit);
}

function
  _overrides_set() {
  true;
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        target_address =
          _value;
      }
      else if ( _value == "-v" ||
           _value == "--verbose" ) {
        quiet =
          "n";
      }
      else if ( _value == "-h" ||
           _value == "--help" ) {
        quiet =
          "n";
        _usage(
          0);
      }
    }
  );
  if ( target_address == "" ) {
    const
      _msg =
        "No target address specified.";
    _msg_error(
      _msg,
      0);
    quiet =
      "n";
    _usage(
      1);
  }
}
async function
  _address_check_cmdline(
    _app_opts) {
  let
    _is_address,
    _msg;
  try {
    _is_address = 
      await _address_check.apply(
        null,
        _app_opts);
    const
      _return_type =
        typeof(
          _is_address);
    if ( _return_type == "undefined" ) {
      _msg =
        "Big error.";
      _msg_error(
        _msg,
        1);
    }
    else {
      if ( ! _is_address ) {
        _msg =
          `Address '${target_address}' not is valid.'`;
        throw _msg;
      }
    }
  } catch (
      _error) {
    _msg_error(
      _error,
      1);
  }
}

if ( _cmdline_check(
       "address-check") ||
     _cmdline_check(
       "ethereum-address-validate") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    target_address,
  ];
  _address_check_cmdline(
    app_opts);
}

module.exports = {
  _address_check:
    _address_check
};
