#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _require */
const
  _require =
    _libcrash._require;
const
  _ethers_module =
    await _require(
      "ethers");
const
  _ethers =
    _ethers_module.ethers;
/* global
     _wei_to_ether */
const
  _wei_to_ether =
    _ethers.formatEther;
const
  _evm_transactions_tools_module =
    await _require(
      "evm-transactions-tools");
/* global
     _transaction_get */
const
  _transaction_get =
    _evm_transactions_tools_module._transaction_get;
/* global
     _transaction_receipt_get */
const
  _transaction_receipt_get =
    _evm_transactions_tools_module._transaction_receipt_get;
const
  _deployer_get_module =
    await import(
      './deployer-get');
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;

function
  _global_variables() {
  _set(
    "app",
    "name",
    "bytecode-creation-get");
  /* global
       wallet_seed:
         writable */
  _set(
    "wallet",
    "seed",
    "");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       api_key_path:
         writable */
  _set(
    "api_key",
    "path",
    "");
  /* global
       chain_id:
         writable */
  _set(
    "chain",
    "id",
    "");
  /* global
       chain_name:
         writable */
  _set(
    "chain",
    "name",
    "");
  /* global
       target_network:
         writable */
  _set(
    "target",
    "network",
    "");
  /* global
       contract_address:
         writable */
  _set(
    "contract",
    "address",
    "");
  /* global
       transaction_deployment:
         writable */
  _set(
    "transaction",
    "deployment",
    "");
  /* global
       contract_bytecode_path:
         writable */
  _set(
    "contract_bytecode",
    "path",
    "");
  /* global
       quiet:
         writable */
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
}

function
  _delay(
    _time) {
  return new Promise(resolve => setTimeout(resolve, _time));
}

async function
  _bytecode_creation_get(
    _wallet_seed,
    _retries_max,
    _api_key_path,
    _chain_id,
    _chain_name,
    _target_network,
    _contract_address,
    _transaction_deployment,
    _bytecode_path) {
  let
    _attempt,
    _bytecode,
    _deployer,
    _deployer_get_opts,
    _transaction_get_opts,
    _tx,
    _wallet_password; //,
    // _receipt,
    // _transaction_receipt_get_opts,
  if ( _bytecode_path == undefined ) {
    _bytecode_path =
      "";
  }
  if ( _contract_address == undefined ) {
    _contract_address =
      "";
  }
  _contract_address =
    _contract_address.toLowerCase();
  _attempt =
    1;
  _wallet_password =
    "";
  _output_path =
    "";
  _transaction_get_opts = [
    _retries_max,
    _wallet_seed,
    _wallet_password,
    _chain_id,
    _chain_name,
    _target_network,
    _api_key_path,
    _output_path,
    _transaction_deployment
  ];
  _transaction_receipt_get_opts = [
    _retries_max,
    _wallet_seed,
    _wallet_password,
    _chain_id,
    _chain_name,
    _target_network,
    _api_key_path,
    _output_path,
    _transaction_deployment
  ];
  while ( _attempt <= _retries_max ) {
    try {
      _tx =
        await _transaction_get.apply(
          null,
          _transaction_get_opts);
      if ( _tx == undefined ) {
        throw { "error": {
                  "message":
                    "Undefined transaction." } };
      }
      else if ( _tx != undefined ) {
        _bytecode =
          _tx.data;
	_file_write(
          _bytecode_path,
          _bytecode);
      }
      break
    } catch (
        _error) {
      _error_display(
        _error);
      // TODO: Do not break the loop
      //       only on network errors.
      _attempt =
        _attempt + 1;
      _msg_error(
        "Increasing retry and waiting 3 seconds.",
        0);
      await _delay(
        3000);
    }
  }
  if ( _attempt > _retries_max ) {
    throw "Maximum number of retries reached.";
  }
  return _bytecode;
}

function
  _config_show() {
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          "1"]);
  const
    _text = [
      `${_program} configuration:`,
      `             Wallet seed: ${wallet_seed}`,
      `             Max retries: ${retries_max}`,
      `            API Key path: ${api_key_path}`,
      `                Chain ID: ${chain_id}`,
      `              Chain Name: ${chain_name}`,
      `          Target network: ${target_network}`,
      `        Contract address: ${contract_address}`,
      `  Deployment transaction: ${transaction_deployment}`,
    ];
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "",
      "Returns the creation bytecode for a contract given its deployment transaction hash.",
      "",
      "Usage:",
      `  ${_program}`,
      "    <quiet>",
      "    <wallet-seed>",
      "    <retries-max>",
      "    <api-key-path>",
      "    <chain-id>",
      "    <chain-name>",
      "    <target-network>",
      "    <contract-address>",
      "    <transaction-deployment>",
      "    <contract-bytecode-path>",
      "",
      "Args:",
      "  <quiet>                          Can be 'y' or 'n'",
      "                                   Default: y",
      "  <wallet-seed>                    Path of the file containing",
      "                                   the seed phrase.",
      "  <retries-max>                    Maximum number of retries before",
      "                                   failing.",
      "  <api-key-path>                   Path of the API key for the",
      "                                   contract ABI provider service",
      "  <chain-id>                       Chain ID for the network.",
      "  <chain-name>                     Name for the network.",
      "  <target-network>                 Network on which the contract",
      "                                   resides.",
      "  <contract-address>               Address of the contract",
      "  <transaction-deployment>         Contract deployment transaction.",
      "  <contract-bytecode-path>         Where to save contract bytecode.",
      "",
      "  Options:",
      "    -h                             This help.",
      ""
    ];
  for (_line of _text) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _overrides_set() {
  _override_set(
    "retries",
    "max",
    10);
}

function
  _cmdline_parse() {
  let
    _error,
    _msg;
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
  _argv.forEach(
    function (
      _value,
      _index) {
      if ( _index == 2 ) {
        _global[
          "quiet"] =
          _value;
      }
      if ( _index == 3 ) {
        _set(
          "wallet",
          "seed",
          _value);
      }
      if ( _index == 4 ) {
        _set(
          "retries",
          "max",
          _value);
      }
      if ( _index == 5 ) {
        _set(
          "api_key",
          "path",
          _value);
      }
      if ( _index == 6 ) {
        _set(
          "chain",
          "id",
          _value);
      }
      if ( _index == 7 ) {
        _set(
          "chain",
          "name",
          _value);
      }
      if ( _index == 8 ) {
        _set(
          "target",
          "network",
          _value);
      }
      if ( _index == 9 ) {
        _set(
          "contract",
          "address",
          _value);
      }
      if ( _index == 10 ) {
        _set(
          "transaction",
          "deployment",
          _value);
      }
      if ( _index == 11 ) {
        _set(
          "contract_bytecode",
          "path",
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _global[
          "quiet"] =
          "n";
        _usage(
          0);
      }
    }
  );
  _error =
    false;
  if ( transaction_deployment == "" ) {
    _msg =
      "No deployment transaction specified.";
    _error =
      true;
  }
  if ( contract_bytecode_path == "" ) {
    _msg =
      "No contract bytecode path specified.";
    _error =
      true;
  }
  if ( _error ) {
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _usage(
      1);
  }
}
async function
  _bytecode_creation_get_cmdline(
    _app_opts) {
  let
    _bytecode,
    _msg;
  try {
    _bytecode = 
      await _bytecode_creation_get.apply(
        null,
        _app_opts);
    if ( _bytecode != undefined ) {
      _msg =
        `Bytecode has length '${_bytecode.length}'`;
      _msg_info(
        _msg);
      // _printf(
      //   _bytecode.toString());
    }
    else {
      _msg =
        "It has not been possible to retrieve " +
        "the bytecode from the transaction.";
      throw _msg;
    }
  } catch (
      _error) {
    _msg_error(
      _error,
      1);
  }
}

if ( _cmdline_check(
       "bytecode-creation-get") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    retries_max,
    api_key_path,
    chain_id,
    chain_name,
    target_network,
    contract_address,
    transaction_deployment,
    contract_bytecode_path
  ];
  _bytecode_creation_get_cmdline(
    app_opts);
}

export {
  _bytecode_creation_get
};

// module.exports = {
//   _bytecode_creation_get:
//     _bytecode_creation_get
// };
