#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error
/* global
     _printf */
const
  _printf =
    _libcrash._printf
const
  _contract_get_module =
    require(
      './contract-get');
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get
const
  _evm_wallet_module =
    require(
      "evm-wallet");
/* global
     _provider_get */
const
  _provider_get =
    _evm_wallet_module._provider_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "bytecode-runtime-get";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       api_key_path:
         writable */
  api_key_path =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       contract_address:
         writable */
  contract_address =
    "";
  /* global
       contract_abi_path:
         writable */
  contract_abi_path =
    "";
  /* global
       contract_bytecode_path:
         writable */
  contract_bytecode_path =
    "";
  // contract_compiler_output_path =
  //   "";
  // contract_method =
  //   "";
  // method_args =
  //   [];
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function
  _delay(
    _time) {
  return new Promise(resolve => setTimeout(resolve, _time));
}

function
  _msg_info_contract_obtained(
    _contract) {
  const
    _msg =
      `Contract '${_contract}' obtained.`;
  _msg_info(
    _msg);
}

function
  _msg_info_method_obtained(
    _method) {
  const
    _msg =
      "Method obtained.";
  _msg_info(
    _msg);
}

async function
  _bytecode_runtime_get(
    _wallet_seed,
    _retries_max,
    _api_key_path,
    _target_network,
    _contract_address,
    _contract_bytecode_path
    ) {
  let
    _api_key,
    _code,
    _msg,
    _network_provider,
    _passed,
    _wallet_password;
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
  }
  else if ( _api_key_path == "" ) {
    _api_key =
      ""
  }
  _retry =
    1;
  _wallet_password =
    "";
  _passed = 
    false;
  while ( _retry <= _retries_max &&
          _passed == false ) {
    try {
      _network_provider =
        await _provider_get(
          _target_network,
          _api_key);
      _code =
        await _network_provider.getCode(
          _contract_address);
      if ( _code != undefined ) {
        _msg =
          `Bytecode length: ${_code.length}`;
        _msg_info(
          _msg);
        _file_write(
          _contract_bytecode_path,
          _code);
        _passed =
          true;
      }
      else if ( _code == undefined ) {
        _msg =
          "Code not retrieved."
        throw {"error": {
                 "message":
                   _msg } };
      }
    } catch (
        _error) {
      _error_display(
        _error);
      _retry =
        _retry + 1;
      _msg =
        "Increasing retry and waiting 3 seconds.";
      _msg_error(
        _msg,
        0);
      await _delay(
        3000);
    }
  }
  if ( _retry > _retries_max ) {
    throw "Maximum number of retries reached.";
  }
  return _code;
}

function
  _config_show() {
  let
    _line,
    _method_args;
  const
    _text = [
    "  bytecode-runtime-get configuration:",
    `        Contract address: ${contract_address}`,
    `       Contract bytecode: ${contract_bytecode_path}`,
    `             Max retries: ${retries_max}`,
    `   Credentials options:`,
    `             Wallet seed: ${wallet_seed}`,
    `            API Key path: ${api_key_path}`,
    `       Network options:`,
    `          Target network: ${target_network}`,
  ];
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit) {
  let
    _line,
    _text;
  _text = [
    "Retrieves the runtime bytecode for an address.",
    "",
    "Usage:",
    "  bytecode-runtime-get",
    "    <quiet>",
    "    <wallet-seed>",
    "    <retries-max>",
    "    <api-key-path>",
    "    <target-network>",
    "    <contract-address>",
    "    <contract-bytecode_path>",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    `                                   Default: ${quiet}`,
    "  <wallet-seed>                    Path of the file containing",
    "                                   the seed phrase.",
    "  <retries-max>                    Maximum number of retries before",
    "                                   failing.",
    "  <api-key-path>                   Path of the API key for the",
    "                                   contract ABI provider service",
    "  <target-network>                 Network on which the contract",
    "                                   resides.",
    "  <contract-address>               Address of the contract",
    "  <contract-bytecode-path>         Path in which to save",
    "                                   the runtime bytecode.",
    "",
    "  Options:",
    "    -h                             This help."
  ];
  for (_line of _text) {
    _msg_info(
      _line);
  }
  process.exit(
    _exit);
}

function
  _overrides_set() {
  if ( retries_max == "" ) {
    retries_max =
      100;
  }
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        retries_max =
          _value;
      }
      if ( _index == 5 ) {
        api_key_path =
          _value;
      }
      if ( _index == 6 ) {
        target_network =
          _value;
      }
      if ( _index == 7 ) {
        contract_address =
          _value;
      }
      if ( _index == 8 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage(
          0);
      }
    }
  );
  if ( contract_address == "" ) {
    _msg_error(
      "It is required to set a contract address.",
      0);
    quiet =
      "n";
    _usage(
      1);
  }
  if ( target_network == "" ) {
    _msg_error(
      "It is required to set a network.",
      0);
    quiet =
      "n";
    _usage(
      1);
  }
  if ( contract_bytecode_path == "" ) {
    _msg_error(
      "It is required to set a path in which to save the bytecode.",
      0);
    quiet =
      "n";
    _usage(
      1);
  }
}

async function
  _bytecode_runtime_get_cmdline(
    _app_opts) {
    let
      _code;
  try {
    _code = 
      await _bytecode_runtime_get.apply(
        null,
        _app_opts);
    if ( _code != undefined ) {
      _printf(
        typeof(
          _code));
      // _printf(
      //   _code.toString());
    }
    else {
      throw "Bytecode runtime retrieval failed."
    }
  } catch (_error) {
    _msg_error(
      _error,
      1);
  }
}

if ( _cmdline_check(
       "bytecode-runtime-get") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    retries_max,
    api_key_path,
    target_network,
    contract_address,
    contract_bytecode_path,
  ];
  _bytecode_runtime_get_cmdline(
    app_opts);
}

module.exports = {
  _bytecode_runtime_get:
    _bytecode_runtime_get
};

