#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ---------------------------------------------------------------
 *     bytecode-runtime-get
 *     ---------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ---------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _evm_wallet_module =
    await _require(
      "evm-wallet");
/* global
     _provider_get */
const
  _provider_get =
    _evm_wallet_module._provider_get;
const
  _contract_get_module =
    await import(
      './contract-get');
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "bytecode-runtime-get");
  /* global
       wallet_seed:
         writable */
  _set(
    "wallet",
    "seed",
    "");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       api_key_path:
         writable */
  _set(
    "api_key",
    "path",
    "");
  /* global
       target_network:
         writable */
  _set(
    "target",
    "network",
    "");
  /* global
       contract_address:
         writable */
  _set(
    "contract",
    "address",
    "");
  /* global
       contract_abi_path:
         writable */
  _set(
    "contract_abi",
    "path",
    "");
  /* global
       contract_bytecode_path:
         writable */
  _set(
    "contract_bytecode",
    "path",
    "");
  // contract_compiler_output_path =
  //   "";
  // contract_method =
  //   "";
  // method_args =
  //   [];
  /* global
       quiet:
         writable */
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
}

function
  _delay(
    _time) {
  return new Promise(resolve => setTimeout(resolve, _time));
}

function
  _msg_info_contract_obtained(
    _contract) {
  const
    _msg =
      `Contract '${_contract}' obtained.`;
  _msg_info(
    _msg);
}

function
  _msg_info_method_obtained(
    _method) {
  const
    _msg =
      "Method obtained.";
  _msg_info(
    _msg);
}

async function
  _bytecode_runtime_get(
    _wallet_seed,
    _retries_max,
    _api_key_path,
    _target_network,
    _contract_address,
    _contract_bytecode_path
    ) {
  let
    _api_key,
    _code,
    _msg,
    _network_provider,
    _passed,
    _wallet_password;
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
  }
  else if ( _api_key_path == "" ) {
    _api_key =
      ""
  }
  _retry =
    1;
  _wallet_password =
    "";
  _passed = 
    false;
  while ( _retry <= _retries_max &&
          _passed == false ) {
    try {
      _network_provider =
        await _provider_get(
          _target_network,
          _api_key);
      _code =
        await _network_provider.getCode(
          _contract_address);
      if ( _code != undefined ) {
        _msg =
          `Bytecode length: ${_code.length}`;
        _msg_info(
          _msg);
        _file_write(
          _contract_bytecode_path,
          _code);
        _passed =
          true;
      }
      else if ( _code == undefined ) {
        _msg =
          "Code not retrieved."
        throw {"error": {
                 "message":
                   _msg } };
      }
    } catch (
        _error) {
      _error_display(
        _error);
      _retry =
        _retry + 1;
      _msg =
        "Increasing retry and waiting 3 seconds.";
      _msg_error(
        _msg,
        0);
      await _delay(
        3000);
    }
  }
  if ( _retry > _retries_max ) {
    throw "Maximum number of retries reached.";
  }
  return _code;
}

function
  _config_show() {
  let
    _line,
    _method_args;
  const
    _program =
      _basename(
        _argv[
          0]);
  const
    _text = [
    `  ${_program} configuration:`,
    `        Contract address: ${contract_address}`,
    `       Contract bytecode: ${contract_bytecode_path}`,
    `             Max retries: ${retries_max}`,
    `   Credentials options:`,
    `             Wallet seed: ${wallet_seed}`,
    `            API Key path: ${api_key_path}`,
    `       Network options:`,
    `          Target network: ${target_network}`,
  ];
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  const
    _program =
      _basename(
        _argv[
          0]);
  _text = [
    "Retrieves the runtime bytecode for an address.",
    "",
    "Usage:",
    `  ${_program}`,
    "    <quiet>",
    "    <wallet-seed>",
    "    <retries-max>",
    "    <api-key-path>",
    "    <target-network>",
    "    <contract-address>",
    "    <contract-bytecode_path>",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    `                                   Default: ${quiet}`,
    "  <wallet-seed>                    Path of the file containing",
    "                                   the seed phrase.",
    "  <retries-max>                    Maximum number of retries before",
    "                                   failing.",
    `                                   Default: ${retries_max}`,
    "  <api-key-path>                   Path of the API key for the",
    "                                   contract ABI provider service",
    "  <target-network>                 Network on which the contract",
    "                                   resides.",
    "  <contract-address>               Address of the contract",
    "  <contract-bytecode-path>         Path in which to save",
    "                                   the runtime bytecode.",
    "",
    "  Options:",
    "    -h                             This help."
  ];
  for (_line of _text) {
    _msg_info(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _overrides_set() {
  _override_set(
    "retries",
    "max",
    100);
}

function
  _cmdline_parse() {
  let
   _msg;
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
  _argv.forEach(
    function (
      _value,
      _index) {
      if ( _index == 2 ) {
        _global[
          "quiet"] =
          _value;
      }
      if ( _index == 3 ) {
        _set(
          "wallet",
          "seed",
          _value);
      }
      if ( _index == 4 ) {
        _set(
          "retries",
          "max",
          _value);
      }
      if ( _index == 5 ) {
        _set(
          "api_key",
          "path",
          _value);
      }
      if ( _index == 6 ) {
        _set(
          "target",
          "network",
          _value);
      }
      if ( _index == 7 ) {
        _set(
          "contract",
          "address",
          _value);
      }
      if ( _index == 8 ) {
        _set(
          "contract_bytecode",
          "path",
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage(
          0);
      }
    }
  );
  const
    _contract_address =
      _get(
        "contract",
        "address");
  if ( _contract_address == "" ) {
    _msg =
      "It is required to set a contract address.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _overrides_set();
    _usage(
      1);
  }
  const
    _target_network =
      _get(
        "target",
        "network");
  if ( _target_network == "" ) {
    _msg =
      "It is required to set a network.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _usage(
      1);
  }
  const
    _contract_bytecode_path =
      _get(
        "contract_bytecode",
        "path");
  if ( _contract_bytecode_path == "" ) {
    _msg =
      "It is required to set a path " +
      "in which to save the bytecode.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _usage(
      1);
  }
}

async function
  _bytecode_runtime_get_cmdline(
    _app_opts) {
  let
    _code;
  try {
    _code = 
      await _bytecode_runtime_get.apply(
        null,
        _app_opts);
    if ( _code != undefined ) {
      await _printf(
        typeof(
          _code));
      // _printf(
      //   _code.toString());
    }
    else {
      throw "Bytecode runtime retrieval failed."
    }
  } catch (_error) {
    _msg_error(
      _error,
      1);
  }
}

if ( await _cmdline_check(
       "bytecode-runtime-get") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    retries_max,
    api_key_path,
    target_network,
    contract_address,
    contract_bytecode_path,
  ];
  _bytecode_runtime_get_cmdline(
    app_opts);
}

export {
  _bytecode_runtime_get
};

// module.exports = {
//   _bytecode_runtime_get:
//     _bytecode_runtime_get
// };

