#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _require */
const
  _require =
    _libcrash._require;
const
  _ethers_module =
    await _require(
      "ethers");
const
  _ethers =
    _ethers_module.ethers;
/* global
     _wei_to_ether */
const
  _wei_to_ether =
    _ethers.formatEther;
const
  _evm_transactions_tools_module =
    await _require(
      "evm-transactions-tools");
/* global
     _transaction_get */
const
  _transaction_get =
    _evm_transactions_tools_module._transaction_get;
/* global
     _transaction_receipt_get */
const
  _transaction_receipt_get =
    _evm_transactions_tools_module._transaction_receipt_get;
const
  _deployer_get_module =
    require(
      './deployer-get');
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;

function
  _global_variables() {
  app_name =
    "bytecode-creation-get";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       api_key_path:
         writable */
  api_key_path =
    "";
  /* global
       chain_id:
         writable */
  chain_id =
    "";
  /* global
       chain_name:
         writable */
  chain_name =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       contract_address:
         writable */
  contract_address =
    "";
  /* global
       transaction_deployment:
         writable */
  transaction_deployment =
    "";
  /* global
       contract_bytecode_path:
         writable */
  contract_bytecode_path =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function
  _delay(
    _time) {
  return new Promise(resolve => setTimeout(resolve, _time));
}

async function
  _bytecode_creation_get(
    _wallet_seed,
    _retries_max,
    _api_key_path,
    _chain_id,
    _chain_name,
    _target_network,
    _contract_address,
    _transaction_deployment,
    _bytecode_path) {
  let
    _attempt,
    _bytecode,
    _deployer,
    _deployer_get_opts,
    _transaction_get_opts,
    _tx,
    _wallet_password; //,
    // _receipt,
    // _transaction_receipt_get_opts,
  if ( _bytecode_path == undefined ) {
    _bytecode_path =
      "";
  }
  if ( _contract_address == undefined ) {
    _contract_address =
      "";
  }
  _contract_address =
    _contract_address.toLowerCase();
  _attempt =
    1;
  _wallet_password =
    "";
  _output_path =
    "";
  _transaction_get_opts = [
    _retries_max,
    _wallet_seed,
    _wallet_password,
    _chain_id,
    _chain_name,
    _target_network,
    _api_key_path,
    _output_path,
    _transaction_deployment
  ];
  _transaction_receipt_get_opts = [
    _retries_max,
    _wallet_seed,
    _wallet_password,
    _chain_id,
    _chain_name,
    _target_network,
    _api_key_path,
    _output_path,
    _transaction_deployment
  ];
  while ( _attempt <= _retries_max ) {
    try {
      _tx =
        await _transaction_get.apply(
          null,
          _transaction_get_opts);
      if ( _tx == undefined ) {
        throw { "error": {
                  "message":
                    "Undefined transaction." } };
      }
      else if ( _tx != undefined ) {
        _bytecode =
          _tx.data;
	_file_write(
          _bytecode_path,
          _bytecode);
      }
      break
    } catch (
        _error) {
      _error_display(
        _error);
      // TODO: Do not break the loop
      //       only on network errors.
      _attempt =
        _attempt + 1;
      _msg_error(
        "Increasing retry and waiting 3 seconds.",
        0);
      await _delay(
        3000);
    }
  }
  if ( _attempt > _retries_max ) {
    throw "Maximum number of retries reached.";
  }
  return _bytecode;
}

function
  _config_show() {
  let
    _line,
    _method_args,
    _text;
  _text =
    [];
  _text.push(
    "bytecode-creation-get configuration:");
  _text.push(
    "             Wallet seed: {wallet_seed}".replace(
      "{wallet_seed}",
      wallet_seed));
  _text.push(
    "             Max retries: {retries_max}".replace(
      "{retries_max}",
      retries_max));
  _text.push(
    "            API Key path: {api_key_path}".replace(
      "{api_key_path}",
      api_key_path));
  _text.push(
    "                Chain ID: {chain_id}".replace(
      "{chain_id}",
      chain_id));
  _text.push(
    "              Chain Name: {chain_name}".replace(
      "{chain_name}",
      chain_name));
  _text.push(
    "          Target network: {target_network}".replace(
      "{target_network}",
      target_network));
  _text.push(
    "        Contract address: {contract_address}".replace(
      "{contract_address}",
      contract_address));
  _text.push(
    "  Deployment transaction: {transaction_deployment}".replace(
      "{transaction_deployment}",
      transaction_deployment));
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _display_fun,
    _line,
    _text;
  _text = [
    "Returns the creation bytecode for a contract given its deployment transaction hash.",
    "",
    "Usage:",
    "  bytecode-creation-get",
    "    <quiet>",
    "    <wallet_seed>",
    "    <retries_max>",
    "    <api_key_path>",
    "    <chain_id>",
    "    <chain_name>",
    "    <target_network>",
    "    <contract_address>",
    "    <transaction_deployment>",
    "    <contract_bytecode_path>",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    "                                   Default: y",
    "  <wallet_seed>                    Path of the file containing",
    "                                   the seed phrase.",
    "  <retries_max>                    Maximum number of retries before",
    "                                   failing.",
    "  <api_key_path>                   Path of the API key for the",
    "                                   contract ABI provider service",
    "  <chain_id>                       Chain ID for the network.",
    "  <chain_name>                     Name for the network.",
    "  <target_network>                 Network on which the contract",
    "                                   resides.",
    "  <contract_address>               Address of the contract",
    "  <transaction_deployment>         Contract deployment transaction.",
    "  <contract_bytecode_path>         Where to save contract bytecode.",
    "",
    "  Options:",
    "    -h                             This help."
  ];
  for (_line of _text) {
    _msg_info(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _overrides_set() {
  _override_set(
    "retries",
    "max",
    10);
}

function
  _cmdline_parse() {
  let
    _error,
    _msg;
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        retries_max =
          _value;
      }
      if ( _index == 5 ) {
        api_key_path =
          _value;
      }
      if ( _index == 6 ) {
        chain_id =
          _value;
      }
      if ( _index == 7 ) {
        chain_name =
          _value;
      }
      if ( _index == 8 ) {
        target_network =
          _value;
      }
      if ( _index == 9 ) {
        contract_address =
          _value;
      }
      if ( _index == 10 ) {
        transaction_deployment =
          _value;
      }
      if ( _index == 11 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        quiet =
          "n";
        _usage(
          0);
      }
    }
  );
  _error =
    false;
  if ( transaction_deployment == "" ) {
    _msg =
      "No deployment transaction specified.";
    _error =
      true;
  }
  if ( contract_bytecode_path == "" ) {
    _msg =
      "No contract bytecode path specified.";
    _error =
      true;
  }
  if ( _error ) {
    _msg_error(
      _msg,
      0);
    quiet =
      "n";
    _usage(
      1);
  }
}
async function
  _bytecode_creation_get_cmdline(
    _app_opts) {
  let
    _bytecode,
    _msg;
  try {
    _bytecode = 
      await _bytecode_creation_get.apply(
        null,
        _app_opts);
    if ( _bytecode != undefined ) {
      _msg_info(
        `Bytecode has length '${_bytecode.length}'`);
      // _printf(
      //   _bytecode.toString());
    }
    else {
      _msg =
        "It has not been possible to retrieve " +
	"the bytecode from the transaction.";
      throw _msg;
    }
  } catch (
      _error) {
    _msg_error(
      _error,
      1);
  }
}

if ( _cmdline_check(
       "bytecode-creation-get") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    retries_max,
    api_key_path,
    chain_id,
    chain_name,
    target_network,
    contract_address,
    transaction_deployment,
    contract_bytecode_path
  ];
  _bytecode_creation_get_cmdline(
    app_opts);
}

module.exports = {
  _bytecode_creation_get:
    _bytecode_creation_get
};
