#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _json_read */
const
  _json_read =
    _libcrash._json_read;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _require */
const
  _require =
    _libcrash._require;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
const
  _ethers =
    _ethers_module.ethers;
/* global
     _contract_factory */
const
  _contract_factory =
    _ethers.ContractFactory;
/* global
     _base_contract */
const
  _base_contract =
    _ethers.BaseContract;
const
  _evm_wallet_module =
    await _require(
      "evm-wallet");
/* global
     _wallet_get */
const
  _wallet_get =
    _evm_wallet_module._wallet_get;
/* global
     _provider_get */
const
  _provider_get =
    _evm_wallet_module._provider_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "contract-get"
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       wallet_password_path:
         writable */
  wallet_password_path =
    "";
  /* global
       contract_address:
         writable */
  contract_address =
    "";
  /* global
       contract_abi_path:
         writable */
  contract_abi_path =
    "";
  /* global
       contract_bytecode_path:
         writable */
  contract_bytecode_path =
    "";
  /* global
       contract_compiler_output_path:
         writable */
  contract_compiler_output_path =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key_path:
         writable */
  api_key_path =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}

function
  _msg_error_no_input_data() {
  const
    _text = [
      "You need to provide either",
      "the bytecode or the data"
    ];
  const
    _msg =
      _text.join(
        " ");
  _msg_error(
    _msg,
    1);
}

function
  _msg_info_wallet_selected(
    _wallet) {
  const
    _msg =
      `Wallet is '${_wallet}'.`;
  _msg_info(
    _msg);
}

async function
  _contract_get_abi(
    _wallet,
    _contract_address,
    _contract_abi_path) {
  const
    _contract_abi =
      _json_read(
        _contract_abi_path);
  const
    _contract = new
      _base_contract(
        _contract_address,
        _contract_abi,
        runner =
          _wallet);
  return _contract;
}

async function
  _contract_get_bytecode(
    _wallet,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path) {
  let
    _contract,
    _contract_abi,
    _contract_bytecode,
    _msg;
  if ( _contract_abi_path == "" ) {
    _contract_abi = [];
  }
  else if ( _contract_abi_path != "" ) {
    _contract_abi =
      _json_read(
        _contract_abi_path);
  }
  if ( _contract_bytecode_path != "" ) {
    _contract_bytecode =
      _file_read(
        _contract_bytecode_path);
  }
  const
    _factory =
      new _contract_factory(
        _contract_abi,
        _contract_bytecode,
        _wallet);
  if ( _contract_address != "" ) {
    _contract =
      _factory.attach(
        _contract_address);
  }
  else if ( _contract_address == "" ) {
    try {
      _contract =
        _factory.getDeployTransaction();
    } catch (e) {
      const
        _msg =
          `Encountered the above error.`;
      console.error(
        e);
      _msg_error(
        _msg,
        0);
    }
  }
  return _contract;
}

async function
  _contract_get_compiler_output(
    _wallet,
    _contract_address,
    _contract_compiler_output_path) {
  let
    _contract,
    _msg;
  if ( typeof(
         _contract_compiler_output_path) == "undefined" ||
       _contract_compiler_output_path == "" ) {
    _msg =
      `No contract compiler output path given in input.`;
    _msg_error(
      _msg,
      1);
  }
  if ( ! _file_exists(
           _contract_compiler_output_path) ) {
    _msg =
      `No contract compiler output found ` +
      `at path '${_contract_compiler_output_path}'.`;
    _msg_error(
      _msg,
      1);
  }
  const
    _contract_compiler_output =
      _file_read(
        _contract_compiler_output_path);
  const
    _factory =
      _contract_factory.fromSolidity(
        _contract_compiler_output,
        _wallet);
  if ( _contract_address != "" ) {
    _contract =
      _factory.attach(
        _contract_address);
  }
  else if ( _contract_address == "" ) {
    _contract = await
      _factory.getDeployTransaction();
  }
  return _contract;
}

async function
  _contract_get(
    _wallet_seed,
    _wallet_password_path,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _target_network,
    _api_key_path) {
  let
    _api_key,
    _contract,
    _contract_get_opts,
    _network_provider,
    _wallet,
    _wallet_get_opts,
    _wallet_path_list,
    _wallet_path;
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
  }
  _network_provider =
    _provider_get(
      _target_network,
      _api_key);
  _contract_get_opts =
    [];
  if ( _wallet_seed != "" ) {
    _wallet_path_list = [
      _dirname(
        _wallet_seed),
      "wallet.dat"
    ];
    _wallet_path =
      _path_join(
        _wallet_path_list);
    _wallet_get_opts = [
      _wallet_path,
      _wallet_password_path,
      _wallet_seed,
      _network_provider
    ];
    _wallet =
      _wallet_get.apply(
        null,
        _wallet_get_opts);
    _msg_info_wallet_selected(
      _wallet);
    _contract_get_opts.push(
      _wallet);
  }
  else {
    _contract_get_opts.push(
      _network_provider);
  }
  _contract_get_opts.push(
    _contract_address);
  if ( _contract_bytecode_path != "" ) {
    _contract_get_opts.push(
      _contract_abi_path,
      _contract_bytecode_path);
    _contract_get_fun =
      _contract_get_bytecode;
  }
  else if ( _contract_compiler_output_path != "" ) {
    _contract_get_opts.push(
      _contract_compiler_output_path);
    _contract_get_fun =
      _contract_get_compiler_output;
  }
  else if ( _contract_bytecode_path == "" && 
	    _contract_abi_path != "" ) {
    _contract_get_opts.push(
      _contract_abi_path);
    _contract_get_fun =
      _contract_get_abi;
  }
  else if ( _contract_bytecode_path == "" &&
	    _contract_abi_path == "" &&
            _contract_compiler_output_path == "" ) {
    _msg_error_no_input_data();
  }
  try {
    _contract = await
      _contract_get_fun.apply(
        null,
        _contract_get_opts);
  } catch (e) {
    console.error(
      e);
  }
  return _contract;
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [];
  _text.push(
    "             Wallet seed: {wallet_seed}".replace(
      "{wallet_seed}",
      wallet_seed));
  _text.push(
    "         Wallet password: {wallet_password_path}".replace(
      "{wallet_password_path}",
      wallet_password_path));
  _text.push(
    "        Contract address: {contract_address}".replace(
      "{contract_address}",
      contract_address));
  _text.push(
    "       Contract ABI path: {contract_abi_path}".replace(
      "{contract_abi_path}",
      contract_abi_path));
  _text.push(
    "       Contract bytecode: {contract_bytecode_path}".replace(
      "{contract_bytecode_path}",
      contract_bytecode_path));
  _text.push(
    "Contract compiler output: {contract_compiler_output_path}".replace(
      "{contract_compiler_output_path}",
      contract_compiler_output_path));
  _text.push(
    "          Target network: {target_network}".replace(
      "{target_network}",
      target_network));
  _text.push(
    "                 API Key: {api_key_path}".replace(
      "{api_key_path}",
      api_key_path));
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  contract-get",
    "    <quiet>",
    "    <wallet_seed>",
    "    <wallet_password_path>",
    "    <contract_address>",
    "    <contract_abi_path>",
    "    <contract_bytecode_path>",
    "    <contract_compiler_output_path>",
    "    <target_network>",
    "    (<api_key_path>)",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    "                                   Default: y",
    "  <wallet_seed>                    Path of the seed phrase.",
    "  <wallet_password_path>           Wallet password path.",
    "  <contract_address>               Contract of the address one is",
    "                                   getting the contract of.",
    "  <contract_abi_path>              Path of the contract ABI.",
    "  <contract_bytecode_path>         Path for the contract bytecode.",
    "  <contract_compiler_output_path>  Path for the contract compiler",
    "                                   output path (the hardhat artifact).",
    "  <target_network>                 Network on which the contract",
    "                                   resides.",
    "  <api_key_path>                   Path of the API key for the",
    "                                   contract ABI provider service.",
    "",
    "  Options:",
    "    -h                             This help."
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  _exit(
    _exit_code);
}

function _cmdline_parse() {
  quiet = "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        wallet_password_path =
          _value;
      }
      if ( _index == 5 ) {
        contract_address =
          _value;
      }
      if ( _index == 6 ) {
        contract_abi_path =
          _value;
      }
      if ( _index == 7 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _index == 8 ) {
        contract_compiler_output_path =
          _value;
      }
      if ( _index == 9 ) {
        target_network =
          _value;
      }
      if ( _index ==  10 ) {
        api_key_path =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage();
      }
    }
  );
  if ( contract_abi_path == "" &&
       contract_bytecode_path == "" && 
       contract_compiler_output_path == ""  ) {
    _usage();
  }
}

if ( _cmdline_check(
       "contract-get") ) {
  _global_variables();
  _cmdline_parse();
  _config_show();
  app_opts = [
    wallet_seed,
    wallet_password_path,
    contract_address,
    contract_abi_path,
    contract_bytecode_path,
    contract_compiler_output_path,
    target_network,
    api_key_path,
  ];
  _contract_get.apply(
    null,
    app_opts);
}

module.exports = {
  _contract_get:
    _contract_get
};
