#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     deployer-verify
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _deployer_get_module =
    await import(
      './deployer-get');
/* global
     _deployer_get */
const
  _deployer_get =
    _deployer_get_module._deployer_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "deployer-verify");
  /* global
       wallet_seed:
         writable */
  _set(
    "wallet",
    "seed",
    "");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       api_key_path:
         writable */
  _set(
    "api_key",
    "path",
    "");
  /* global
       chain_id:
         writable */
  _set(
    "chain",
    "id",
    "");
  /* global
       chain_name:
         writable */
  _set(
    "chain",
    "name",
    "");
  /* global
       target_network:
         writable */
  _set(
    "target",
    "network",
    "");
  /* global
       contract_address:
         writable */
  _set(
    "contract",
    "address",
    "");
  /* global
       contract_deployer:
         writable */
  _set(
    "contract",
    "deployer",
    "");
  /* global
       transaction_deployment:
         writable */
  _set(
    "transaction",
    "deployment",
    "");
  const
    _global =
      _global_get();
  /* global
       quiet:
         writable */
  _global[
    "quiet"] =
    "";
}

function
  _delay(
    _time) {
  return new Promise(resolve => setTimeout(resolve, _time));
}

async function
  _deployer_verify(
    _wallet_seed,
    _retries_max,
    _api_key_path,
    _chain_id,
    _chain_name,
    _target_network,
    _contract_address,
    _contract_deployer,
    _transaction_deployment) {
  let
    _is_deployer;
  const
    _deployer_get_opts = [
      _wallet_seed,
      _retries_max,
      _api_key_path,
      _chain_id,
      _chain_name,
      _target_network,
      _contract_address,
      _transaction_deployment
    ];
  const
    _deployer_real =
      await _deployer_get.apply(
        null,
        _deployer_get_opts);
  if ( typeof(
         _deployer_real) == "undefined" ) {
    const
      _msg =
        "Error obtaining the deployer from input data.";
    throw _msg;
  }
  if ( _contract_deployer == _deployer_real ) {
    _is_deployer =
      true;
  }
  else if ( _contract_deployer != _deployer_real ) {
    _is_deployer =
      false;
  }
  return _is_deployer;
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
    "deployer-get configuration:",
    `             Wallet seed: ${wallet_seed}`,
    `             Max retries: ${retries_max}`,
    `            API Key path: ${api_key_path}`,
    `                Chain ID: ${chain_id}`,
    `              Chain Name: ${chain_name}`,
    `          Target network: ${target_network}`,
    `        Contract address: ${contract_address}`,
    `       Contract deployer: ${contract_deployer}`,
    `  Deployment transaction: ${transaction_deployment}`
  ];
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Given a deployment transaction hash",
      "and a contract address, determines",
      "if an input address is the",
      "contract deployer.",
      "",
      "Usage:",
      "  deployer-verify",
      "    <quiet>",
      "    <wallet-seed>",
      "    <retries-max>",
      "    <api-key-path>",
      "    <chain-id>",
      "    <chain-name>",
      "    <target-network>",
      "    <contract-address>",
      "    <contract-deployer>",
      "    <transaction-deployment>",
      "",
      "Args:",
      "  <quiet>                          Can be 'y' or 'n'",
      "                                   Default: y",
      "  <wallet-seed>                    Path of the file containing",
      "                                   the seed phrase.",
      "  <retries-max>                    Maximum number of retries before",
      "                                   failing.",
      "  <api-key-path>                   Path of the API key for the",
      "                                   contract ABI provider service",
      "  <target-network>                 Network on which the contract",
      "                                   resides.",
      "  <contract-address>               Address of the contract.",
      "  <contract-deployer>              Address of the supposed deployer.",
      "  <transaction-deployment>         Contract deployment transaction.",
      "",
      "  Options:",
      "    -h                             This help."
    ];
  for (_line of _text) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _overrides_set() {
  _override_set(
    "retries",
    "max",
    10);
}

function
  _cmdline_parse() {
  let
    _msg;
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
  _argv.forEach(
    function (
      _value,
      _index) {
      if ( _index == 2 ) {
        _global[
          "quiet"] =
          _value;
      }
      if ( _index == 3 ) {
        _set(
          "wallet",
          "seed",
          _value);
      }
      if ( _index == 4 ) {
        _set(
          "retries",
          "max",
          _value);
      }
      if ( _index == 5 ) {
        _set(
          "api_key",
          "path",
          _value);
      }
      if ( _index == 6 ) {
        _set(
          "chain",
          "id",
          _value);
      }
      if ( _index == 7 ) {
        _set(
          "chain",
          "name",
          _value);
      }
      if ( _index == 8 ) {
        _set(
          "target",
          "network",
          _value);
      }
      if ( _index == 9 ) {
        _set(
          "contract",
          "address",
          _value);
      }
      if ( _index == 10 ) {
        _set(
          "contract",
          "deployer",
          _value);
      }
      if ( _index == 11 ) {
        _set(
          "transaction",
          "deployment",
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage(
          0);
      }
    }
  );
  const
    _contract_address =
      _get(
        "contract",
        "address");
  if ( _contract_address == "" ) {
    _msg =
      "No contract address specified.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _overrides_set();
    _usage(
      1);
  }
  const
    _contract_deployer =
      _get(
        "contract",
        "deployer");
  if ( _contract_deployer == "" ) {
    _msg =
      "No contract deployer specified.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _overrides_set();
    _usage(
      1);
  }
  const
    _transaction_deployment =
      _get(
        "transaction",
        "deployment");
  if ( _transaction_deployment == "" ) {
    _msg =
      "No deployement transaction specified.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _overrides_set();
    _usage(
      1);
  }
}

async function
  _deployer_verify_cmdline(
    _app_opts) {
  let
    _is_deployer;
  try {
    _is_deployer = 
      await _deployer_verify.apply(
        null,
        _app_opts);
    if ( typeof(
           _is_deployer) != "undefined" ) {
      _printf(
        _is_deployer.toString());
    }
    else {
      const
        _msg =
          "It has not been possile to discern from " +
          "input data whether the candidate deployer " +
          "is the contract actual deployer.";
      throw _msg;
    }
  } catch (_error) {
    _msg_error(
      _error,
      1);
  }
}

if ( await _cmdline_check(
       "deployer-verify") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    retries_max,
    api_key_path,
    chain_id,
    chain_name,
    target_network,
    contract_address,
    contract_deployer,
    transaction_deployment
  ];
  _deployer_verify_cmdline(
    app_opts);
}

export {
  _deployer_verify
};

// module.exports = {
//   _deployer_verify:
//     _deployer_verify
// };
