#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ---------------------------------------------------------------
 *     evmt-contract-call-static
 *     ---------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ---------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* Crash Javascript global variables */

/* global
     app_name:
       writable */
/* global
     app_opts:
       writable */
/* global
     quiet:
       writable */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _error_display */
const
  _error_display =
    _libcrash._error_display;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _printf */
const
  _printf =
    _libcrash._printf;
/* global
     _set */
const
  _set =
    _libcrash._set;
/* global
     _sleep */
const
  _sleep =
    _libcrash._sleep;
const
  _contract_get_module =
    await import(
      './contract-get');
/* global
     _contract_get */
const
  _contract_get =
    _contract_get_module._contract_get

function
  _global_variables() {
  _set(
    "app",
    "name",
    "evm-contract-call-static");
  _set(
    "app",
    "opts",
    []);
  /* global
       wallet_seed:
         writable */
  _set(
    "wallet",
    "seed",
    "");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       api_key_path:
         writable */
  _set(
    "api_key",
    "path",
    "");
  /* global
       target_network:
         writable */
  _set(
    "target",
    "network",
    "");
  /* global
       contract_address:
         writable */
  _set(
    "contract",
    "address",
    "");
  /* global
       contract_abi_path:
         writable */
  _set(
    "contract_abi",
    "path",
    "");
  /* global
       contract_bytecode_path:
         writable */
  _set(
    "contract_bytecode",
    "path",
    "");
  /* global
       contract_compiler_output_path:
         writable */
  _set(
    "contract_compiler_output",
    "path",
    "");
  /* global
       method_object:
         writable */
  _set(
    "method",
    "object",
    "");
  /* global
       contract_method:
         writable */
  _set(
    "contract",
    "method",
    "");
  /* global
       method_args:
         writable */
  _set(
    "method",
    "args",
    []);
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
}

function
  _msg_info_contract_obtained(
    _contract) {
  const
    _msg =
      `Contract '${_contract}' obtained.`;
  _msg_info(
    _msg);
}

function
  _msg_info_method_obtained(
    _method) {
  const
    _msg =
      "Method obtained.";
  _msg_info(
    _msg);
}

async function
  _contract_call_static(
    _wallet_seed,
    _retries_max,
    _api_key_path,
    _target_network,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _method_object,
    _contract_address,
    _contract_method,
    _method_args) {
  let
    _contract,
    _contract_get_opts,
    _method,
    _msg,
    _passed,
    _value;
  if ( _method_object == undefined ) {
    _method_object =
      "";
  }
  _retry =
    1;
  const
    _wallet_password =
      "";
  _contract_get_opts = [
    _wallet_seed,
    _wallet_password,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _target_network,
    _api_key_path,
  ];
  _passed = 
    false;
  while ( _retry <= _retries_max &&
          _passed == false ) {
    try {
      if ( _method_object === "" ||
           typeof(
             _method_object) === "undefined" ) {
        _contract =
          await _contract_get.apply(
            null,
            _contract_get_opts);
        _msg_info_contract_obtained(
          _contract);
        try {
          _method =
            await _contract.getFunction(
              _contract_method);
          _msg_info_method_obtained(
            _method);
	}
        catch(
          _error) {
          const
            _msg_no_fragment =
              "no matching fragment";
          const
            _msg_short =
              _error[
                "shortMessage"];
          if ( _msg_no_fragment == _msg_short ) {
            _msg =
              `Found no '${_contract_method}' method ` +
              `nor contract ABI '${_contract_abi_path}' ` +
              `nor in compiler output ` +
              `'${_contract_compiler_output_path}'.`;
            _msg_error(
              _msg,
              0);
	  }
          throw _error;
	}
      }
      else if ( _method_object != "" ||
                _method_object != undefined ) {
        _msg =
          "Re-using contract method.";
        _msg_info(
          _msg);
        _method =
          _method_object;
      }
      _value =
        await _method.staticCall.apply(
          null,
          _method_args);
      if ( _value != undefined ) {
        _passed =
          true;
      }
      else if ( _value == undefined ) {
        throw { "error": {
                  "message":
                    "Value undefined, static call error" } };
      }
    } catch (
        _error) {
      _error_display(
        _error);
      _retry =
        _retry + 1;
      _msg_error(
        "Increasing retry and waiting 3 seconds.",
        0);
      await _sleep(
        3000);
    }
  }
  if ( _retry > _retries_max ) {
    throw { "error": {
              "message":
                "Maximum number of retries reached." } };
  }
  return [
    _value,
    _method
  ];
}

function
  _config_show() {
  let
    _line;
  const
    _method_args =
      method_args.join(
      " ");
  const
    _program =
      _basename(
        _argv[
          0]);
  const
    _text = [
      `  ${_program} configuration:`,
      `             Wallet seed: ${wallet_seed}`,
      `             Max retries: ${retries_max}`,
      `            API Key path: ${api_key_path}`,
      `          Target network: ${target_network}`,
      `            Contract ABI: ${contract_abi_path}`,
      `       Contract bytecode: ${contract_bytecode_path}`,
      `Contract compiler output: ${contract_compiler_output_path}`,
      `        Contract address: ${contract_address}`,
      `         Contract method: ${contract_method}`,
      `             Method args: ${_method_args}`
    ];
  for (_line of _text)  { 
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          0]);
  const
    _text = [
      "Execute a static call to an EVM network's contract method",
      "",
      "Usage:",
      `  ${_program}`,
      "    <quiet>",
      "    <wallet-seed>",
      "    <retries-max>",
      "    <api-key-path>",
      "    <target-network>",
      "    <contract-abi-path>",
      "    <contract-bytecode-path>",
      "    <contract-compiler-output-path>",
      "    <contract-address>",
      "    <contract-method>",
      "    <method-args>",
      "",
      "Args:",
      "  <quiet>                          Can be 'y' or 'n'",
      "                                   Default: y",
      "  <wallet-seed>                    Path of the file containing",
      "                                   the seed phrase.",
      "  <retries-max>                    Maximum number of retries before",
      "                                   failing.",
      "  <api-key-path>                   Path of the API key for the",
      "                                   contract ABI provider service",
      "  <target-network>                 Network on which the contract",
      "                                   resides.",
      "  <contract-abi-path>              Path of the contract ABI",
      "  <contract-bytecode-path>         Path for the contract bytecode",
      "  <contract-compiler-output-path>  Path for the contract compiler",
      "                                   output path (the hardhat artifact).",
      "  <contract-address>               Address of the contract",
      "  <contract-method>                Contract method to execute",
      "  [method-args]                    Arguments to pass to the method",
      "",
      "  Options:",
      "    -h                             This help."
    ];
  for (_line of _text) {
    _msg_info(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _overrides_set() {
  _override_set(
    "retries",
    "max",
    100);
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        retries_max =
          _value;
      }
      if ( _index == 5 ) {
        api_key_path =
          _value;
      }
      if ( _index == 6 ) {
        target_network =
          _value;
      }
      if ( _index == 7 ) {
        contract_abi_path =
          _value;
      }
      if ( _index == 8 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _index == 9 ) {
        contract_compiler_output_path =
          _value;
      }
      if ( _index == 10 ) {
        contract_address =
          _value;
      }
      if ( _index == 11 ) {
        contract_method =
          _value;
      }
      if ( 11 < _index ) {
        method_args.push(
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage(
          0);
      }
    }
  );
  if ( contract_address == "" ) {
    _usage(
      1);
  }
}

async function
  _contract_call_static_cmdline(
    _app_opts) {
  let
    _method_object,
    _msg,
    _value;
  try {
    [_value,
     _method_object] = 
      await _contract_call_static.apply(
        null,
        _app_opts);
    if ( _value != undefined ) {
      _printf(
        _value.toString());
    }
    else {
      _msg =
        "Static contract call returned undefined value.";
      throw { "error": {
                "message":
                  _msg } };
    }
  } catch (
      _error) {
      _error_display(
        _error);
      _msg =
        "Error while running static call.";
      _msg_error(
        _msg,
        1);
  }
}


if ( await _cmdline_check(
       "evm-contract-call-static") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    retries_max,
    api_key_path,
    target_network,
    contract_abi_path,
    contract_bytecode_path,
    contract_compiler_output_path,
    method_object,
    contract_address,
    contract_method,
    method_args
  ];
  _contract_call_static_cmdline(
    app_opts);
}

export {
  _contract_call_static
};

// module.exports = {
//   _contract_call_static:
//     _contract_call_static
// };

